/*
 * Acmdrv.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-audio.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_ACMDRV_H
#define AKARI_ACMDRV_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms895510 ACM_Close: print `BOOL ACM_Close(DWORDdwOpenData);` */
BOOL ACM_Close(DWORD dwOpenData);
/* ms895511 ACM_Deinit: print `PVOID ACM_Deinit(DWORD dwData);` */
PVOID ACM_Deinit(DWORD dwData);
/* ms896097 ACM_Init: print `PVOID ACM_Init(DWORDdwInfo);` */
AKARI_CE_IMPORT PVOID ACM_Init(DWORD dwInfo)
    AKARI_CE_NAME(ACM_Init);
/* ms896098 ACM_IOControl: print `BOOL ACM_IOControl(DWORDdwOpenData,DWORDdwCode,PBYTE pBufIn,DWORDdwLenIn,PBYTE pBufOut,DWORD dwLenOut,PDWORD pdwActualOut);` */
AKARI_CE_IMPORT BOOL ACM_IOControl(DWORD dwOpenData, DWORD dwCode, PBYTE pBufIn, DWORD dwLenIn, PBYTE pBufOut, DWORD dwLenOut, PDWORD pdwActualOut)
    AKARI_CE_NAME(ACM_IOControl);
/* ms896099 ACM_Open (ACM Driver): print `` */
AKARI_CE_IMPORT PVOID ACM_Open(DWORD dwData, DWORD dwAccess, DWORD dwShareMode)
    AKARI_CE_NAME(ACM_Open);
/* ms896100 ACM_PowerDown: print `void ACM_PowerDown(void);` */
AKARI_CE_IMPORT void ACM_PowerDown(void)
    AKARI_CE_NAME(ACM_PowerDown);
/* ms896101 ACM_PowerUp: print `void ACM_PowerUp(void);` */
AKARI_CE_IMPORT void ACM_PowerUp(void)
    AKARI_CE_NAME(ACM_PowerUp);
/* ms896102 ACM_Read: print `DWORD ACM_Read(DWORD dwOpenData,LPVOID pBuf,DWORD len);` */
AKARI_CE_IMPORT DWORD ACM_Read(DWORD dwOpenData, LPVOID pBuf, DWORD len)
    AKARI_CE_NAME(ACM_Read);
/* ms896103 ACM_Seek: print `DWORD ACM_Seek(DWORD dwOpenData,long pos,DWORD type);` */
/* (record-only: parameter or return type unpublished) */
/* ms896104 ACM_Write: print `DWORD ACM_Write(DWORD dwOpenData,LPCVOID pBuf,DWORD len);` */
AKARI_CE_IMPORT DWORD ACM_Write(DWORD dwOpenData, LPCVOID pBuf, DWORD len)
    AKARI_CE_NAME(ACM_Write);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_ACMDRV_H */
