/*
 * Avc_vcr.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-1394.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_AVC_VCR_H
#define AKARI_AVC_VCR_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-1394 (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923264 VCR_RequestResponse -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } u; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_AVC_VCR_H */
