/*
 * Avc_unit.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-1394.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_AVC_UNIT_H
#define AKARI_AVC_UNIT_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-1394 (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct PDEVICE_OBJECT PDEVICE_OBJECT;   /* opaque carrier (layout unpublished) */
typedef struct PFILE_OBJECT PFILE_OBJECT;   /* opaque carrier (layout unpublished) */
/* aa448229 UNIT_AllocateLocalPlug_Response (page print, compiled) */
typedef struct  {
    HANDLE ualp_Plug;
    ULONG ualp_PlugNumber;
} UNIT_AllocateLocalPlug_Response;
/* aa448231 UNIT_ConnectionRequestProcessed_Request (page print, compiled) */
typedef struct  {
    PVOID ucrp_RegistrationToken;
    PVOID ucrp_Request;
    NTSTATUS ucrp_Status;
} UNIT_ConnectionRequestProcessed_Request;
/* aa448233 UNIT_DereferenceConnectionPlug_Request (page print, compiled) */
typedef struct  {
    PVOID udcp_RegistrationToken;
    HANDLE udcp_Plug;
} UNIT_DereferenceConnectionPlug_Request;
/* aa448236 UNIT_FreeLocalPlug_Request (page print, compiled) */
typedef struct  {
    PVOID uflp_RegistrationToken;
    HANDLE uflp_Plug;
} UNIT_FreeLocalPlug_Request;
/* aa448238 UNIT_ProcessRegistryPlugs_Request (page print, compiled) */
typedef struct  {
    PVOID uprp_RegistrationToken;
    HANDLE uprp_RootKey;
} UNIT_ProcessRegistryPlugs_Request;
/* aa448239 UNIT_QueryLocalPlugs_Request (page print, compiled) */
typedef struct  {
    PVOID uqlp_RegistrationToken;
    ULONG uqlp_Flags;
} UNIT_QueryLocalPlugs_Request;
/* aa448240 UNIT_QueryLocalPlugs_Response (page print, compiled) */
typedef struct  {
    BOOL uqlp_PlugState;
    ULONG uqlp_PlugNumber;
    ULONG uqlp_Direction;
    ULONG uqlp_MediaType;
    HANDLE uqlp_Plug;
} UNIT_QueryLocalPlugs_Response;
/* aa448242 UNIT_RegisterSubunit_Response (page print, compiled) */
typedef struct  {
    PVOID urs_RegistrationToken;
} UNIT_RegisterSubunit_Response;
/* aa448228 UNIT_AllocateLocalPlug_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } UNIT_AllocateLocalPlug_Request; */
/* aa448241 UNIT_RegisterSubunit_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } UNIT_RegisterSubunit_Request; */
/* aa448230 UNIT_CloseUnitDeviceObject: print `NTSTATUS UNIT_CloseUnitDeviceObject(PFILE_OBJECT UnitFileObject, PDEVICE_OBJECT UnitDeviceObject);` */
AKARI_CE_IMPORT NTSTATUS UNIT_CloseUnitDeviceObject(PFILE_OBJECT UnitFileObject, PDEVICE_OBJECT UnitDeviceObject)
    AKARI_CE_NAME(UNIT_CloseUnitDeviceObject);
/* aa448237 UNIT_OpenUnitDeviceObject: print `NTSTATUS UNIT_OpenUnitDeviceObject(PDEVICE_OBJECT SubunitParentDeviceObject, PFILE_OBJECT* UnitFileObject, PDEVICE_OBJECT* UnitDeviceObject);` */
AKARI_CE_IMPORT NTSTATUS UNIT_OpenUnitDeviceObject(PDEVICE_OBJECT SubunitParentDeviceObject, PFILE_OBJECT* UnitFileObject, PDEVICE_OBJECT* UnitDeviceObject)
    AKARI_CE_NAME(UNIT_OpenUnitDeviceObject);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_AVC_UNIT_H */
