/*
 * Avc_vvcr.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-1394.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_AVC_VVCR_H
#define AKARI_AVC_VVCR_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-1394 (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923270 VVCR_Complete_Request (page print, compiled) */
typedef struct  {
    PVOID vvcr_RequestIdentifier;
    BOOL vvcr_Status;
} VVCR_Complete_Request;
/* ms923271 VVCR_Event_Request (page print, compiled) */
typedef struct  {
    ULONG vve_Flags;
} VVCR_Event_Request;
/* ms923273 VVCR_EVENT_Type (page print, compiled) */
typedef enum  {
    VVCR_EVENT_PlugStateChange,
    VVCR_EVENT_ConnectToRemotePlug,
    VVCR_EVENT_PlayRequest,
    VVCR_EVENT_RecordRequest,
    VVCR_EVENT_WindRequest,
    VVCR_EVENT_RelativeTimeCounter,
    VVCR_EVENT_TimeCode,
    VVCR_EVENT_AbsoluteTrackNumber
} VVCR_EVENT_Type;
/* ms923274 VVCR_MECHANISM_STATE (page print, compiled) */
typedef enum  {
    VVCR_MECHANISM_STATE_Stopped,
    VVCR_MECHANISM_STATE_Playing,
    VVCR_MECHANISM_STATE_Recording,
    VVCR_MECHANISM_STATE_Rewinding,
    VVCR_MECHANISM_STATE_FastForwarding,
    VVCR_MECHANISM_STATE_HighSpeedRewinding
} VVCR_MECHANISM_STATE;
/* ms923276 VVCR_SetMechanismPosition_Request (page print, compiled) */
typedef struct  {
    BYTE vvsmp_Hour;
    BYTE vvsmp_Minute;
    BYTE vvsmp_Second;
    BYTE vvsmp_Frame;
    BOOL vvsmp_Negative;
} VVCR_SetMechanismPosition_Request;
/* ms923277 VVCR_SetMechanismState_Request (page print, compiled) */
typedef struct  {
    VVCR_MECHANISM_STATE vsms_State;
} VVCR_SetMechanismState_Request;
/* ms923278 VVCR_SetMechanismTrackNumber_Request (page print, compiled) */
typedef struct  {
    ULONG vvsmtn_TrackNumber;
} VVCR_SetMechanismTrackNumber_Request;
/* ms923272 VVCR_Event_Response -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } PlugStateChange; */
/* ms923275 VVCR_QueryState_Response -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } VVCR_QueryState_Response; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_AVC_VVCR_H */
