/*
 * Avc_stream.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-1394.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_AVC_STREAM_H
#define AKARI_AVC_STREAM_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-1394 (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896115 AUDIO_SampleFrequency (page print, compiled) */
typedef enum  {
    AUDIO_SampleFrequency_32Khz = 0,
    AUDIO_SampleFrequency_44_1Khz,
    AUDIO_SampleFrequency_48Khz,
    AUDIO_SampleFrequency_88_2Khz,
    AUDIO_SampleFrequency_96Khz,
    AUDIO_SampleFrequency_176_4Khz,
    AUDIO_SampleFrequency_192Khz
} AUDIO_SampleFrequency;
/* aa448155 STREAM_CreateLocalPlug_Response (page print, compiled) */
typedef struct  {
    HANDLE sclp_Plug;
    ULONG sclp_PlugNumber;
} STREAM_CreateLocalPlug_Response;
/* aa448156 STREAM_DeleteLocalPlug_Request (page print, compiled) */
typedef struct  {
    HANDLE sdlp_Plug;
} STREAM_DeleteLocalPlug_Request;
/* aa448157 STREAM_DereferenceRemotePlug_Request (page print, compiled) */
typedef struct  {
    ULONG sdrp_Direction;
    ULONG sdrp_SubunitPlugID;
    ULONG sdrp_PlugNumber;
    PVOID sdrp_PlugToken;
} STREAM_DereferenceRemotePlug_Request;
/* aa448160 STREAM_GetMediaSize_Response (page print, compiled) */
typedef struct  {
    ULONG sgms_PacketSize;
    ULONG sgms_FrameSize;
} STREAM_GetMediaSize_Response;
/* aa448161 STREAM_GetRemotePlugHandle_Request (page print, compiled) */
typedef struct  {
    ULONG sgrph_PlugNumber;
    ULONG sgrph_PlugDirection;
} STREAM_GetRemotePlugHandle_Request;
/* aa448162 STREAM_GetRemotePlugHandle_Response (page print, compiled) */
typedef struct  {
    HANDLE sgrph_Plug;
} STREAM_GetRemotePlugHandle_Response;
/* aa448163 STREAM_LocateRemotePlug_Request (page print, compiled) */
typedef struct  {
    ULONG slrp_MediaType;
    ULONG slrp_Direction;
    ULONG slrp_SubunitPlugID;
} STREAM_LocateRemotePlug_Request;
/* aa448164 STREAM_LocateRemotePlug_Response (page print, compiled) */
typedef struct  {
    ULONG slrp_PlugNumber;
    PVOID slrp_PlugToken;
} STREAM_LocateRemotePlug_Response;
/* aa448165 STREAM_MediaType (page print, compiled) */
typedef enum  {
    STREAM_MediaType_MPEG = 0,
    STREAM_MediaType_MPEG_TimeShifted,
    STREAM_MediaType_DSS,
    STREAM_MediaType_DSS_TimeShifted,
    STREAM_MediaType_Audio_AM824,
    STREAM_MediaType_Audio_24x4Pack,
    STREAM_MediaType_Audio_32fp,
    STREAM_MediaType_DV_SD_625_50Hz,
    STREAM_MediaType_DV_SD_525_60Hz,
    STREAM_MediaType_DV_SDL_625_50Hz,
    STREAM_MediaType_DV_SDL_525_60Hz,
    STREAM_MediaType_DV_HD_1250_50Hz,
    STREAM_MediaType_DV_HD_1125_60Hz,
    STREAM_MediaType_Default = 0xFFFF
} STREAM_MediaType;
/* aa448168 STREAM_SetMediaSize_Request (page print, compiled) */
typedef struct  {
    STREAM_MediaType ssms_MediaType;
    ULONG ssms_FrameSize;
} STREAM_SetMediaSize_Request;
/* aa448152 STREAM_AttachBuffers_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_AttachBuffers_Request; */
/* aa448153 STREAM_AttachBuffers_Response -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_AttachBuffers_Response; */
/* aa448154 STREAM_CreateLocalPlug_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_CreateLocalPlug_Request; */
/* aa448158 STREAM_DetachBuffers_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_DetachBuffers_Request; */
/* aa448159 STREAM_GetMediaSize_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_GetMediaSize_Request; */
/* aa448166 STREAM_QueryBufferState_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_QueryBufferState_Request; */
/* aa448167 STREAM_QueryBufferState_Response -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_QueryBufferState_Response; */
/* aa448169 STREAM_StartReceiveSession_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_StartReceiveSession_Request; */
/* aa448170 STREAM_StartReceiveSession_Response -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_StartReceiveSession_Response; */
/* aa448171 STREAM_StartTransmitSession_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_StartTransmitSession_Request; */
/* aa448172 STREAM_StartTransmitSession_Response -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_StartTransmitSession_Response; */
/* aa448173 STREAM_StopSession_Request -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } STREAM_StopSession_Request; */

/* ------------------------------------------------------------------
 * Book surface: drivers-1394 (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890559 Application Session Buffers */
/* ms890566 Application Session Data Transfer */
/* ms890572 Application Session Starting */
/* ms890581 Application Session Stopping */
/* ms892180 IEEE 1394 AV/C VCR Subunit Driver Development Concepts */
/* ms892181 IEEE 1394 AV/C VCR Subunit Driver Samples */
/* ms892184 IEEE 1394 Bus Driver Samples */
/* ms892185 IEEE 1394 Data Transfers */
/* ms892187 IEEE 1394 Driver Thread Priorities */
/* ms892188 IEEE 1394 Sample Communication */
/* ms892189 IEEE 1394 SBP-2 Driver Development Concepts */
/* ms892191 IEEE 1394 SBP-2 Driver Registry Settings */
/* ms892190 IEEE 1394 SBP-2 Driver Samples */
/* ms892192 IEEE 1394 Streaming Filter Driver Architecture */
/* ms892193 IEEE 1394 Streaming Filter Driver Differences in Media Types */
/* ms892194 IEEE 1394 Streaming Filter Driver IOCTL Processing Requirements */
/* ms892195 IEEE 1394 Streaming Filter Driver IRP Processing Requirements Complex Form */
/* ms892196 IEEE 1394 Streaming Filter Driver IRP Processing Requirements Incorrect Form */
/* ms892197 IEEE 1394 Streaming Filter Driver IRP Processing Requirements Simple Form */
/* ms892199 IEEE 1394 Streaming Filter Driver Registry Settings */
/* ms892201 IEEE 1394 Streaming Filter Driver Samples */
/* ms892204 IEEE 1394 Unit Filter Driver Architecture */
/* ms892205 IEEE 1394 Unit Filter Driver Destination Selection */
/* ms892206 IEEE 1394 Unit Filter Driver Plug Allocation */
/* ms892207 IEEE 1394 Unit Filter Driver Plug Management */
/* ms892208 IEEE 1394 Unit Filter Driver Registration */
/* ms892209 IEEE 1394 Unit Filter Driver Registry Settings */
/* ms892211 IEEE 1394 Unit Filter Driver Samples */
/* ms892212 IEEE 1394 Unit Filter Driver Streaming */
/* ms892213 IEEE 1394 Virtual VCR Application */
/* ms892214 IEEE 1394 Virtual VCR Driver Architecture */
/* ms892215 IEEE 1394 Virtual VCR Driver Registry Settings */
/* ms892217 IEEE 1394 Virtual VCR Driver Samples */
/* aa447548 Plug Finding */
/* ms894014 Serial Bus and Subunit Plug Association */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_AVC_STREAM_H */
