/*
 * Battimpl.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-battery.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_BATTIMPL_H
#define AKARI_BATTIMPL_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896135 BatteryPDDDeinitialize: print `void WINAPI BatteryPDDDeinitialize(void);` */
void WINAPI BatteryPDDDeinitialize(void);
/* ms896136 BatteryPDDGetLevels: print `LONG BatteryPDDGetLevels(void);` */
LONG BatteryPDDGetLevels(void);
/* ms896137 BatteryPDDGetStatus: print `BOOL WINAPI BatteryPDDGetStatus( PSYSTEM_POWER_STATUS_EX2 pstatus, PBOOL pfBatteriesChangedSinceLastCall);` */
BOOL WINAPI BatteryPDDGetStatus(PSYSTEM_POWER_STATUS_EX2 pstatus, PBOOL pfBatteriesChangedSinceLastCall);
/* ms896138 BatteryPDDInitialize: print `BOOL WINAPI BatteryPDDInitialize( LPCTSTR pszRegistryContext);` */
BOOL WINAPI BatteryPDDInitialize(LPCTSTR pszRegistryContext);
/* ms896139 BatteryPDDPowerHandler: print `void WINAPI BatteryPDDPowerHandler( BOOL bOff);` */
void WINAPI BatteryPDDPowerHandler(BOOL bOff);
/* ms896140 BatteryPDDResume: print `void WINAPI BatteryPDDResume(void);` */
void WINAPI BatteryPDDResume(void);
/* ms896141 BatteryPDDSupportsChangeNotification: print `BOOL BatteryPDDSupportsChangeNotification(void);` */
BOOL BatteryPDDSupportsChangeNotification(void);

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-battery (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919400 PFN_BATTERY_PDD_IOCONTROL: prototype printed by the page; derived at the M99 sweep. */
typedef DWORD (*PFN_BATTERY_PDD_IOCONTROL)(DWORD dwContext, DWORD Ioctl, PUCHAR pInBuf, DWORD InBufLen, PUCHAR pOutBuf, DWORD OutBufLen, PDWORD pdwBytesTransferred);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_BATTIMPL_H */
