/*
 * Bt_hcip.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-bthci.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_BT_HCIP_H
#define AKARI_BT_HCIP_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-bthci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct BD_BUFFER BD_BUFFER;   /* opaque carrier (layout unpublished) */
typedef struct HCI_PARAMETERS HCI_PARAMETERS;   /* opaque carrier (layout unpublished) */
typedef struct HCI_TYPE HCI_TYPE;   /* opaque carrier (layout unpublished) */
/* ms899386 HCI_PARAMETERS -- HELD (page print; member types unpublished):
 *   typedef struct __hci_parameters { ... } HCI_PARAMETERS; */
typedef struct HCI_TYPE HCI_TYPE;   /* referenced; no page prints a layout */
/* ms899383 HCI_CloseConnection: print `void HCI_CloseConnection(void);` */
AKARI_CE_IMPORT void HCI_CloseConnection(void)
    AKARI_CE_NAME(HCI_CloseConnection);
/* ms899385 HCI_OpenConnection: print `int HCI_OpenConnection(void);` */
AKARI_CE_IMPORT int HCI_OpenConnection(void)
    AKARI_CE_NAME(HCI_OpenConnection);
/* ms899387 HCI_ReadHciParameters: print `int HCI_ReadHciParameters(HCI_PARAMETERS* pParms);` */
AKARI_CE_IMPORT int HCI_ReadHciParameters(HCI_PARAMETERS* pParms)
    AKARI_CE_NAME(HCI_ReadHciParameters);
/* ms899388 HCI_ReadPacket: print `int HCI_ReadPacket(HCI_TYPE* peType, BD_BUFFER* pInBuffer);` */
AKARI_CE_IMPORT int HCI_ReadPacket(HCI_TYPE* peType, BD_BUFFER* pInBuffer)
    AKARI_CE_NAME(HCI_ReadPacket);
/* ms899389 HCI_SetCallback: print `typedef int (*HCI_TransportCallback)(HCI_EVENT eEvent, void* pEvent);int HCI_SetCallback(HCI_TransportCallback pfCallback);` -- recorded verbatim (no compiled prototype) */
/* ms899390 HCI_StartHardware: print `int HCI_StartHardware(void);` */
AKARI_CE_IMPORT int HCI_StartHardware(void)
    AKARI_CE_NAME(HCI_StartHardware);
/* ms899391 HCI_StopHardware: print `int HCI_StopHardware(void);` */
AKARI_CE_IMPORT int HCI_StopHardware(void)
    AKARI_CE_NAME(HCI_StopHardware);
/* ms899393 HCI_WritePacket: print `int HCI_WritePacket(HCI_TYPE eType, BD_BUFFER* pOutBuffer);` */
AKARI_CE_IMPORT int HCI_WritePacket(HCI_TYPE eType, BD_BUFFER* pOutBuffer)
    AKARI_CE_NAME(HCI_WritePacket);

/* ------------------------------------------------------------------
 * Book surface: drivers-bthci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890928 Bluetooth HCI Transport Driver Registry Settings */
/* ms890956 Bluetooth Stack Architecture */
/* ms890965 Bluetooth Stack Implementation Considerations */
/* ms890977 Bluetooth Stack Implementation in Windows CE */
/* aa447431 Closing Connections */
/* aa447457 Debug/Auxiliary */
/* ms892245 Internal Representation for Bluetooth Address */
/* ms892428 IO Control and Other Common Stack Functions */
/* ms892493 Memory Utilization */
/* aa447430 Opening Connections */
/* ms894022 Shared Thread Pool */
/* ms894023 Sharing Responsibilities */
/* ms894035 Supported HCI Transport Drivers */
/* aa447440 Transferring Data */

/* ------------------------------------------------------------------
 * Book surface: drivers-bthci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890928 Bluetooth HCI Transport Driver Registry Settings */
/* ms890956 Bluetooth Stack Architecture */
/* ms890965 Bluetooth Stack Implementation Considerations */
/* ms890977 Bluetooth Stack Implementation in Windows CE */
/* aa447431 Closing Connections */
/* aa447457 Debug/Auxiliary */
/* ms892245 Internal Representation for Bluetooth Address */
/* ms892428 IO Control and Other Common Stack Functions */
/* ms892493 Memory Utilization */
/* aa447430 Opening Connections */
/* ms894022 Shared Thread Pool */
/* ms894023 Sharing Responsibilities */
/* ms894035 Supported HCI Transport Drivers */
/* aa447440 Transferring Data */

/* ------------------------------------------------------------------
 * Book surface: drivers-bthci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890928 Bluetooth HCI Transport Driver Registry Settings */
/* ms890956 Bluetooth Stack Architecture */
/* ms890965 Bluetooth Stack Implementation Considerations */
/* ms890977 Bluetooth Stack Implementation in Windows CE */
/* aa447431 Closing Connections */
/* aa447457 Debug/Auxiliary */
/* ms892245 Internal Representation for Bluetooth Address */
/* ms892428 IO Control and Other Common Stack Functions */
/* ms892493 Memory Utilization */
/* aa447430 Opening Connections */
/* ms894022 Shared Thread Pool */
/* ms894023 Sharing Responsibilities */
/* ms894035 Supported HCI Transport Drivers */
/* aa447440 Transferring Data */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_BT_HCIP_H */
