/*
 * Cardserv.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-pccard.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CARDSERV_H
#define AKARI_CARDSERV_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447649 CARD_SOCKET_HANDLE -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_SOCKET_HANDLE, *PCARD_SOCKET_HANDLE; */
/* aa447637 CardReleaseSocketMask: print `STATUS CardReleaseSocketMask(CARD_CLIENT_HANDLE hCardClient,CARD_SOCKET_HANDLE hSock);` */
/* (record-only: parameter or return type unpublished) */
/* aa447643 CardRequestIRQ: print `STATUS CardRequestIRQ(CARD_CLIENT_HANDLE hCardClient,CARD_SOCKET_HANDLE hSocket,CARD_ISR ISRFunction,UINT32 uISRContextData);` */
/* (record-only: parameter or return type unpublished) */
/* aa447645 CardRequestSocketMask: print `STATUS CardRequestSocketMask(CARD_CLIENT_HANDLEhCardClient,CARD_SOCKET_HANDLEhSock,UINT16fEventMask);` -- recorded verbatim (no compiled prototype) */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896162 CARD_EVENT: documented name-only (no value published; held) */
/* aa447630 CardPowerOff: documented name-only (no value published; held) */
/* aa447631 CardPowerOn: documented name-only (no value published; held) */
/* aa447667 CLIENT_CALLBACK: documented name-only (no value published; held) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_CARDSERV_H */
