/*
 * Cardsv2.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-pccard.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CARDSV2_H
#define AKARI_CARDSV2_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896159 CARD_CONFIG_INFO -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_CONFIG_INFO, *PCARD_CONFIG_INFO; */
/* ms896160 CARD_DATA_PARMS -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_DATA_PARMS, *PCARD_DATA_PARMS; */
/* ms896163 CARD_EVENT_MASK_PARMS -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_EVENT_MASK_PARMS, *PCARD_EVENT_MASK_PARMS; */
/* ms896164 CARD_EVENT_PARMS -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_EVENT_PARMS, *PCARD_EVENT_PARMS; */
/* aa447633 CARD_REGISTER_PARMS -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_REGISTER_PARMS, *PCARD_REGISTER_PARMS; */
/* aa447650 CARD_STATUS -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_STATUS, *PCARD_STATUS; */
/* aa447651 CARD_TUPLE_PARMS -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_TUPLE_PARMS, *PCARD_TUPLE_PARMS; */
/* aa447654 CARD_WINDOW_ADDRESS -- HELD (page print; member types unpublished):
 *   typedef struct CARD_WINDOW_ADDRESS { ... } CARD_WINDOW_ADDRESS, *PCARD_WINDOW_ADDRESS; */
/* aa447653 CARD_WINDOW_PARMS -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } CARD_WINDOW_PARMS, *PCARD_WINDOW_PARMS; */
/* ms896157 CardAccessConfigurationRegister: print `STATUS CardAccessConfigurationRegister(CARD_CLIENT_HANDLEhCardClient,CARD_SOCKET_HANDLEhSocket,UINT8 rw_flag,UINT8 offset,UINT8* pValue);` -- recorded verbatim (no compiled prototype) */
/* ms896161 CardDeregisterClient: print `STATUS CardDeregisterClient(CARD_CLIENT_HANDLEhCardClient);` -- recorded verbatim (no compiled prototype) */
/* ms896165 CardGetEventMask: print `STATUS CardGetEventMask(CARD_CLIENT_HANDLEhCardClient,PCARD_EVENT_MASK_PARMSpMaskParms);` -- recorded verbatim (no compiled prototype) */
/* ms896167 CardGetNextTuple: print `STATUS CardGetNextTuple(PCARD_TUPLE_PARMSpGetTupleParms);` -- recorded verbatim (no compiled prototype) */
/* ms896168 CardGetParsedTuple: print `STATUS CardGetParsedTuple(CARD_SOCKET_HANDLEhSocket,UINT8uDesiredTuple,PVOIDpBuf,PUINT32 pnItems);` -- recorded verbatim (no compiled prototype) */
/* ms896169 CardGetStatus: print `STATUS CardGetStatus(PCARD_STATUSpStatus);` -- recorded verbatim (no compiled prototype) */
/* ms896170 CardGetTupleData: print `STATUS CardGetTupleData(PCARD_DATA_PARMSpTupleDataParms);` -- recorded verbatim (no compiled prototype) */
/* ms896172 CardMapWindow: print `PVOID CardMapWindow(CARD_WINDOW_HANDLEhCardWindow,UINT32 uCardAddress,UINT32 uSize,PUINT32pGranularity);` -- recorded verbatim (no compiled prototype) */
/* ms896173 CardMapWindowPhysical: print `STATUS CardMapWindowPhysical(CARD_WINDOW_HANDLEhCardWindow,PCARD_WINDOW_ADDRESSpCardWindowAddr);` -- recorded verbatim (no compiled prototype) */
/* aa447629 CardModifyWindow: print `STATUS CardModifyWindow(CARD_WINDOW_HANDLEhCardWindow,UINT16fAttributes,UINT8fAccessSpeed);` -- recorded verbatim (no compiled prototype) */
/* aa447632 CardRegisterClient: print `CARD_CLIENT_HANDLE CardRegisterClient(CLIENT_CALLBACKCallBackFn,PCARD_REGISTER_PARMSpParms);` -- recorded verbatim (no compiled prototype) */
/* aa447634 CardReleaseConfiguration: print `STATUS CardReleaseConfiguration(CARD_CLIENT_HANDLEhCardClient,CARD_SOCKET_HANDLEhSock);` -- recorded verbatim (no compiled prototype) */
/* aa447635 CardReleaseExclusive: print `STATUS CardReleaseExclusive(CARD_CLIENT_HANDLEhCardClient,CARD_SOCKET_HANDLEhSocket);` -- recorded verbatim (no compiled prototype) */
/* aa447636 CardReleaseIRQ: print `STATUS CardReleaseIRQ(CARD_CLIENT_HANDLE hCardClient,CARD_SOCKET_HANDLE hSocket);` */
/* (record-only: parameter or return type unpublished) */
/* aa447638 CardReleaseWindow: print `STATUS CardReleaseWindow(CARD_WINDOW_HANDLE hCardWin);` */
/* (record-only: parameter or return type unpublished) */
/* aa447639 CardRequestConfigRegisterPhAddr: print `STATUS CardRequestConfigRegisterPhAddr(CARD_CLIENT_HANDLEhCardClient,CARD_SOCKET_HANDLEhSock, PCARD_WINDOW_ADDRESS pCardWindowAddr, PDWORD pOffset);` -- recorded verbatim (no compiled prototype) */
/* aa447640 CardRequestConfiguration: print `STATUS CardRequestConfiguration(CARD_CLIENT_HANDLE hCardClient,PCARD_CONFIG_INFO pParms);` */
/* (record-only: parameter or return type unpublished) */
/* aa447641 CardRequestDisable: print `STATUS CardRequestDisable(CARD_CLIENT_HANDLEhCardClient,CARD_SOCKET_HANDLEhSock);` -- recorded verbatim (no compiled prototype) */
/* aa447642 CardRequestExclusive: print `STATUS CardRequestExclusive(CARD_CLIENT_HANDLE hCardClient,CARD_SOCKET_HANDLE hSocket);` */
/* (record-only: parameter or return type unpublished) */
/* aa447644 CardRequestIRQLine: print `STATUS CardRequestIRQLine(CARD_CLIENT_HANDLEhCardClient,CARD_SOCKET_HANDLEhSocket, UINT16 uSupportedIrqBit, PDWORD pdwIrqOrSysIntrNumber, PDWORD pdwIsSysIntr);` -- recorded verbatim (no compiled prototype) */
/* aa447646 CardRequestWindow: print `CARD_WINDOW_HANDLE CardRequestWindow(CARD_CLIENT_HANDLE hCardClient,PCARD_WINDOW_PARMS pCardWinParms);` */
/* (record-only: parameter or return type unpublished) */
/* aa447647 CardResetFunction: print `STATUS CardResetFunction(CARD_CLIENT_HANDLE hCardClient,CARD_SOCKET_HANDLE hSock);` */
/* (record-only: parameter or return type unpublished) */
/* aa447648 CardSetEventMask: print `STATUS CardSetEventMask(CARD_CLIENT_HANDLE hCardClient,CARD_EVENT_MASK_PARMS pMaskParms);` */
/* (record-only: parameter or return type unpublished) */
/* aa447789 EnumCard: print `STATUS EnumCard(PDWORDpdwNumOfStructure,PCARD_DESCRIPTORpCardDescriptorArray,PDWORD pdwNumOfStructureCopied);` -- recorded verbatim (no compiled prototype) */
/* aa447793 EnumSocket: print `STATUS EnumSocket(PDWORDpdwNumOfStructure,PSOCKET_DESCRIPTORpSocketDescriptorArray,PDWORD pdwNumOfStructureCopied);` -- recorded verbatim (no compiled prototype) */
/* ms899315 GetSocketIndex: print `STATUS GetSocketIndex(CARD_SOCKET_HANDLEhCard,PDWORDpdwSocketIndex);` -- recorded verbatim (no compiled prototype) */
/* ms899316 GetSocketStatus: print `STATUS GetSocketStatus(DWORDdwSocketIndex,PDWORDpdwStatus);` */
/* (record-only: parameter or return type unpublished) */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448267 Bridge Base Class */
/* ms923713 Converting a Legacy PCMCIA Driver to a Bus-Agnostic Driver */
/* aa447530 Legacy PCMCIA Driver Registry Settings */
/* ms923736 PC Card Bus Driver */
/* ms919380 PC Card Driver Event Codes */
/* aa447531 PC Card Driver Samples */
/* aa448277 PC Card Socket Service Shared Code Library Registry Settings */
/* aa447529 PCMCIA Legacy Compatibility Layer Architecture */
/* aa447532 PCMCIA Legacy Compatibility Layer Event Codes */
/* aa447534 PCMCIA Legacy Compatibility Layer Tuple Codes */
/* aa447535 PCMCIA Legacy Compatibility Layer Window Attributes */
/* aa447536 PCMCIA Legacy Compatibility Layer Window Speeds */
/* aa448287 Socket Class */
/* aa448288 Static Window Classes */
/* aa448296 Window Classes */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896166 CardGetFirstTuple: print `` */
/* (record-only: parameter or return type unpublished) */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448267 Bridge Base Class */
/* ms923713 Converting a Legacy PCMCIA Driver to a Bus-Agnostic Driver */
/* aa447530 Legacy PCMCIA Driver Registry Settings */
/* ms923736 PC Card Bus Driver */
/* ms919380 PC Card Driver Event Codes */
/* aa447531 PC Card Driver Samples */
/* aa448277 PC Card Socket Service Shared Code Library Registry Settings */
/* aa447529 PCMCIA Legacy Compatibility Layer Architecture */
/* aa447532 PCMCIA Legacy Compatibility Layer Event Codes */
/* aa447534 PCMCIA Legacy Compatibility Layer Tuple Codes */
/* aa447535 PCMCIA Legacy Compatibility Layer Window Attributes */
/* aa447536 PCMCIA Legacy Compatibility Layer Window Speeds */
/* aa448287 Socket Class */
/* aa448288 Static Window Classes */
/* aa448296 Window Classes */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896174 CardModifyConfiguration: documented name-only (no value published; held) */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448267 Bridge Base Class */
/* ms923713 Converting a Legacy PCMCIA Driver to a Bus-Agnostic Driver */
/* aa447530 Legacy PCMCIA Driver Registry Settings */
/* ms923736 PC Card Bus Driver */
/* ms919380 PC Card Driver Event Codes */
/* aa447531 PC Card Driver Samples */
/* aa448277 PC Card Socket Service Shared Code Library Registry Settings */
/* aa447529 PCMCIA Legacy Compatibility Layer Architecture */
/* aa447532 PCMCIA Legacy Compatibility Layer Event Codes */
/* aa447534 PCMCIA Legacy Compatibility Layer Tuple Codes */
/* aa447535 PCMCIA Legacy Compatibility Layer Window Attributes */
/* aa447536 PCMCIA Legacy Compatibility Layer Window Speeds */
/* aa448287 Socket Class */
/* aa448288 Static Window Classes */
/* aa448296 Window Classes */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_CARDSV2_H */
