/*
 * Cdioctl.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-block.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CDIOCTL_H
#define AKARI_CDIOCTL_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447660 CD_SENSE_DATA -- HELD (page print; member types unpublished):
 *   typedef struct _CD_SENSE_DATA { ... } CD_SENSE_DATA, *PCD_SENSE_DATA; */
/* aa447655 CDROM_DISCINFO -- HELD (page print; member types unpublished):
 *   typedef struct CDROM_DISCINFO { ... } CDROM_DISCINFO, *PCDROM_DISCINFO; */
/* aa447656 CDROM_PLAY_AUDIO_MSF -- HELD (page print; member types unpublished):
 *   typedef struct _CDROM_PLAY_AUDIO_MSF { ... } CDROM_PLAY_AUDIO_MSF, *PCDROM_PLAY_AUDIO_MSF; */
/* aa447657 CDROM_READ -- HELD (page print; member types unpublished):
 *   typedef struct CDROM_READ { ... } CDROM_READ, *PCDROM_READ; */
/* aa447658 CDROM_TESTUNITREADY -- HELD (page print; member types unpublished):
 *   typedef struct CDROM_TESTUNITREADY { ... } CDROM_TESTUNITREADY, *PCDROM_TESTUNITREADY; */
/* aa447659 CDROM_TOC -- HELD (page print; member types unpublished):
 *   typedef struct _CDROM_TOC { ... } CDROM_TOC, *PCDROM_TOC; */
/* ms920831 SGX_BUF -- HELD (page print; member types unpublished):
 *   typedef struct _SGX_BUF { ... } SGX_BUF, *PSGX_BUF; */

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms892148 ATAPI Slave Devices */
/* ms890840 Block Driver Access */
/* ms890849 Block Driver Architecture */
/* ms890855 Block Driver Detection */
/* ms890864 Block Driver Installation */
/* ms890868 Block Driver Interface */
/* ms890874 Block Driver Loading */
/* ms890877 Block Driver Manager */
/* ms890882 Block Driver Power Cycle */
/* ms890889 Block Driver Registry Settings */
/* ms892152 File System Loading and Unloading */
/* aa447620 Sample ATADISK Driver */
/* aa447625 Sample Secure Digital Card Driver */

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms892148 ATAPI Slave Devices */
/* ms890840 Block Driver Access */
/* ms890849 Block Driver Architecture */
/* ms890855 Block Driver Detection */
/* ms890864 Block Driver Installation */
/* ms890868 Block Driver Interface */
/* ms890874 Block Driver Loading */
/* ms890877 Block Driver Manager */
/* ms890882 Block Driver Power Cycle */
/* ms890889 Block Driver Registry Settings */
/* ms892152 File System Loading and Unloading */
/* aa447620 Sample ATADISK Driver */
/* aa447625 Sample Secure Digital Card Driver */

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms901375 IOCTL_CDROM_DISC_INFO: documented name-only (no value published; held) */
/* ms901376 IOCTL_CDROM_EJECT_MEDIA: documented name-only (no value published; held) */
/* ms901377 IOCTL_CDROM_GET_SENSE_DATA: documented name-only (no value published; held) */
/* ms901378 IOCTL_CDROM_ISSUE_INQUIRY: documented name-only (no value published; held) */
/* ms901379 IOCTL_CDROM_PAUSE_AUDIO: documented name-only (no value published; held) */
/* ms901380 IOCTL_CDROM_PLAY_AUDIO_MSF: documented name-only (no value published; held) */
/* ms901381 IOCTL_CDROM_READ_SG: documented name-only (no value published; held) */
/* ms901382 IOCTL_CDROM_READ_TOC: documented name-only (no value published; held) */
/* ms901383 IOCTL_CDROM_RESUME_AUDIO: documented name-only (no value published; held) */
/* ms901384 IOCTL_CDROM_SEEK_AUDIO_MSF: documented name-only (no value published; held) */
/* ms901385 IOCTL_CDROM_STOP_AUDIO: documented name-only (no value published; held) */
/* ms901386 IOCTL_CDROM_TEST_UNIT_READY: documented name-only (no value published; held) */

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms892148 ATAPI Slave Devices */
/* ms890840 Block Driver Access */
/* ms890849 Block Driver Architecture */
/* ms890855 Block Driver Detection */
/* ms890864 Block Driver Installation */
/* ms890868 Block Driver Interface */
/* ms890874 Block Driver Loading */
/* ms890877 Block Driver Manager */
/* ms890882 Block Driver Power Cycle */
/* ms890889 Block Driver Registry Settings */
/* ms892152 File System Loading and Unloading */
/* aa447620 Sample ATADISK Driver */
/* aa447625 Sample Secure Digital Card Driver */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_CDIOCTL_H */
