/*
 * Ce_setup.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): activesync.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CE_SETUP_H
#define AKARI_CE_SETUP_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa514312 Install_Exit: print `codeINSTALL_EXIT Install_Exit(HWNDhwndParent,LPCTSTRpszInstallDir,WORDcFailedDirs,WORDcFailedFiles,WORDcFailedRegKeys,WORDcFailedRegVals,WORDcFailedShortcuts);` */
/* (record-only: parameter or return type unpublished) */
/* ms864467 Uninstall_Exit: print `codeUNINSTALL_EXIT Uninstall_Exit(HWNDhwndParent);` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_CE_SETUP_H */
