/*
 * Ceutil.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): activesync.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CEUTIL_H
#define AKARI_CEUTIL_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms861107 CeGetDeviceId: print `DEVICEID CeGetDeviceId();` */
/* (record-only: parameter or return type unpublished) */
/* aa513363 CeGetSelectedDeviceId: print `DEVICEID CeGetSelectedDeviceId();` */
/* (record-only: parameter or return type unpublished) */
/* aa513818 CeSvcAdd: print `HRESULT CeSvcAdd( LPTSTR pszSvcName,LPTSTR pszSvcClass,LPVOID pSvcInfo);` */
AKARI_CE_IMPORT HRESULT CeSvcAdd(LPTSTR pszSvcName, LPTSTR pszSvcClass, LPVOID pSvcInfo)
    AKARI_CE_NAME(CeSvcAdd);
/* aa513819 CeSvcClose: print `HRESULT CeSvcClose( HCESVC hSvc);` */
/* (record-only: parameter or return type unpublished) */
/* aa513820 CeSvcDelete: print `HRESULT CeSvcDelete( HCESVC hSvc);` */
/* (record-only: parameter or return type unpublished) */
/* aa513823 CeSvcDeleteVal: print `HRESULT CeSvcDeleteVal( HCESVC hSvc,LPCTSTR pszValName);` */
/* (record-only: parameter or return type unpublished) */
/* aa513824 CeSvcEnumProfiles: print `HRESULT CeSvcEnumProfiles( PHCESVC phSvc,DWORD lProfileIndex,PDWORD plProfile);` */
/* (record-only: parameter or return type unpublished) */
/* aa513826 CeSvcGetBinary: print `HRESULT CeSvcGetBinary( HCESVC hSvc,LPCTSTR pszValName,LPBYTE pszVal,LPDWORD pcbVal);` */
/* (record-only: parameter or return type unpublished) */
/* aa513828 CeSvcGetDword: print `HRESULT CeSvcGetDword( HCESVC hSvc,LPCTSTR pszValName,LPDWORD pdwVal);` */
/* (record-only: parameter or return type unpublished) */
/* aa513830 CeSvcGetString: print `HRESULT CeSvcGetString( HCESVC hSvc,LPCTSTR pszValName,LPTSTR pszVal,DWORD cbVal);` */
/* (record-only: parameter or return type unpublished) */
/* aa513833 CeSvcOpen: print `` -- recorded verbatim (no compiled prototype) */
/* aa513836 CeSvcOpenEx: print `HRESULT CeSvcOpenEx( HCESVC hSvcRoot,LPTSTR pszPath,BOOL fCreate,PHCESVC phSvc);` */
/* (record-only: parameter or return type unpublished) */
/* aa513837 CeSvcQueryInfo: print `HRESULT CeSvcQueryInfo( LPTSTR pszSvcName,LPTSTR pszSvcClass,LPVOID pszSvcInfo,DWORD cbBuffer);` */
AKARI_CE_IMPORT HRESULT CeSvcQueryInfo(LPTSTR pszSvcName, LPTSTR pszSvcClass, LPVOID pszSvcInfo, DWORD cbBuffer)
    AKARI_CE_NAME(CeSvcQueryInfo);
/* aa513840 CeSvcRemove: print `HRESULT CeSvcRemove( LPTSTR pszSvcName,LPTSTR pszSvcClass,DWORD dwSvcFlags);` */
AKARI_CE_IMPORT HRESULT CeSvcRemove(LPTSTR pszSvcName, LPTSTR pszSvcClass, DWORD dwSvcFlags)
    AKARI_CE_NAME(CeSvcRemove);
/* aa513842 CeSvcSetBinary: print `HRESULT CeSvcSetBinary( HCESVC hSvc,LPCTSTR pszValName,LPBYTE pszVal,DWORD cbVal);` */
/* (record-only: parameter or return type unpublished) */
/* aa513844 CeSvcSetDword: print `HRESULT CeSvcSetDword( HCESVC hSvc,LPCTSTR pszValName,DWORD dwVal);` */
/* (record-only: parameter or return type unpublished) */
/* aa513845 CeSvcSetString: print `HRESULT CeSvcSetString( HCESVC hSvc,LPCTSTR pszValName,LPCTSTR pszVal);` */
/* (record-only: parameter or return type unpublished) */
/* ms860950 CeSvcOpen Constant Enumeration (Header: Ceutil.h.) */

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms860950 CeSvcOpen Constant Enumeration (Header: Ceutil.h.) */

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa514415 ObjectNotify: documented name-only (no value published; held) */
/* ms860950 CeSvcOpen Constant Enumeration (Header: Ceutil.h.) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_CEUTIL_H */
