/*
 * Ctblt.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-display.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_CTBLT_H
#define AKARI_CTBLT_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms920529 SetClearTypeBltGamma: print `void SetClearTypeBltGamma(ULONGulGamma);` */
AKARI_CE_IMPORT void SetClearTypeBltGamma(ULONG ulGamma)
    AKARI_CE_NAME(SetClearTypeBltGamma);
/* ms920541 SetClearTypeBltMasks: print `void SetClearTypeBltMasks(ULONGfRedMask,ULONGfGreMask,ULONGfBluMask);` */
AKARI_CE_IMPORT void SetClearTypeBltMasks(ULONG fRedMask, ULONG fGreMask, ULONG fBluMask)
    AKARI_CE_NAME(SetClearTypeBltMasks);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_CTBLT_H */
