/*
 * D3dmddk.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-d3dmdisp.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_D3DMDDK_H
#define AKARI_D3DMDDK_H

#include <Windows.h>
#include "D3dm.h"      /* D3DMFORMAT and the D3DM value types the DDK
                        * structures reference */

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-d3dmdisp (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447711 D3DM_CLEAR (page print, compiled) */
typedef struct _D3DM_CLEAR {
    DWORD Flags;
    DWORD FillColor;
    float FillDepth;
    DWORD FillStencil;
    DWORD NumRects;
    RECT Rects[1];
} D3DM_CLEAR, * LPD3DM_CLEAR;
/* aa447712 D3DM_COLORFILL (page print, compiled) */
typedef struct _D3DM_COLORFILL {
    D3DMCOLOR Color;
    ULONG SurfaceId;
    RECT Rect;
} D3DM_COLORFILL, * LPD3DM_COLORFILL;
/* aa447713 D3DM_COMMAND (page print, compiled) */
typedef struct _D3DM_COMMAND {
    BYTE nCommand;
    BYTE nReserved;
    WORD nCount;
} D3DM_COMMAND, *LPD3DM_COMMAND;
/* aa447714 D3DM_COPYRECT (page print, compiled) */
typedef struct _D3DM_COPYRECT {
    ULONG SourceSurf;
    RECT SourceRect;
    ULONG DestSurf;
    POINT DestPoint;
} D3DM_COPYRECT, * LPD3DM_COPYRECT;
/* aa447715 D3DM_CREATECONTEXT_DATA (page print, compiled) */
typedef struct _D3DM_CREATECONTEXT_DATA {
    ULONG nContextId;
    HRESULT rval;
} D3DM_CREATECONTEXT_DATA;
/* aa447717 D3DM_CREATELIGHT (page print, compiled) */
typedef struct _D3DM_CREATELIGHT {
    DWORD Index;
} D3DM_CREATELIGHT, * LPD3DM_CREATELIGHT;
/* aa447718 D3DM_CREATEPALETTE (page print, compiled) */
typedef struct _D3DM_CREATEPALETTE {
    DWORD Index;
} D3DM_CREATEPALETTE, * LPD3DM_CREATEPALETTE;
/* aa447721 D3DM_DESTROYCONTEXT_DATA (page print, compiled) */
typedef struct _D3DM_DESTROYCONTEXT_DATA {
    ULONG nContextId;
    HRESULT rval;
} D3DM_DESTROYCONTEXT_DATA;
/* aa447723 D3DM_DESTROYSURFACE_DATA (page print, compiled) */
typedef struct _D3DM_DESTROYSURFACE_DATA {
    ULONG nSurfaceId;
    HRESULT rval;
} D3DM_DESTROYSURFACE_DATA;
/* aa447726 D3DM_DRAWINDEXEDPRIMITIVE (page print, compiled) */
typedef struct _D3DM_DRAWINDEXEDPRIMITIVE {
    D3DMPRIMITIVETYPE PrimType;
    DWORD MinIndex;
    DWORD NumVertices;
    DWORD StartIndexOffset;
    DWORD PrimitiveCount;
    INT BaseVertexIndex;
} D3DM_DRAWINDEXEDPRIMITIVE, * LPD3DM_DRAWINDEXEDPRIMITIVE;
/* aa447727 D3DM_DRAWPRIMITIVE (Structure) (page print, compiled) */
typedef struct _D3DM_DRAWPRIMITIVE {
    D3DMPRIMITIVETYPE PrimType;
    DWORD StartVertex;
    DWORD PrimitiveCount;
} D3DM_DRAWPRIMITIVE, * LPD3DM_DRAWPRIMITIVE;
/* aa447728 D3DM_DRAWPRIMITIVE_DATA (page print, compiled) */
typedef struct _D3DM_DRAWPRIMITIVE_DATA {
    ULONG nContextId;
    LPVOID pCommands;
    ULONG nStartOffset;
    ULONG nEndOffset;
    HRESULT rval;
} D3DM_DRAWPRIMITIVE_DATA;
/* ms896732 D3DM_GETINFO_DATA (page print, compiled) */
typedef struct _D3DM_GETINFO_DATA {
    ULONG nContextId;
    DWORD DevInfoId;
    void* pDevInfoStruct;
    DWORD DevInfoStructSize;
    HRESULT rval;
} D3DM_GETINFO_DATA;
/* ms896734 D3DM_INDEXBUFFER (page print, compiled) */
typedef struct _D3DM_INDEXBUFFER {
    ULONG BufferId;
    DWORD Stride;
} D3DM_INDEXBUFFER, * LPD3DM_INDEXBUFFER;
/* ms896737 D3DM_LOCKSURFACE_DATA (page print, compiled) */
typedef struct _D3DM_LOCKSURFACE_DATA {
    RECT Rect;
    D3DMLOCKED_RECT LockedRect;
    ULONG nSurfaceId;
    ULONG Flags;
    HRESULT rval;
} D3DM_LOCKSURFACE_DATA;
/* ms896739 D3DM_MATERIAL (page print, compiled) */
typedef struct _D3DM_MATERIAL {
    D3DMMATERIAL Material;
    D3DMFORMAT Format;
} D3DM_MATERIAL, * LPD3DM_MATERIAL;
/* ms896740 D3DM_OPERATION (page print, compiled) */
typedef enum _D3DM_OPERATION {
    D3DMOP_BEGINSCENE,
    D3DMOP_ENDSCENE,
    D3DMOP_PRESENT,
    D3DMOP_COPYRECT,
    D3DMOP_CLEAR,
    D3DMOP_RENDERTARGET,
    D3DMOP_RENDERSTATE,
    D3DMOP_TRANSFORM,
    D3DMOP_VIEWPORT,
    D3DMOP_MATERIAL,
    D3DMOP_CREATELIGHT,
    D3DMOP_SETLIGHT,
    D3DMOP_TEXTURESTAGESTATE,
    D3DMOP_CREATEPALETTE,
    D3DMOP_SETPALETTE,
    D3DMOP_PROCESSVERTICES,
    D3DMOP_DRAWPRIMITIVE,
    D3DMOP_DRAWINDEXEDPRIMITIVE,
    D3DMOP_VERTEXBUFFER,
    D3DMOP_INDEXBUFFER,
    D3DMOP_COLORFILL,
    D3DMOP_STRETCHRECT
} D3DM_OPERATION;
/* ms896741 D3DM_PRESENT (page print, compiled) */
typedef struct _D3DM_PRESENT {
    ULONG PresentSurface;
    RECT SourceRect;
    RECT DestinationRect;
    DWORD NumClippingRects;
    RECT ClippingRects[1];
} D3DM_PRESENT, * LPD3DM_PRESENT;
/* ms896742 D3DM_PROCESSVERTICES (page print, compiled) */
typedef struct _D3DM_PROCESSVERTICES {
    DWORD SrcStartIndex;
    DWORD DestIndex;
    DWORD VertexCount;
    ULONG DestBufferId;
    DWORD Flags;
} D3DM_PROCESSVERTICES, * LPD3DM_PROCESSVERTICES;
/* ms896743 D3DM_RENDERSTATE (page print, compiled) */
typedef struct _D3DM_RENDERSTATE {
    D3DMRENDERSTATETYPE RenderState;
    D3DMVALUE Value;
} D3DM_RENDERSTATE, *LPD3DM_RENDERSTATE;
/* ms896744 D3DM_RENDERTARGET (page print, compiled) */
typedef struct _D3DM_RENDERTARGET {
    ULONG RenderTarget;
    ULONG ZBuffer;
} D3DM_RENDERTARGET, * LPD3DM_RENDERTARGET;
/* ms896749 D3DM_SETLIGHT_DATATYPE (page print, compiled) */
typedef enum _D3DM_SETLIGHT_DATATYPE {
    D3DM_SETLIGHT_ENABLE = 0,
    D3DM_SETLIGHT_DISABLE = 1,
    D3DM_SETLIGHT_DATA_ENABLE = 2,
    D3DM_SETLIGHT_DATA_DISABLE = 3
} D3DM_SETLIGHT_DATATYPE;
/* ms896750 D3DM_SETLIGHT_WITHDATA (page print, compiled) */
typedef struct _D3DM_SETLIGHT_WITHDATA {
    DWORD Index;
    D3DM_SETLIGHT_DATATYPE DataType;
    D3DMLIGHT Data;
    D3DMFORMAT Format;
} D3DM_SETLIGHT_WITHDATA, * LPD3DM_SETLIGHT_WITHDATA;
/* ms896752 D3DM_SETPALETTE_DATATYPE (page print, compiled) */
typedef enum _D3DM_SETPALETTE_DATATYPE {
    D3DM_SETPALETTE_SETACTIVE = 0,
    D3DM_SETPALETTE_SETENTRIES = 1
} D3DM_SETPALETTE_DATATYPE;
/* ms896753 D3DM_SETPALETTE_WITHENTRIES (page print, compiled) */
typedef struct _D3DM_SETPALETTE_WITHENTRIES {
    DWORD Index;
    D3DM_SETPALETTE_DATATYPE DataType;
    PALETTEENTRY Entries[256];
} D3DM_SETPALETTE_WITHENTRIES, *LPD3DM_SETPALETTE_WITHENTRIES;
/* ms896754 D3DM_STRETCHRECT (page print, compiled) */
typedef struct _D3DM_STRETCHRECT {
    ULONG SourceId;
    RECT SourceRect;
    ULONG DestId;
    RECT DestRect;
    D3DMTEXTUREFILTERTYPE Filter;
} D3DM_STRETCHRECT, * LPD3DM_STRETCHRECT;
/* ms896755 D3DM_TEXTURESTAGESTATE (page print, compiled) */
typedef struct _D3DM_TEXTURESTAGESTATE {
    WORD Stage;
    WORD State;
    DWORD Value;
} D3DM_TEXTURESTAGESTATE, * LPD3DM_TEXTURESTAGESTATE;
/* ms896756 D3DM_TRANSFORM (page print, compiled) */
typedef struct _D3DM_TRANSFORM {
    D3DMTRANSFORMSTATETYPE TransformType;
    D3DMMATRIX Matrix;
    D3DMFORMAT Format;
} D3DM_TRANSFORM, * LPD3DM_TRANSFORM;
/* ms896757 D3DM_UNLOCKSURFACE_DATA (page print, compiled) */
typedef struct _D3DM_UNLOCKSURFACE_DATA {
    ULONG nSurfaceId;
    HRESULT rval;
} D3DM_UNLOCKSURFACE_DATA;
/* ms896759 D3DM_VALIDATEDEVICE_DATA (page print, compiled) */
typedef struct _D3DM_VALIDATEDEVICE_DATA {
    ULONG nContextId;
    DWORD NumPasses;
    HRESULT rval;
} D3DM_VALIDATEDEVICE_DATA;
/* ms896761 D3DM_VERTEXBUFFER (page print, compiled) */
typedef struct _D3DM_VERTEXBUFFER {
    DWORD StreamIndex;
    ULONG BufferId;
    DWORD Stride;
} D3DM_VERTEXBUFFER, * LPD3DM_VERTEXBUFFER;
/* ms896762 D3DM_VIEWPORT (page print, compiled) */
typedef struct _D3DM_VIEWPORT {
    D3DMVIEWPORT Viewport;
} D3DM_VIEWPORT, * LPD3DM_VIEWPORT;
/* aa447707 D3DMTEXTURE_DESC (page print, compiled) */
typedef struct _D3DMTEXTURE_DESC {
    D3DMFORMAT Format;
    D3DMRESOURCETYPE Type;
    ULONG Usage;
    D3DMPOOL Pool;
    UINT Size;
    D3DMMULTISAMPLE_TYPE MultiSampleType;
    UINT Width;
    UINT Height;
    ULONG Level;
    ULONG TotalLevels;
} D3DMTEXTURE_DESC;
/* aa447719 D3DM_CREATESURFACE_DATA -- HELD (page print; member types unpublished):
 *   typedef struct _D3DM_CREATESURFACE_DATA { ... } D3DM_CREATESURFACE_DATA; */
/* ms896729 D3DM_GETADAPTERINFO_DATA -- HELD (page print; member types unpublished):
 *   typedef struct _D3DM_GETADAPTERINFO_DATA { ... } D3DM_GETADAPTERINFO_DATA; */
/* ms896735 D3DM_INITIALIZE_DATA -- HELD (page print; member types unpublished):
 *   typedef struct _D3DM_INITIALIZE_DATA { ... } D3DM_INITIALIZE_DATA; */
/* ms896745 D3DM_RESOURCEMANAGER_ACTION -- HELD (page print; member types unpublished):
 *   typedef enum _D3DM_RESOURCEMANAGER_ACTION { ... } D3DM_RESOURCEMANAGER_ACTION; */
/* ms896746 D3DM_RESOURCEMANAGER_DATA -- HELD (page print; member types unpublished):
 *   typedef struct _D3DM_RESOURCEMANAGER_DATA { ... } D3DM_RESOURCEMANAGER_DATA; */
/* ms896748 D3DM_SETLIGHT -- HELD (page print; member types unpublished):
 *   typedef struct _D3DM_SETLIGHT { ... } D3DM_SETLIGHT, * LPD3DM_SETLIGHT; */
/* ms896751 D3DM_SETPALETTE -- HELD (page print; member types unpublished):
 *   typedef struct _D3DM_SETPALETTE { ... } D3DM_SETPALETTE, *LPD3DM_SETPALETTE; */
/* aa447699 D3DMDEVICEFORMAT -- HELD (page print; member types unpublished):
 *   typedef struct _D3DMDEVICEFORMAT { ... } D3DMDEVICEFORMAT; */
/* ms896720 D3DM_DRIVER Values (Header: D3dmddk.h.) */
/* ms896731 D3DM_GETINFO Values (Header: D3dmddk.h.) */
/* aa447706 D3DMRTYPEFLAG Values (Header: D3dmddk.h.) */

/* ------------------------------------------------------------------
 * Book surface: drivers-d3dmdisp (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890522 Additional Information from the Direct3D Mobile Driver */
/* ms890710 Back Buffers and Image Surfaces */
/* ms891126 Clipping in Direct3D Mobile Drivers */
/* ms891181 Command Buffer Structure */
/* aa447458 Depth and Stencil Buffers */
/* aa447478 Direct3D Mobile Driver Registry Settings */
/* aa447479 Direct3D Mobile Reference Driver */
/* aa447517 Driver Initialization in Direct3D Mobile */
/* ms892156 Front Buffers */
/* ms892244 Internal Direct3D Mobile Driver Errors */
/* ms892488 Local Hooking */
/* ms892504 Multisampling in the Driver */
/* ms892551 Number Format Conversions */
/* aa447592 Remote Hooking */
/* aa447595 Rendering Contexts in Direct3D Mobile */
/* aa447598 Resource Management by Direct3D Mobile Drivers */
/* ms894049 Surface Locks in Direct3D Mobile */
/* ms894061 Texture Maps */
/* ms894734 Vertex and Index Buffers */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_D3DMDDK_H */
