/*
 * Ddkreg.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): driver-libs-remainder.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DDKREG_H
#define AKARI_DDKREG_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: driver-libs-remainder (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms898293 DEVICEWINDOW (page print, compiled) */
typedef struct _DEVICEWINDOW_tag {
    DWORD dwBase;
    DWORD dwLen;
} DEVICEWINDOW, *PDEVICEWINDOW;
/* ms897694 DDKISRINFO -- HELD (page print; member types unpublished):
 *   typedef struct _DDKISRINFO_tag { ... } DDKISRINFO, *PDDKISRINFO; */
/* ms897695 DDKPCIINFO -- HELD (page print; member types unpublished):
 *   typedef struct _DDKPCIINFO_tag { ... } DDKPCIINFO, *PDDKPCIINFO; */
/* ms897713 DDKWINDOWINFO -- HELD (page print; member types unpublished):
 *   typedef struct _DDKWINDOWINFO_tag { ... } DDKWINDOWINFO, *PDDKWINDOWINFO; */
/* ms897699 DDKReg_GetIsrInfo: print `DWORD WINAPI DDKReg_GetIsrInfo(HKEY hk, PDDKISRINFO pii);` */
/* (record-only: parameter or return type unpublished) */
/* ms897705 DDKReg_GetPciInfo: print `DWORD WINAPI DDKReg_GetPciInfo(HKEY hk, PDDKPCIINFO ppi);` */
/* (record-only: parameter or return type unpublished) */
/* ms897707 DDKReg_GetWindowInfo: print `DWORD WINAPI DDKReg_GetWindowInfo(HKEY hk, PDDKWINDOWINFO pwi);` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DDKREG_H */
