/*
 * Ddrawip.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-ddrawdisp.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DDRAWIP_H
#define AKARI_DDRAWIP_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-ddrawdisp (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899354 HalColorControl (video port control callback): print `` -- recorded verbatim (no compiled prototype) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DDRAWIP_H */
