/*
 * Ddrawi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-ddrawdisp.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DDRAWI_H
#define AKARI_DDRAWI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-ddrawdisp (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896110 ATTACHLIST -- HELD (page print; member types unpublished):
 *   typedef struct _ATTACHLIST { ... } ATTACHLIST; */
/* ms896764 DBLNODE -- HELD (page print; member types unpublished):
 *   typedef struct _DBLNODE { ... } DBLNODE; */
/* ms896816 DDHAL_ADDATTACHEDSURFACEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_ADDATTACHEDSURFACEDATA { ... } DDHAL_ADDATTACHEDSURFACEDATA; */
/* ms896817 DDHAL_BLTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_BLTDATA { ... } DDHAL_BLTDATA; */
/* ms896818 DDHAL_CANCREATESURFACEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_CANCREATESURFACEDATA { ... } DDHAL_CANCREATESURFACEDATA; */
/* ms896819 DDHAL_CANCREATEVPORTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_CANCREATEVPORTDATA { ... } DDHAL_CANCREATEVPORTDATA; */
/* ms896820 DDHAL_COLORCONTROLDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_COLORCONTROLDATA { ... } DDHAL_COLORCONTROLDATA; */
/* ms896821 DDHAL_CREATEPALETTEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_CREATEPALETTEDATA { ... } DDHAL_CREATEPALETTEDATA; */
/* ms896822 DDHAL_CREATESURFACEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_CREATESURFACEDATA { ... } DDHAL_CREATESURFACEDATA; */
/* ms896823 DDHAL_CREATEVPORTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_CREATEVPORTDATA { ... } DDHAL_CREATEVPORTDATA; */
/* ms896824 DDHAL_DDCALLBACKS -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DDCALLBACKS { ... } DDHAL_DDCALLBACKS; */
/* ms896825 DDHAL_DDCOLORCONTROLCALLBACKS -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DDCOLORCONTROLCALLBACKS { ... } DDHAL_DDCOLORCONTROLCALLBACKS; */
/* ms896826 DDHAL_DDMISCELLANEOUS2CALLBACKS -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DDMISCELLANEOUS2CALLBACKS { ... } DDHAL_DDMISCELLANEOUS2CALLBACKS, *LPDDHAL_DDMISCELLANEOUS2CALLBACKS; */
/* ms896827 DDHAL_DDMISCELLANEOUSCALLBACKS -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DDMISCELLANEOUSCALLBACKS { ... } DDHAL_DDMISCELLANEOUSCALLBACKS, *LPDDHAL_DDMISCELLANEOUSCALLBACKS; */
/* ms896828 DDHAL_DDPALETTECALLBACKS -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DDPALETTECALLBACKS { ... } DDHAL_DDPALETTECALLBACKS; */
/* ms896829 DDHAL_DDSURFACECALLBACKS -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DDSURFACECALLBACKS { ... } DDHAL_DDSURFACECALLBACKS; */
/* ms897064 DDHAL_DDVIDEOPORTCALLBACKS -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DDVIDEOPORTCALLBACKS { ... } DDHAL_DDVIDEOPORTCALLBACKS; */
/* ms897235 DDHAL_DESTROYDRIVERDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DESTROYDRIVERDATA { ... } DDHAL_DESTROYDRIVERDATA; */
/* ms897243 DDHAL_DESTROYPALETTEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DESTROYPALETTEDATA { ... } DDHAL_DESTROYPALETTEDATA; */
/* ms897355 DDHAL_DESTROYSURFACEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DESTROYSURFACEDATA { ... } DDHAL_DESTROYSURFACEDATA; */
/* ms897410 DDHAL_DESTROYVPORTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_DESTROYVPORTDATA { ... } DDHAL_DESTROYVPORTDATA; */
/* ms897514 DDHAL_FLIPDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_FLIPDATA { ... } DDHAL_FLIPDATA; */
/* ms897527 DDHAL_FLIPTOGDISURFACEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_FLIPTOGDISURFACEDATA { ... } DDHAL_FLIPTOGDISURFACEDATA; */
/* ms897534 DDHAL_FLIPVPORTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_FLIPVPORTDATA { ... } DDHAL_FLIPVPORTDATA; */
/* ms897538 DDHAL_GETAVAILDRIVERMEMORYDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETAVAILDRIVERMEMORYDATA { ... } DDHAL_GETAVAILDRIVERMEMORYDATA; */
/* ms897546 DDHAL_GETBLTSTATUSDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETBLTSTATUSDATA { ... } DDHAL_GETBLTSTATUSDATA; */
/* ms897547 DDHAL_GETDRIVERINFODATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETDRIVERINFODATA { ... } DDHAL_GETDRIVERINFODATA; */
/* ms897553 DDHAL_GETFLIPSTATUSDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETFLIPSTATUSDATA { ... } DDHAL_GETFLIPSTATUSDATA; */
/* ms897557 DDHAL_GETHEAPALIGNMENTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETHEAPALIGNMENTDATA { ... } DDHAL_GETHEAPALIGNMENTDATA; */
/* ms897563 DDHAL_GETSCANLINEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETSCANLINEDATA { ... } DDHAL_GETSCANLINEDATA; */
/* ms897569 DDHAL_GETVPORTBANDWIDTHDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETVPORTBANDWIDTHDATA { ... } DDHAL_GETVPORTBANDWIDTHDATA; */
/* ms897575 DDHAL_GETVPORTCONNECTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETVPORTCONNECTDATA { ... } DDHAL_GETVPORTCONNECTDATA; */
/* ms897577 DDHAL_GETVPORTFIELDDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETVPORTFIELDDATA { ... } DDHAL_GETVPORTFIELDDATA; */
/* ms897584 DDHAL_GETVPORTFLIPSTATUSDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETVPORTFLIPSTATUSDATA { ... } DDHAL_GETVPORTFLIPSTATUSDATA; */
/* ms897587 DDHAL_GETVPORTINPUTFORMATDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETVPORTINPUTFORMATDATA { ... } DDHAL_GETVPORTINPUTFORMATDATA; */
/* ms897590 DDHAL_GETVPORTLINEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETVPORTLINEDATA { ... } DDHAL_GETVPORTLINEDATA; */
/* ms897595 DDHAL_GETVPORTOUTPUTFORMATDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETVPORTOUTPUTFORMATDATA { ... } DDHAL_GETVPORTOUTPUTFORMATDATA; */
/* ms897598 DDHAL_GETVPORTSIGNALDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_GETVPORTSIGNALDATA { ... } DDHAL_GETVPORTSIGNALDATA; */
/* ms897608 DDHAL_LOCKDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_LOCKDATA { ... } DDHAL_LOCKDATA; */
/* ms897624 DDHAL_SETCLIPLISTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_SETCLIPLISTDATA { ... } DDHAL_SETCLIPLISTDATA; */
/* ms897627 DDHAL_SETCOLORKEYDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_SETCOLORKEYDATA { ... } DDHAL_SETCOLORKEYDATA; */
/* ms897633 DDHAL_SETENTRIESDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_SETENTRIESDATA { ... } DDHAL_SETENTRIESDATA; */
/* ms897640 DDHAL_SETEXCLUSIVEMODEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_SETEXCLUSIVEMODEDATA { ... } DDHAL_SETEXCLUSIVEMODEDATA; */
/* ms897647 DDHAL_SETMODEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_SETMODEDATA { ... } DDHAL_SETMODEDATA; */
/* ms897652 DDHAL_SETOVERLAYPOSITIONDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_SETOVERLAYPOSITIONDATA { ... } DDHAL_SETOVERLAYPOSITIONDATA; */
/* ms897656 DDHAL_SETPALETTEDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_SETPALETTEDATA { ... } DDHAL_SETPALETTEDATA; */
/* ms897662 DDHAL_UNLOCKDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_UNLOCKDATA { ... } DDHAL_UNLOCKDATA; */
/* ms897669 DDHAL_UPDATENONLOCALHEAPDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_UPDATENONLOCALHEAPDATA { ... } DDHAL_UPDATENONLOCALHEAPDATA; */
/* ms897671 DDHAL_UPDATEOVERLAYDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_UPDATEOVERLAYDATA { ... } DDHAL_UPDATEOVERLAYDATA; */
/* ms897678 DDHAL_UPDATEVPORTDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_UPDATEVPORTDATA { ... } DDHAL_UPDATEVPORTDATA; */
/* ms897680 DDHAL_VPORTCOLORDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_VPORTCOLORDATA { ... } DDHAL_VPORTCOLORDATA; */
/* ms897686 DDHAL_WAITFORVERTICALBLANKDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_WAITFORVERTICALBLANKDATA { ... } DDHAL_WAITFORVERTICALBLANKDATA; */
/* ms897689 DDHAL_WAITFORVPORTSYNCDATA -- HELD (page print; member types unpublished):
 *   typedef struct _DDHAL_WAITFORVPORTSYNCDATA { ... } DDHAL_WAITFORVPORTSYNCDATA; */
/* ms897605 DDHALINFO -- HELD (page print; member types unpublished):
 *   typedef struct _DDHALINFO { ... } DDHALINFO; */
/* ms897612 DDHALMODEINFO -- HELD (page print; member types unpublished):
 *   typedef struct _DDHALMODEINFO { ... } DDHALMODEINFO; */
/* ms897932 DDMORECAPS -- HELD (page print; member types unpublished):
 *   typedef struct _DDMORECAPS { ... } DDMORECAPS, FAR *LPDDMORECAPS; */
/* ms897948 DDMORESURFACECAPS -- HELD (page print; member types unpublished):
 *   typedef struct _DDMORESURFACECAPS { ... } DDMORESURFACECAPS, FAR* LPDDMORESURFACECAPS; */
/* ms898018 DDNONLOCALVIDMEMCAPS -- HELD (page print; member types unpublished):
 *   typedef struct _DDNONLOCALVIDMEMCAPS { ... } DDNONLOCALVIDMEMCAPS; */
/* ms898127 DDRAWI_DDRAWCLIPPER_GBL -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWCLIPPER_GBL { ... } DDRAWI_DDRAWCLIPPER_GBL; */
/* ms898239 DDRAWI_DDRAWCLIPPER_INT -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWCLIPPER_INT { ... } DDRAWI_DDRAWCLIPPER_INT; */
/* ms898249 DDRAWI_DDRAWCLIPPER_LCL -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWCLIPPER_LCL { ... } DDRAWI_DDRAWCLIPPER_LCL; */
/* ms898255 DDRAWI_DDRAWPALETTE_GBL -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWPALETTE_GBL { ... } DDRAWI_DDRAWPALETTE_GBL; */
/* ms898256 DDRAWI_DDRAWPALETTE_INT -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWPALETTE_INT { ... } DDRAWI_DDRAWPALETTE_INT; */
/* ms898257 DDRAWI_DDRAWPALETTE_LCL -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWPALETTE_LCL { ... } DDRAWI_DDRAWPALETTE_LCL; */
/* ms898258 DDRAWI_DDRAWSURFACE_GBL -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWSURFACE_GBL { ... } DDRAWI_DDRAWSURFACE_GBL; */
/* ms898260 DDRAWI_DDRAWSURFACE_GBL_MORE -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWSURFACE_GBL_MORE { ... } DDRAWI_DDRAWSURFACE_GBL_MORE; */
/* ms898261 DDRAWI_DDRAWSURFACE_INT -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWSURFACE_INT { ... } DDRAWI_DDRAWSURFACE_INT; */
/* ms898263 DDRAWI_DDRAWSURFACE_MORE -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDRAWSURFACE_MORE { ... } DDRAWI_DDRAWSURFACE_MORE; */
/* ms898264 DDRAWI_DDVIDEOPORT_INT -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDVIDEOPORT_INT { ... } DDRAWI_DDVIDEOPORT_INT; */
/* ms898265 DDRAWI_DDVIDEOPORT_LCL -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DDVIDEOPORT_LCL { ... } DDRAWI_DDVIDEOPORT_LCL; */
/* ms898266 DDRAWI_DIRECTDRAW_GBL -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DIRECTDRAW_GBL { ... } DDRAWI_DIRECTDRAW_GBL; */
/* ms898267 DDRAWI_DIRECTDRAW_INT -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DIRECTDRAW_INT { ... } DDRAWI_DIRECTDRAW_INT; */
/* ms898268 DDRAWI_DIRECTDRAW_LCL -- HELD (page print; member types unpublished):
 *   typedef struct _DDRAWI_DIRECTDRAW_LCL { ... } DDRAWI_DIRECTDRAW_LCL; */
/* ms923268 VIDMEM -- HELD (page print; member types unpublished):
 *   typedef struct _VIDMEM { ... } VIDMEM; */
/* ms923269 VIDMEMINFO -- HELD (page print; member types unpublished):
 *   typedef struct _VIDMEMINFO { ... } VIDMEMINFO; */
/* ms896156 CanCreateVideoPort: print `DWORD CanCreateVideoPort(LPDDHAL_CANCREATEVPORTDATApccvpd);` -- recorded verbatim (no compiled prototype) */
/* ms898283 DestroyPalette: print `DWORD DestroyPalette(LPDDHAL_DESTROYPALETTEDATApdpd);` -- recorded verbatim (no compiled prototype) */
/* ms898284 DestroySurface: print `DWORD DestroySurface(LPDDHAL_DESTROYSURFACEDATApdsd);` -- recorded verbatim (no compiled prototype) */
/* ms898285 DestroyVideoPort: print `DWORD DestroyVideoPort(LPDDHAL_DESTROYVPORTDATApdvpd);` -- recorded verbatim (no compiled prototype) */
/* aa447808 FlipVideoPort: print `DWORD FlipVideoPort(LPDDHAL_FLIPVPORTDATApfvpd);` -- recorded verbatim (no compiled prototype) */
/* ms899308 GET_LPDDRAWSURFACE_GBL_MORE: print `GET_LPDDRAWSURFACE_GBL_MORE(psurf_gbl) \(*(LPDDRAWI_DDRAWSURFACE_GBL_MORE *) \((BYTE *)psurf_gbl- sizeof( DWORD )))` */
/* (record-only: parameter or return type unpublished) */
/* aa447822 GetAvailDriverMemory: print `DWORD GetAvailDriverMemory(LPDDHAL_GETAVAILDRIVERMEMORYDATApgadmd);` -- recorded verbatim (no compiled prototype) */
/* aa447833 GetDriverInfo: print `DWORD GetDriverInfo(LPDDHAL_GETDRIVERINFODATAlpData);` -- recorded verbatim (no compiled prototype) */
/* aa447839 GetHeapAlignment: print `DWORD GetHeapAlignment(LPDDHAL_GETHEAPALIGNMENTDATAlpGhaData);` -- recorded verbatim (no compiled prototype) */
/* ms899318 GetSysmemBltStatus: print `DWORD GetSysmemBltStatus(LPDDHAL_GETBLTSTATUSDATApgbsd);` -- recorded verbatim (no compiled prototype) */
/* ms899323 GetVideoPortBandwidth: print `DWORD GetVideoPortBandwidth(LPDDHAL_GETVPORTBANDWIDTHDATApgvpbd);` -- recorded verbatim (no compiled prototype) */
/* ms899325 GetVideoPortField: print `DWORD GetVideoPortField(LPDDHAL_GETVPORTFIELDDATApgvpfd);` -- recorded verbatim (no compiled prototype) */
/* ms899326 GetVideoPortFlipStatus: print `DWORD GetVideoPortFlipStatus(LPDDHAL_GETVPORTFLIPSTATUSDATApgvpfsd);` -- recorded verbatim (no compiled prototype) */
/* ms899327 GetVideoPortInputFormats: print `DWORD GetVideoPortInputFormats(LPDDHAL_GETVPORTINPUTFORMATDATApgvpifd);` -- recorded verbatim (no compiled prototype) */
/* ms899328 GetVideoPortLine: print `DWORD GetVideoPortLine(LPDDHAL_GETVPORTLINEDATApgvpld);` -- recorded verbatim (no compiled prototype) */
/* ms899329 GetVideoPortOutputFormats: print `DWORD GetVideoPortOutputFormats(LPDDHAL_GETVPORTOUTPUTFORMATDATApgvpofd);` -- recorded verbatim (no compiled prototype) */
/* ms899353 HalColorControl (color control callback): print `` -- recorded verbatim (no compiled prototype) */
/* aa448183 SURFACE_PHYSICALVIDMEM: print `SURFACE_PHYSICALVIDMEM(psurf_gbl) \( GET_LPDDRAWSURFACE_GBL_MORE(psurf_gbl)->fpPhysicalVidMem )` */
/* (record-only: parameter or return type unpublished) */
/* ms923156 UpdateNonLocalHeap: print `DWORD UpdateNonLocalHeap(LPDDHAL_UPDATENONLOCALHEAPDATAlpd);` -- recorded verbatim (no compiled prototype) */
/* ms923171 UpdateVideoPort: print `DWORD UpdateVideoPort(LPDDHAL_UPDATEVPORTDATApuvpd);` -- recorded verbatim (no compiled prototype) */
/* ms923280 WaitForVideoPortSync: print `DWORD WaitForVideoPortSync(LPDDHAL_WAITFORVPORTSYNCDATApwfvpsd);` -- recorded verbatim (no compiled prototype) */

/* ------------------------------------------------------------------
 * Book surface: drivers-ddrawdisp (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896774 DDGPE Class Definition */
/* aa447442 DDGPE Derivation */
/* ms896793 DDGPESurf Class Definition */
/* aa447445 DDGPESurf Derivation */
/* aa447447 DDHAL Callback Return Values */
/* aa447448 DDHAL Callbacks and Capabilities */
/* aa447450 DDHAL Customization */
/* aa447484 Developing a Display Driver that is Prepared for DirectDraw Support */
/* aa447477 Differences from Desktop Implementations */
/* ms890597 DirectDraw Display Driver Architecture */
/* aa447489 DirectDraw Driver Samples */
/* aa447797 Exported DDHAL Functions */
/* aa447498 Extending a Display Driver with the DDGPE Classes */
/* aa447451 Implementing DDHAL Functionality */
/* aa447452 Implementing DDHAL Functionality without GPE */
/* ms892231 Implementing Overlay Flipping in a DirectDraw Driver */
/* aa447454 Porting DDHAL from the Desktop */
/* aa447502 Preparing a Display Driver */
/* aa448178 SurfaceHeap Class Definition */
/* ms894730 Use of SurfaceHeap */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DDRAWI_H */
