/*
 * Ddvdata.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): graphics-book.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DDVDATA_H
#define AKARI_DDVDATA_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: graphics-book (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa451617 DVD-Video API Structures/DVD_AUDIO_MU_ATTR (Header: Ddvdata.h, Dvdata.idl.) */

/* ------------------------------------------------------------------
 * Book surface: graphics-book (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa451617 DVD-Video API Structures/DVD_AUDIO_MU_ATTR (Header: Ddvdata.h, Dvdata.idl.) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DDVDATA_H */
