/*
 * Developer-defined.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): servers.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DEVELOPER-DEFINED_H
#define AKARI_DEVELOPER-DEFINED_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: servers (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms898932 xxx_Close (Services.exe): print `` */
BOOL xxx_Close(DWORD dwData);
/* ms898933 xxx_Deinit (Services.exe): print `` */
BOOL xxx_Deinit(DWORD dwData);
/* ms898934 xxx_Init (Services.exe): print `` */
DWORD xxx_Init(DWORD dwData);
/* ms898935 xxx_IOControl (Services.exe): print `` */
BOOL xxx_IOControl(DWORD dwData, DWORD dwCode, PBYTE pBufIn, DWORD dwLenIn, PBYTE pBufOut, DWORD dwLenOut, PDWORD pdwActualOut);
/* ms898936 xxx_Open (Services.exe): print `` */
BOOL xxx_Open(DWORD dwData, DWORD dwAccess, DWORD dwShareMode);
/* ms898937 xxx_Read (Services.exe): print `` */
DWORD xxx_Read(DWORD dwData, LPVOID pBuf, DWORD dwLen);
/* ms898938 xxx_Seek (Services.exe): print `` */
DWORD xxx_Seek(DWORD dwData, long pos, DWORD type);
/* ms898939 xxx_Write (Services.exe): print `` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DEVELOPER-DEFINED_H */
