/*
 * Devload.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): devmgr.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DEVLOAD_H
#define AKARI_DEVLOAD_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: devmgr (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919788 REGINI (page print, compiled) */
typedef struct _REGINI {
    LPCWSTR lpszVal;
    LPBYTE pData;
    DWORD dwLen;
    DWORD dwType;
} REGINI;
/* aa447792 EnumPnpIds: print `DWORD EnumPnpIds(LPTSTRlpszPnpList,LPDWORDlpBuflen);` */
AKARI_CE_IMPORT DWORD EnumPnpIds(LPTSTR lpszPnpList, LPDWORD lpBuflen)
    AKARI_CE_NAME(EnumPnpIds);
/* ms919310 OpenDeviceKey: print `HKEY OpenDeviceKey( LPCTSTR ActiveKey);` */
AKARI_CE_IMPORT HKEY OpenDeviceKey(LPCTSTR ActiveKey)
    AKARI_CE_NAME(OpenDeviceKey);

/* ------------------------------------------------------------------
 * Book surface: devmgr (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: devmgr (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms898304 DMAdvertiseInterface: documented name-only (no value published; held) */
/* ms919663 POST_INIT_BUF: documented name-only (no value published; held) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DEVLOAD_H */
