/*
 * Diskio.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-flash.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DISKIO_H
#define AKARI_DISKIO_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-flash (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms898280 DELETE_SECTOR_INFO -- HELD (page print; member types unpublished):
 *   typedef struct _DELETE_SECTOR_INFO { ... } DELETE_SECTOR_INFO, *PDELETE_SECTOR_INFO; */

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms898299 DISK_INFO (page print, compiled) */
typedef struct _DISK_INFO {
    DWORD di_total_sectors;
    DWORD di_bytes_per_sect;
    DWORD di_cylinders;
    DWORD di_heads;
    DWORD di_sectors;
    DWORD di_flags;
} DISK_INFO, *PDISK_INFO;
/* ms920807 SG_BUF (page print, compiled) */
typedef struct _SG_BUF {
    PUCHAR sb_buf;
    DWORD sb_len;
} SG_BUF, *PSG_BUF;
/* aa448149 STORAGE_IDENTIFICATION (page print, compiled) */
typedef struct _STORAGE_IDENTIFICATION {
    DWORD dwSize;
    DWORD dwFlags;
    DWORD dwManufactureIDOffset;
    DWORD dwSerialNumOffset;
} STORAGE_IDENTIFICATION, *PSTORAGE_IDENTIFICATION;
/* ms920817 SG_REQ -- HELD (page print; member types unpublished):
 *   typedef struct _SG_REQ { ... } SG_REQ, *PSG_REQ; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DISKIO_H */
