/*
 * Dvddata.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): graphics-book.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DVDDATA_H
#define AKARI_DVDDATA_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: graphics-book (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa451943 IDVDROM/IDVDROM::Bind (Header: Dvddata.h.) */
/* aa451957 IDVDROM/IDVDROM::Unbind (Header: Dvddata.h.) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DVDDATA_H */
