/*
 * Dvdioctl.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-block.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_DVDIOCTL_H
#define AKARI_DVDIOCTL_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447763 DVD_REGIONCE (page print, compiled) */
typedef struct _DVD_REGIONCE {
    HANDLE hDrive;
    UCHAR CopySystem;
    UCHAR RegionData;
    UCHAR SystemRegion;
    UCHAR ResetCount;
} DVD_REGIONCE, *PDVD_REGIONCE;

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-block (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms902120 IOCTL_DVD_GET_REGION: value adopted at the M99 three-generation sweep -- R1 ddk/ntddcdvd.h: CTL_CODE(IOCTL_DVD_BASE, 0x0405, METHOD_BUFFERED, FILE_READ_ACCESS) = 0x00335014 (the CE page prints the name only; the desktop serial/optical DDI value, CE inherited the interface). */
#define IOCTL_DVD_GET_REGION                0x00335014

#ifdef __cplusplus
}
#endif

#endif /* AKARI_DVDIOCTL_H */
