/*
 * Fmd.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-flash.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_FMD_H
#define AKARI_FMD_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-flash (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896143 BlockLockInfo -- HELD (page print; member types unpublished):
 *   typedef struct _BlockLockInfo { ... } BlockLockInfo, *PBlockLockInfo; */
/* aa447801 FlashInfo -- HELD (page print; member types unpublished):
 *   typedef struct _FlashInfo { ... } FlashInfo, *PFlashInfo; */
/* aa447814 FMDInterface -- HELD (page print; member types unpublished):
 *   typedef struct _FMDInterface { ... } FMDInterface, *PFMDInterface; */
/* ms920470 SectorInfo -- HELD (page print; member types unpublished):
 *   typedef struct _SectorInfo { ... } SectorInfo, *PSectorInfo; */
/* aa447809 FMD_Deinit: print `BOOL FMD_Deinit(PVOID hFMD);` */
BOOL FMD_Deinit(PVOID hFMD);
/* aa447810 FMD_EraseBlock: print `BOOL FMD_EraseBlock(BLOCK_IDblockID);` -- recorded verbatim (no compiled prototype) */
/* aa447811 FMD_GetBlockStatus: print `DWORD FMD_GetBlockStatus(BLOCK_IDblockID);` -- recorded verbatim (no compiled prototype) */
/* aa447812 FMD_GetInfo: print `BOOL FMD_GetInfo(PFlashInfopFlashInfo);` -- recorded verbatim (no compiled prototype) */
/* aa447813 FMD_Init: print `PVOID FMD_Init( LPCTSTRlpActiveReg, PPCI_REG_INFOpRegIn, PPCI_REG_INFOpRegOut);` -- recorded verbatim (no compiled prototype) */
/* aa447815 FMD_OEMIoControl: print `FMD_OEMIoControl(DWORDdwIoControlCode,PBYTEpInBuf,DWORDnInBufSize,PBYTEpOutBuf,DWORDnOutBufSize,PDWORDpBytesReturned);` */
void FMD_OEMIoControl(DWORD dwIoControlCode, PBYTE pInBuf, DWORD nInBufSize, PBYTE pOutBuf, DWORD nOutBufSize, PDWORD pBytesReturned);
/* aa447816 FMD_PowerDown: print `VOID FMD_PowerDown(VOID);` */
VOID FMD_PowerDown(void);
/* aa447817 FMD_PowerUp: print `VOID FMD_PowerUp(VOID);` */
VOID FMD_PowerUp(void);
/* aa447818 FMD_ReadSector: print `BOOL FMD_ReadSector(SECTOR_ADDRstartSectorAddr,LPBYTEpSectorBuff,PSectorInfo pSectorInfoBuff,DWORD dwNumSectors);` -- recorded verbatim (no compiled prototype) */
/* aa447819 FMD_SetBlockStatus: print `BOOL FMD_SetBlockStatus(BLOCK_IDblockID,DWORDdwStatus);` -- recorded verbatim (no compiled prototype) */
/* aa447820 FMD_WriteSector: print `BOOL FMD_WriteSector(SECTOR_ADDRstartSectorAddr,LPBYTEpSectorBuff,PSectorInfo pSectorInfoBuff,DWORD dwNumSectors);` -- recorded verbatim (no compiled prototype) */

/* ------------------------------------------------------------------
 * Book surface: drivers-flash (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms895489 How to Configure a Run-Time Image to Support a Flash Media Device */
/* ms895494 How to Develop a Flash Media Driver */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_FMD_H */
