/*
 * Gpe.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-display.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_GPE_H
#define AKARI_GPE_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct DRVENABLEDATA DRVENABLEDATA;   /* opaque carrier (layout unpublished) */
/* aa447837 GetGPE: print `GPE* GetGPE(void);` */
/* (record-only: parameter or return type unpublished) */
/* ms899338 GPEEnableDriver: print `BOOL APIENTRY GPEEnableDriver( ULONG iEngineVersion, ULONG cj, DRVENABLEDATA* pded, PENGCALLBACKS pEngCallbacks);` */
/* (record-only: parameter or return type unpublished) */
/* ms899334 GPE::AllocSurface (Header: Gpe.h.) */
/* ms899335 GPE::BltComplete (Header: Gpe.h.) */
/* ms899337 GPE::BltPrepare (Header: Gpe.h.) */
/* ms899339 GPE::GetModeInfo (Header: Gpe.h.) */
/* ms899340 GPE::Line (Header: Gpe.h.) */
/* ms899344 GPE::MovePointer (Header: Gpe.h.) */
/* ms899345 GPE::NumModes (Header: Gpe.h.) */
/* ms899346 GPE::SetMode (Header: Gpe.h.) */
/* ms899347 GPE::SetPointerShape (Header: Gpe.h.) */
/* ms899348 GPESurf::GPESurf (Header: Gpe.h.) */
/* ms899349 GPESurf::Init (Header: Gpe.h.) */

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899334 GPE::AllocSurface (Header: Gpe.h.) */
/* ms899335 GPE::BltComplete (Header: Gpe.h.) */
/* ms899337 GPE::BltPrepare (Header: Gpe.h.) */
/* ms899339 GPE::GetModeInfo (Header: Gpe.h.) */
/* ms899340 GPE::Line (Header: Gpe.h.) */
/* ms899344 GPE::MovePointer (Header: Gpe.h.) */
/* ms899345 GPE::NumModes (Header: Gpe.h.) */
/* ms899346 GPE::SetMode (Header: Gpe.h.) */
/* ms899347 GPE::SetPointerShape (Header: Gpe.h.) */
/* ms899348 GPESurf::GPESurf (Header: Gpe.h.) */
/* ms899349 GPESurf::Init (Header: Gpe.h.) */

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899334 GPE::AllocSurface (Header: Gpe.h.) */
/* ms899335 GPE::BltComplete (Header: Gpe.h.) */
/* ms899337 GPE::BltPrepare (Header: Gpe.h.) */
/* ms899339 GPE::GetModeInfo (Header: Gpe.h.) */
/* ms899340 GPE::Line (Header: Gpe.h.) */
/* ms899344 GPE::MovePointer (Header: Gpe.h.) */
/* ms899345 GPE::NumModes (Header: Gpe.h.) */
/* ms899346 GPE::SetMode (Header: Gpe.h.) */
/* ms899347 GPE::SetPointerShape (Header: Gpe.h.) */
/* ms899348 GPESurf::GPESurf (Header: Gpe.h.) */
/* ms899349 GPESurf::Init (Header: Gpe.h.) */

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899336 GPEBltParms: documented name-only (no value published; held) */
/* ms899341 GPELineParms: documented name-only (no value published; held) */
/* ms899342 GPEMode: documented name-only (no value published; held) */
/* ms899334 GPE::AllocSurface (Header: Gpe.h.) */
/* ms899335 GPE::BltComplete (Header: Gpe.h.) */
/* ms899337 GPE::BltPrepare (Header: Gpe.h.) */
/* ms899339 GPE::GetModeInfo (Header: Gpe.h.) */
/* ms899340 GPE::Line (Header: Gpe.h.) */
/* ms899344 GPE::MovePointer (Header: Gpe.h.) */
/* ms899345 GPE::NumModes (Header: Gpe.h.) */
/* ms899346 GPE::SetMode (Header: Gpe.h.) */
/* ms899347 GPE::SetPointerShape (Header: Gpe.h.) */
/* ms899348 GPESurf::GPESurf (Header: Gpe.h.) */
/* ms899349 GPESurf::Init (Header: Gpe.h.) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_GPE_H */
