/*
 * Hcdddsi.h or Ohcdddsi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-usbhost.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_HCDDDSI_H
#define AKARI_HCDDDSI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-usbhost (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899363 HcdMdd_CreateHcdObject: print `` */
/* (record-only: parameter or return type unpublished) */
/* ms899364 HcdMdd_CreateMemoryObject: print `` */
LPVOID HcdMdd_CreateMemoryObject(DWORD cbSize, DWORD cbHighPrioritySize, PUCHAR pVirtAddr, PUCHAR pPhysAddr);
/* ms899366 HcdMdd_DestroyMemoryObject: print `` */
/* (record-only: parameter or return type unpublished) */
/* ms899367 HcdMdd_PowerDown: print `` */
/* (record-only: parameter or return type unpublished) */
/* ms899368 HcdMdd_PowerUp: print `` */
/* (record-only: parameter or return type unpublished) */
/* ms899370 HcdMdd_SetCapability: print `DWORD HcdMdd_SetCapability( LPVOID lpvUhcdObject, DWORD dwCapability);` */
DWORD HcdMdd_SetCapability(LPVOID lpvUhcdObject, DWORD dwCapability);
/* ms899371 HcdPdd_CheckConfigPower: print `` */
BOOL HcdPdd_CheckConfigPower(UCHAR bPort, DWORD dwConfigPower, DWORD dwTotalPower);
/* ms899372 HcdPdd_Close: print `` */
BOOL HcdPdd_Close(DWORD dwOpenContext);
/* ms899373 HcdPdd_Deinit: print `` */
BOOL HcdPdd_Deinit(DWORD dwDeviceContext);
/* ms899374 HcdPdd_DllMain: print `` */
/* (record-only: parameter or return type unpublished) */
/* ms899375 HcdPdd_Init: print `` */
DWORD HcdPdd_Init(DWORD dwContext);
/* ms899376 HcdPdd_IOControl: print `` */
BOOL HcdPdd_IOControl(DWORD dwOpenContext);
/* ms899377 HcdPdd_Open: print `` */
DWORD HcdPdd_Open(DWORD dwDeviceContext, DWORD dwAccessCode, DWORD dwShareMode);
/* ms899378 HcdPdd_PowerDown: print `` */
void HcdPdd_PowerDown(DWORD dwDeviceContext);
/* ms899379 HcdPdd_PowerUp: print `` */
void HcdPdd_PowerUp(DWORD dwDeviceContext);
/* ms899380 HcdPdd_Read: print `` */
DWORD HcdPdd_Read(DWORD dwOpenContext);
/* ms899381 HcdPdd_Seek: print `` */
DWORD HcdPdd_Seek(DWORD dwOpenContext);
/* ms899382 HcdPdd_Write: print `` */
DWORD HcdPdd_Write(DWORD dwOpenContext);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_HCDDDSI_H */
