/*
 * Hiddi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-hid.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_HIDDI_H
#define AKARI_HIDDI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-hid (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899883 HID_DRIVER_SETTINGS (page print, compiled) */
typedef struct _HID_DRIVER_SETTINGS {
    DWORD dwVendorId;
    DWORD dwProductId;
    DWORD dwReleaseNumber;
    DWORD dwInterfaceNumber;
    DWORD dwCollection;
    DWORD dwUsagePage;
    DWORD dwUsage;
} HID_DRIVER_SETTINGS, *PHID_DRIVER_SETTINGS;
/* ms899890 HID_STRING_TYPE (page print, compiled) */
typedef enum _HID_STRING_TYPE {
    HID_STRING_INDEXED = 0,
    HID_STRING_ID_IMANUFACTURER,
    HID_STRING_ID_IPRODUCT,
    HID_STRING_ID_ISERIALNUMBER,
    HID_STRING_MAX
} HID_STRING_TYPE;
/* ms899395 HIDDeviceNotifications: print `BOOL HIDDeviceNotifications( DWORD dwMsg, WPARAM wParam, PVOID pvNotifyParameter);` */
AKARI_CE_IMPORT BOOL HIDDeviceNotifications(DWORD dwMsg, WPARAM wParam, PVOID pvNotifyParameter)
    AKARI_CE_NAME(HIDDeviceNotifications);

/* ------------------------------------------------------------------
 * Book surface: drivers-hid (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-hid (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899886 HID_FUNCS: documented name-only (no value published; held) */
/* ms899394 HIDDeviceAttach: documented name-only (no value published; held) */
/* ms902163 LPGET_INTERRUPT_REPORT: documented name-only (no value published; held) */
/* ms902165 LPGET_QUEUE_SIZE: documented name-only (no value published; held) */
/* ms902164 LPGET_REPORT: documented name-only (no value published; held) */
/* ms902167 LPGET_STRING: documented name-only (no value published; held) */
/* ms902174 LPSET_QUEUE_SIZE: documented name-only (no value published; held) */
/* ms902173 LPSET_REPORT: documented name-only (no value published; held) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_HIDDI_H */
