/*
 * Hidpddi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-hid.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_HIDPDDI_H
#define AKARI_HIDPDDI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-hid (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899400 HidP_FreeCollectionDescription: print `void HidP_FreeCollectionDescription( PHIDP_DEVICE_DESC DeviceDescription);` */
/* (record-only: parameter or return type unpublished) */
/* ms899405 HidP_GetCollectionDescription: print `NTSTATUS HidP_GetCollectionDescription( PHIDP_REPORT_DESCRIPTOR ReportDesc, ULONG DescLength, POOL_TYPE PoolType, PHIDP_DEVICE_DESC DeviceDescription);` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_HIDPDDI_H */
