/*
 * Hidpi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-hid.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_HIDPI_H
#define AKARI_HIDPI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-hid (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct USAGE USAGE;   /* opaque carrier (layout unpublished) */
/* ms899798 HIDP_KEYBOARD_DIRECTION (page print, compiled) */
typedef enum _HIDP_KEYBOARD_DIRECTION {
    HidP_Keyboard_Break,
    HidP_Keyboard_Make
} HIDP_KEYBOARD_DIRECTION;
/* ms899820 HIDP_REPORT_TYPE (page print, compiled) */
typedef enum _HIDP_REPORT_TYPE {
    HidP_Input,
    HidP_Output,
    HidP_Feature
} HIDP_REPORT_TYPE;
/* ms899854 HIDP_UNKNOWN_TOKEN (page print, compiled) */
typedef struct _HIDP_UNKNOWN_TOKEN {
    UCHAR Token;
    UCHAR Reserved[3];
    ULONG BitField;
} HIDP_UNKNOWN_TOKEN, * PHIDP_UNKNOWN_TOKEN;
/* ms899396 HIDP_BUTTON_CAPS -- HELD (page print; member types unpublished):
 *   typedef struct _HIDP_BUTTON_CAPS { ... } Range; */
/* ms899397 HIDP_CAPS -- HELD (page print; member types unpublished):
 *   typedef struct _HIDP_CAPS { ... } HIDP_CAPS, * PHIDP_CAPS; */
/* ms899398 HIDP_DATA -- HELD (page print; member types unpublished):
 *   typedef struct _HIDP_DATA { ... } HIDP_DATA, * PHIDP_DATA; */
/* ms899399 HIDP_EXTENDED_ATTRIBUTES -- HELD (page print; member types unpublished):
 *   typedef struct _HIDP_EXTENDED_ATTRIBUTES { ... } HIDP_EXTENDED_ATTRIBUTES, * PHIDP_EXTENDED_ATTRIBUTES; */
/* ms899801 HIDP_LINK_COLLECTION_NODE -- HELD (page print; member types unpublished):
 *   typedef struct _HIDP_LINK_COLLECTION_NODE { ... } HIDP_LINK_COLLECTION_NODE, * PHIDP_LINK_COLLECTION_NODE; */
/* ms899879 HIDP_VALUE_CAPS -- HELD (page print; member types unpublished):
 *   typedef struct _HIDP_VALUE_CAPS { ... } Range; */
/* ms923182 USAGE_AND_PAGE -- HELD (page print; member types unpublished):
 *   typedef struct _USAGE_AND_PAGE { ... } USAGE_AND_PAGE, * PUSAGE_AND_PAGE; */
/* ms899401 HidP_GetButtonCaps: print `NTSTATUS HidP_GetButtonCaps( HIDP_REPORT_TYPE ReportType, PHIDP_BUTTON_CAPS ButtonCaps, PUSHORT ButtonCapsLength, PHIDP_PREPARSED_DATA PreparsedData);` */
/* (record-only: parameter or return type unpublished) */
/* ms899402 HidP_GetButtons: print `#define HidP_GetButtons(Rty, UPa, LCo, ULi, ULe, Ppd, Rep, RLe) \ HidP_GetUsages(Rty, UPa, LCo, ULi, ULe, Ppd, Rep, RLe)` -- recorded verbatim (no compiled prototype) */
/* ms899403 HidP_GetButtonsEx: print `#define HidP_GetButtonsEx(Rty, LCo, BLi, ULe, Ppd, Rep, RLe) \ HidP_GetUsagesEx(Rty, LCo, BLi, ULe, Ppd, Rep, RLe)` -- recorded verbatim (no compiled prototype) */
/* ms899404 HidP_GetCaps: print `NTSTATUS HidP_GetCaps( PHIDP_PREPARSED_DATA PreparsedData, PHIDP_CAPS Capabilities);` */
/* (record-only: parameter or return type unpublished) */
/* ms899406 HidP_GetData: print `NTSTATUS HidP_GetData( HIDP_REPORT_TYPE ReportType, PHIDP_DATA DataList, PULONG DataLength, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899407 HidP_GetExtendedAttributes: print `NTSTATUS HidP_GetExtendedAttributes( HIDP_REPORT_TYPE ReportType, USHORT DataIndex, PHIDP_PREPARSED_DATA PreparsedData, PHIDP_EXTENDED_ATTRIBUTES Attributes, PULONG LengthAttributes);` */
/* (record-only: parameter or return type unpublished) */
/* ms899408 HidP_GetLinkCollectionNodes: print `NTSTATUS HidP_GetLinkCollectionNodes( PHIDP_LINK_COLLECTION_NODE LinkCollectionNodes, PULONG LinkCollectionNodesLength, PHIDP_PREPARSED_DATA PreparsedData);` */
/* (record-only: parameter or return type unpublished) */
/* ms899521 HidP_GetScaledUsageValue: print `NTSTATUS HidP_GetScaledUsageValue( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE Usage, PLONG UsageValue, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899730 HidP_GetSpecificButtonCaps: print `NTSTATUS HidP_GetSpecificButtonCaps( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE Usage, PULONG ButtonCapsLength, PHIDP_PREPARSED_DATA PreparsedData);` */
/* (record-only: parameter or return type unpublished) */
/* ms899736 HidP_GetSpecificValueCaps: print `NTSTATUS HidP_GetSpecificValueCaps( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE Usage, PHIDP_VALUE_CAPS ValueCaps, PULONG ValueCapsLength, PHIDP_PREPARSED_DATA PreparsedData);` */
/* (record-only: parameter or return type unpublished) */
/* ms899742 HidP_GetUsages: print `NTSTATUS HidP_GetUsages( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE* UsageList, ULONG* UsageLength, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899753 HidP_GetUsagesEx: print `NTSTATUS HidP_GetUsagesEx( HIDP_REPORT_TYPE ReportType, USHORT LinkCollection, PUSAGE_AND_PAGE ButtonList, ULONG* UsageLength, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899765 HidP_GetUsageValue: print `NTSTATUS HidP_GetUsageValue( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE Usage, PULONG UsageValue, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899779 HidP_GetUsageValueArray: print `NTSTATUS HidP_GetUsageValueArray( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE Usage, PCHAR UsageValue, USHORT UsageValueByteLength, PDIP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899783 HidP_GetValueCaps: print `NTSTATUS HidP_GetValueCaps( HIDP_REPORT_TYPE ReportType, PHIDP_VALUE_CAPS ValueCaps, PULONG ValueCapsLength, PHIDP_PREPARSED_DATA PreparsedData);` */
/* (record-only: parameter or return type unpublished) */
/* ms899786 HidP_InitializeReportForID: print `` */
/* (record-only: parameter or return type unpublished) */
/* ms899792 HidP_IsSameUsageAndPage: print `BOOLEAN HidP_IsSameUsageAndPage( USAGE_AND_PAGE u1, USAGE_AND_PAGE u2);` */
/* (record-only: parameter or return type unpublished) */
/* ms899808 HidP_MaxDataListLength: print `ULONG HidP_MaxDataListLength( HIDP_REPORT_TYPE ReportType, PHIDP_PREPARSED_DATA PreparsedData);` */
/* (record-only: parameter or return type unpublished) */
/* ms899811 HidP_MaxUsageListLength: print `ULONG HidP_MaxUsageListLength( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, PHIDP_PREPARSED_DATA PreparsedData);` */
/* (record-only: parameter or return type unpublished) */
/* ms899826 HidP_SetButtons: print `#define HidP_SetButtons(Rty, Up, Lco, ULi, ULe, Ppd, Rep, Rle) \ HidP_SetUsages(Rty, Up, Lco, ULi, ULe, Ppd, Rep, Rle)` -- recorded verbatim (no compiled prototype) */
/* ms899830 HidP_SetData: print `NTSTATUS HidP_SetData( HIDP_REPORT_TYPE ReportType, PHIDP_DATA DataList, OUT PULONG DataLength, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899837 HidP_SetScaledUsageValue: print `NTSTATUS HidP_SetScaledUsageValue( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE Usage, LONG UsageValue, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899842 HidP_SetUsages: print `NTSTATUS HidP_SetUsages( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, PUSAGE UsageList, PULONG UsageLength, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899845 HidP_SetUsageValue: print `NTSTATUS HidP_SetUsageValue( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE Usage, ULONG UsageValue, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899852 HidP_SetUsageValueArray: print `NTSTATUS HidP_SetUsageValueArray( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, USAGE Usage, PCHAR UsageValue, USHORT UsageValueByteLength, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899857 HidP_UnsetButtons: print `#define HidP_UnsetButtons(Rty, Up, Lco, ULi, ULe, Ppd, Rep, Rle) \ HidP_UnsetUsages(Rty, Up, Lco, ULi, ULe, Ppd, Rep, Rle)` -- recorded verbatim (no compiled prototype) */
/* ms899864 HidP_UnsetUsages: print `NTSTATUS HidP_UnsetUsages( HIDP_REPORT_TYPE ReportType, USAGE UsagePage, USHORT LinkCollection, PUSAGE UsageList, PULONG UsageLength, PHIDP_PREPARSED_DATA PreparsedData, PCHAR Report, ULONG ReportLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899866 HidP_UsageAndPageListDifference: print `NTSTATUS HidP_UsageAndPageListDifference( PUSAGE_AND_PAGE PreviousUsageList, PUSAGE_AND_PAGE CurrentUsageList, PUSAGE_AND_PAGE BreakUsageList, PUSAGE_AND_PAGE MakeUsageList, ULONG UsageListLength);` */
/* (record-only: parameter or return type unpublished) */
/* ms899869 HidP_UsageListDifference: print `NTSTATUS HidP_UsageListDifference( PUSAGE PreviousUsageList, PUSAGE CurrentUsageList, PUSAGE BreakUsageList, PUSAGE MakeUsageList, ULONG UsageListLength);` */
/* (record-only: parameter or return type unpublished) */

/* ------------------------------------------------------------------
 * Book surface: drivers-hid (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms892167 HID Button Capability Arrays */
/* ms892168 HID Collection Capabilities */
/* ms892169 HID Data Indexes */
/* ms892170 HID Driver Migration */
/* ms894890 HID Driver Registry Settings */
/* ms892172 HID Driver Samples */
/* ms892174 HID Link Collections */
/* ms892175 HID Preparsed Data */
/* ms892176 HID Report Initialization */
/* ms892177 HID Report Interpretation */
/* ms892178 HID Value Capability Arrays */
/* ms923752 Troubleshooting: Dropped HID Reports */
/* ms923757 Troubleshooting: HID Report Identifier Errors */

/* ------------------------------------------------------------------
 * Book surface: drivers-hid (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms892167 HID Button Capability Arrays */
/* ms892168 HID Collection Capabilities */
/* ms892169 HID Data Indexes */
/* ms892170 HID Driver Migration */
/* ms894890 HID Driver Registry Settings */
/* ms892172 HID Driver Samples */
/* ms892174 HID Link Collections */
/* ms892175 HID Preparsed Data */
/* ms892176 HID Report Initialization */
/* ms892177 HID Report Interpretation */
/* ms892178 HID Value Capability Arrays */
/* ms923752 Troubleshooting: Dropped HID Reports */
/* ms923757 Troubleshooting: HID Report Identifier Errors */

/* ------------------------------------------------------------------
 * Book surface: drivers-hid (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms892167 HID Button Capability Arrays */
/* ms892168 HID Collection Capabilities */
/* ms892169 HID Data Indexes */
/* ms892170 HID Driver Migration */
/* ms894890 HID Driver Registry Settings */
/* ms892172 HID Driver Samples */
/* ms892174 HID Link Collections */
/* ms892175 HID Preparsed Data */
/* ms892176 HID Report Initialization */
/* ms892177 HID Report Interpretation */
/* ms892178 HID Value Capability Arrays */
/* ms923752 Troubleshooting: Dropped HID Reports */
/* ms923757 Troubleshooting: HID Report Identifier Errors */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_HIDPI_H */
