/*
 * IExchangeClient.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): exchange.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_IEXCHANGECLIENT_H
#define AKARI_IEXCHANGECLIENT_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: exchange (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa516110 IExchangeClient::CancelPendingRequests (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516134 IExchangeClient::GetServer (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516135 IExchangeClient::Initialize (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516141 IExchangeClient::RequestContacts (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516142 IExchangeClient::RequestFreeBusyData (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516143 IExchangeClient::RequestGALSearch (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516149 IExchangeClient::SetCredentials (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516150 IExchangeClient::SetServer (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516151 IExchangeClient::Uninitialize (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516112 IExchangeClientContactInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516113 IExchangeClientContactInformation::GetEmailAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516114 IExchangeClientContactInformation::GetHomeAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516115 IExchangeClientContactInformation::GetHomePhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516116 IExchangeClientContactInformation::GetMobilePhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516117 IExchangeClientContactInformation::GetWorkAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516118 IExchangeClientContactInformation::GetWorkPhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516120 IExchangeClientDataItemArray::GetItemAt (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516121 IExchangeClientDataItemArray::GetItemCount (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516123 IExchangeClientFreeBusyInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516124 IExchangeClientFreeBusyInformation::GetEmailAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516125 IExchangeClientFreeBusyInformation::GetFreeBusyData (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516127 IExchangeClientGALSearchInformation::GetAlias (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516128 IExchangeClientGALSearchInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516129 IExchangeClientGALSearchInformation::GetOffice (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516130 IExchangeClientGALSearchInformation::GetPhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516132 IExchangeClientGALSearchInformation::GetSMTPAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516140 IExchangeClientRequest::Cancel (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516144 IExchangeClientRequest::GetDataItemArray (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516145 IExchangeClientRequest::GetHttpStatus (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516146 IExchangeClientRequest::GetStatus (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516147 IExchangeClientRequest::GetType (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516138 IExchangeClientRequestCallback::OnRequestProgress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516139 IExchangeClientRequestCallback::OnShutdown (Header: IExchangeClient.h, IExchangeClient.idl.) */

/* ------------------------------------------------------------------
 * Book surface: exchange (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms862146 Exchange Client API Organization */
/* ms862148 Exchange Client Migration */
/* ms862149 Exchange Client OS Design Development */
/* aa513729 Exchange Client Registry Settings */
/* ms897393 Exchange Client Samples */
/* ms862150 Exchange Client Security */
/* ms862559 Modifying Returned Contact Information */
/* ms862684 Retrieving Information from an Exchange Server */

/* ------------------------------------------------------------------
 * Book surface: exchange (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa516110 IExchangeClient::CancelPendingRequests (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516134 IExchangeClient::GetServer (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516135 IExchangeClient::Initialize (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516141 IExchangeClient::RequestContacts (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516142 IExchangeClient::RequestFreeBusyData (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516143 IExchangeClient::RequestGALSearch (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516149 IExchangeClient::SetCredentials (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516150 IExchangeClient::SetServer (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516151 IExchangeClient::Uninitialize (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516112 IExchangeClientContactInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516113 IExchangeClientContactInformation::GetEmailAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516114 IExchangeClientContactInformation::GetHomeAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516115 IExchangeClientContactInformation::GetHomePhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516116 IExchangeClientContactInformation::GetMobilePhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516117 IExchangeClientContactInformation::GetWorkAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516118 IExchangeClientContactInformation::GetWorkPhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516120 IExchangeClientDataItemArray::GetItemAt (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516121 IExchangeClientDataItemArray::GetItemCount (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516123 IExchangeClientFreeBusyInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516124 IExchangeClientFreeBusyInformation::GetEmailAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516125 IExchangeClientFreeBusyInformation::GetFreeBusyData (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516127 IExchangeClientGALSearchInformation::GetAlias (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516128 IExchangeClientGALSearchInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516129 IExchangeClientGALSearchInformation::GetOffice (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516130 IExchangeClientGALSearchInformation::GetPhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516132 IExchangeClientGALSearchInformation::GetSMTPAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516140 IExchangeClientRequest::Cancel (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516144 IExchangeClientRequest::GetDataItemArray (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516145 IExchangeClientRequest::GetHttpStatus (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516146 IExchangeClientRequest::GetStatus (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516147 IExchangeClientRequest::GetType (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516138 IExchangeClientRequestCallback::OnRequestProgress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516139 IExchangeClientRequestCallback::OnShutdown (Header: IExchangeClient.h, IExchangeClient.idl.) */

/* ------------------------------------------------------------------
 * Book surface: exchange (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms862146 Exchange Client API Organization */
/* ms862148 Exchange Client Migration */
/* ms862149 Exchange Client OS Design Development */
/* aa513729 Exchange Client Registry Settings */
/* ms897393 Exchange Client Samples */
/* ms862150 Exchange Client Security */
/* ms862559 Modifying Returned Contact Information */
/* ms862684 Retrieving Information from an Exchange Server */

/* ------------------------------------------------------------------
 * Book surface: exchange (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms863932 ContactsSearchCriteria: prototype printed by the page; derived at the M99 sweep. */
typedef struct ContactsSearchCriteria {
    WCHAR* wszFirstName;
    WCHAR* wszLastName;
} ContactsSearchCriteria;

/* aa514944 ExchangeClientRequestStatus: documented name-only (no value published; held) */
/* aa514947 ExchangeClientRequestType: documented name-only (no value published; held) */
/* aa515003 FreeBusyCriteria: prototype printed by the page; derived at the M99 sweep. */
typedef struct FreeBusyCriteria {
    WCHAR* wszAlias;
    SYSTEMTIME* pstStart;
} FreeBusyCriteria;

/* aa515013 GALSearchCriteria: prototype printed by the page; derived at the M99 sweep. */
typedef struct GALSearchCriteria {
    WCHAR* wszAlias;
    WCHAR* wszFirstName;
    WCHAR* wszLastName;
} GALSearchCriteria;

/* aa513745 OWAEC_E_: documented name-only (no value published; held) */
/* aa516110 IExchangeClient::CancelPendingRequests (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516134 IExchangeClient::GetServer (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516135 IExchangeClient::Initialize (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516141 IExchangeClient::RequestContacts (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516142 IExchangeClient::RequestFreeBusyData (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516143 IExchangeClient::RequestGALSearch (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516149 IExchangeClient::SetCredentials (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516150 IExchangeClient::SetServer (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516151 IExchangeClient::Uninitialize (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516112 IExchangeClientContactInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516113 IExchangeClientContactInformation::GetEmailAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516114 IExchangeClientContactInformation::GetHomeAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516115 IExchangeClientContactInformation::GetHomePhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516116 IExchangeClientContactInformation::GetMobilePhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516117 IExchangeClientContactInformation::GetWorkAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516118 IExchangeClientContactInformation::GetWorkPhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516120 IExchangeClientDataItemArray::GetItemAt (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516121 IExchangeClientDataItemArray::GetItemCount (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516123 IExchangeClientFreeBusyInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516124 IExchangeClientFreeBusyInformation::GetEmailAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516125 IExchangeClientFreeBusyInformation::GetFreeBusyData (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516127 IExchangeClientGALSearchInformation::GetAlias (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516128 IExchangeClientGALSearchInformation::GetDisplayName (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516129 IExchangeClientGALSearchInformation::GetOffice (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516130 IExchangeClientGALSearchInformation::GetPhoneNumber (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516132 IExchangeClientGALSearchInformation::GetSMTPAddress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516140 IExchangeClientRequest::Cancel (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516144 IExchangeClientRequest::GetDataItemArray (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516145 IExchangeClientRequest::GetHttpStatus (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516146 IExchangeClientRequest::GetStatus (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516147 IExchangeClientRequest::GetType (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516138 IExchangeClientRequestCallback::OnRequestProgress (Header: IExchangeClient.h, IExchangeClient.idl.) */
/* aa516139 IExchangeClientRequestCallback::OnShutdown (Header: IExchangeClient.h, IExchangeClient.idl.) */

/* ------------------------------------------------------------------
 * Book surface: exchange (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms862146 Exchange Client API Organization */
/* ms862148 Exchange Client Migration */
/* ms862149 Exchange Client OS Design Development */
/* aa513729 Exchange Client Registry Settings */
/* ms897393 Exchange Client Samples */
/* ms862150 Exchange Client Security */
/* ms862559 Modifying Returned Contact Information */
/* ms862684 Retrieving Information from an Exchange Server */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_IEXCHANGECLIENT_H */
