/*
 * Keybddr.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-kbd.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_KEYBDDR_H
#define AKARI_KEYBDDR_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-kbd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-kbd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890515 Adding Keyboard Layouts */
/* ms923760 Adding Keyboard LED Support to the HID Keyboard Driver */
/* ms890989 Brazilian (ABNT) Keyboard */
/* ms923766 Building the Keyboard Driver DLLs */
/* ms923767 Configuring the Keyboard Driver Registry */
/* ms923769 Copying the Windows CE .NET 4.1 or Earlier Keyboard Driver to Windows CE .NET 4.2 or Later */
/* aa448247 Creating the Keyboard Device Layout */
/* aa448248 Creating the Keyboard DLL Sources File */
/* aa448249 Creating the Keyboard Input Language */
/* aa448250 Developing the Keyboard PDD Entry Point */
/* aa447467 Device Layout Data */
/* aa447524 Dutch Keyboard */
/* ms892155 French Keyboard */
/* ms892159 German Keyboard */
/* ms892173 HID Keyboard Driver Dependencies on the GWES Keyboard Driver */
/* aa448257 Implementing the KeybdPdd_GetEventEx2 Function */
/* aa448258 Implementing the Keyboard PDD List */
/* ms892234 Input Language Data */
/* ms892470 Italian Keyboard */
/* ms892472 Japanese Keyboard */
/* ms892476 Keyboard Driver Registry Settings */
/* ms892478 Keyboard Driver Samples */
/* ms892479 Keyboard Identification */
/* ms892481 Keyboard PDDs */
/* ms892483 Korean Keyboard */
/* aa448259 Migrating the Keyboard DLL Without Conforming to the Layout Manager Interface */
/* aa448260 Migrating the Keyboard PDD Without Conforming to the Layout Manager Interface */
/* aa447551 Portuguese Keyboard */
/* aa447582 PS/2 Keyboard Driver Scan Code Support */
/* aa447591 Remote Desktop Protocol Support */
/* ms894033 Spanish Keyboard */
/* ms894053 Swedish Keyboard */
/* ms894072 United Kingdom Keyboard */
/* ms894073 United States 101 Keyboard */
/* aa448264 Updating the Keyboard Driver IST */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_KEYBDDR_H */
