/*
 * Keybdpdd.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-kbd.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_KEYBDPDD_H
#define AKARI_KEYBDPDD_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-kbd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms902146 KEYBD_PDD -- HELD (page print; member types unpublished):
 *   typedef struct tagKEYBD_PDD { ... } KEYBD_PDD, *PKEYBD_PDD; */

/* ------------------------------------------------------------------
 * Book surface: drivers-kbd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-kbd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919401 PFN_KEYBD_EVENT: prototype printed by the page; derived at the M99 sweep. */
typedef void (*PFN_KEYBD_EVENT)(UINT uiPddId, UINT32 uiScanCode, BOOL fKeyDown);

/* ms919402 PFN_KEYBD_PDD_ENTRY: documented name-only (no value published; held) */
/* ms919403 PFN_KEYBD_PDD_POWER_HANDLER: prototype printed by the page; derived at the M99 sweep. */
typedef void (*PFN_KEYBD_PDD_POWER_HANDLER)(UINT uiPddId, BOOL fTurnOff);

/* ms919404 PFN_KEYBD_PDD_TOGGLE_LIGHTS: prototype printed by the page; derived at the M99 sweep. */
typedef void (*PFN_KEYBD_PDD_TOGGLE_LIGHTS)(UINT uiPddId, KEY_STATE_FLAGS KeyStateFlags);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_KEYBDPDD_H */
