/*
 * Led_drvr.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-nled.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_LED_DRVR_H
#define AKARI_LED_DRVR_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-nled (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms905300 NLedDriverGetDeviceInfo: print `BOOL NLedDriverGetDeviceInfo(INT nId,PVOID pOutput);` */
AKARI_CE_IMPORT BOOL NLedDriverGetDeviceInfo(INT nId, PVOID pOutput)
    AKARI_CE_NAME(NLedDriverGetDeviceInfo);
/* ms905305 NLedDriverInitialize: print `BOOL NLedDriverInitialize (void);` */
AKARI_CE_IMPORT BOOL NLedDriverInitialize(void)
    AKARI_CE_NAME(NLedDriverInitialize);
/* ms905309 NLedDriverPowerDown: print `VOID NLedDriverPowerDown(BOOLpower_down);` */
AKARI_CE_IMPORT VOID NLedDriverPowerDown(BOOL power_down)
    AKARI_CE_NAME(NLedDriverPowerDown);
/* ms905313 NLedDriverSetDevice: print `BOOL NLedDriverSetDevice(INT nInfoId,PVOID pInput);` */
AKARI_CE_IMPORT BOOL NLedDriverSetDevice(INT nInfoId, PVOID pInput)
    AKARI_CE_NAME(NLedDriverSetDevice);

/* ------------------------------------------------------------------
 * Book surface: drivers-nled (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms895501 Moving a Notification LED Driver from GWES to Device Manager */
/* ms892549 Notification LED Driver Development Concepts */
/* ms892550 Notification LED Driver Samples */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_LED_DRVR_H */
