/*
 * Mmddk.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-audio.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_MMDDK_H
#define AKARI_MMDDK_H

#include "Mmsystem.h"   /* HMIXER and the wave/mixer carriers */


#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447861 MIXEROPENDESC (page print, compiled) */
typedef struct tMIXEROPENDESC {
    HMIXER hmx;
    LPVOID pReserved0;
    DWORD dwCallback;
    DWORD dwInstance;
} MIXEROPENDESC, *PMIXEROPENDESC;
/* aa447867 MXDM_CLOSE (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_CLOSE;
/* aa447868 MXDM_GETCONTROLDETAILS (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_GETCONTROLDETAILS;
/* aa447869 MXDM_GETDEVCAPS (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_GETDEVCAPS;
/* aa447870 MXDM_GETLINECONTROLS (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_GETLINECONTROLS;
/* aa447871 MXDM_GETLINEINFO (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_GETLINEINFO;
/* aa447872 MXDM_GETNUMDEVS (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_GETNUMDEVS;
/* aa447873 MXDM_INIT (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_INIT;
/* aa447874 MXDM_OPEN (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_OPEN;
/* aa447875 MXDM_SETCONTROLDETAILS (page print, compiled) */
typedef struct  {
    DWORD uDeviceId;
    UINT uMsg;
    DWORD dwUser;
    DWORD lParam1;
    DWORD lParam2;
} MXDM_SETCONTROLDETAILS;
/* ms923288 WAVEOPENDESC -- HELD (page print; member types unpublished):
 *   typedef struct waveopendesc_tag { ... } WAVEOPENDESC; */
/* ms923289 WAVEOUTEXTCAPS -- HELD (page print; member types unpublished):
 *   typedef struct tag_WAVEOUTEXTCAPS { ... } WAVEOUTEXTCAPS; */
/* aa448329 WAVEPROPINFO -- HELD (page print; member types unpublished):
 *   typedef struct tag_WAVEPROPINFO { ... } WAVEPROPINFO, * PWAVEPROPINFO; */

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890477 ACM Format Tags and Filter Tags */
/* ms890640 Audio Device Instances */
/* ms890647 Audio Driver Migration */
/* ms890665 Audio Driver Registry Settings */
/* ms890671 Audio MDD and PDD */
/* ms890682 Audio Mixer */
/* ms891137 Codec Configuration */
/* ms892151 Extra Bytes */
/* ms892247 Interrupt Handling in Audio Drivers */
/* aa447547 Playing and Recording */
/* aa447550 Porting a Desktop ACM Driver to Windows CE */
/* aa447558 Power Management in Audio Drivers */
/* aa447585 Recognized Formats */
/* aa447597 Required Entry-point Function */
/* aa447619 Sample ACM Drivers */
/* aa447626 Samples per Block */
/* ms894065 Tips for Writing ACM Drivers */
/* ms894070 Types of ACM Drivers */
/* ms894748 WAV_IOControl Messages and Parameter Structures */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_MMDDK_H */
