/* Mqoai.h -- documented-case alias for Mq.h.
 * The MSMQ COM object model pages (MSMQApplication, MSMQEvent,
 * MSMQMessage, MSMQQuery, MSMQQueue, MSMQQueueInfo, MSMQQueueInfos and
 * their properties/methods -- 72 rows, Link Library Mqoa.lib) print
 * Header: Mqoai.h; the object records are carried by Mq.h (M75a). */
#include "Mq.h"/* ------------------------------------------------------------------
 * Book surface: servers (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms895153 MSMQEvent.Arrived (Header: Mqoai.h.) */
/* ms895154 MSMQEvent.ArrivedError (Header: Mqoai.h.) */
/* ms895158 MSMQMessage.Ack (Header: Mqoai.h.) */
/* ms895160 MSMQMessage.AdminQueueInfo (Header: Mqoai.h.) */
/* ms895163 MSMQMessage.AppSpecific (Header: Mqoai.h.) */
/* ms895164 MSMQMessage.ArrivedTime (Header: Mqoai.h.) */
/* ms895166 MSMQMessage.AuthLevel (Header: Mqoai.h.) */
/* ms895169 MSMQMessage.Body (Header: Mqoai.h.) */
/* ms895170 MSMQMessage.BodyLength (Header: Mqoai.h.) */
/* ms895173 MSMQMessage.Class (Header: Mqoai.h.) */
/* ms895174 MSMQMessage.CorrelationId (Header: Mqoai.h.) */
/* ms895176 MSMQMessage.Delivery (Header: Mqoai.h.) */
/* ms895178 MSMQMessage.DestinationQueueInfo (Header: Mqoai.h.) */
/* ms895181 MSMQMessage.EncryptAlgorithm (Header: Mqoai.h.) */
/* ms895182 MSMQMessage.Extension (Header: Mqoai.h.) */
/* ms895185 MSMQMessage.HashAlgorithm (Header: Mqoai.h.) */
/* ms895186 MSMQMessage.Id (Header: Mqoai.h.) */
/* ms895189 MSMQMessage.IsAuthenticated (Header: Mqoai.h.) */
/* ms895190 MSMQMessage.Journal (Header: Mqoai.h.) */
/* ms895193 MSMQMessage.Label (Header: Mqoai.h.) */
/* ms895194 MSMQMessage.MaxTimeToReachQueue (Header: Mqoai.h.) */
/* ms895196 MSMQMessage.MaxTimeToReceive (Header: Mqoai.h.) */
/* ms895199 MSMQMessage.Priority (Header: Mqoai.h.) */
/* ms895200 MSMQMessage.PrivLevel (Header: Mqoai.h.) */
/* ms895203 MSMQMessage.ResponseQueueInfo (Header: Mqoai.h.) */
/* ms895204 MSMQMessage.Send (Header: Mqoai.h.) */
/* ms895207 MSMQMessage.SenderCertificate (Header: Mqoai.h.) */
/* ms895208 MSMQMessage.SenderId (Header: Mqoai.h.) */
/* ms895211 MSMQMessage.SenderIdType (Header: Mqoai.h.) */
/* ms895212 MSMQMessage.SentTime (Header: Mqoai.h.) */
/* ms895215 MSMQMessage.SourceMachineGuid (Header: Mqoai.h.) */
/* ms895217 MSMQMessage.Trace (Header: Mqoai.h.) */
/* ms895224 MSMQQueue.Access (Header: Mqoai.h.) */
/* ms895225 MSMQQueue.Close (Header: Mqoai.h.) */
/* ms895228 MSMQQueue.EnableNotification (Header: Mqoai.h.) */
/* ms895231 MSMQQueue.Handle (Header: Mqoai.h.) */
/* ms895276 MSMQQueue.IsOpen (Header: Mqoai.h.) */
/* ms895279 MSMQQueue.Peek (Header: Mqoai.h.) */
/* ms895281 MSMQQueue.PeekCurrent (Header: Mqoai.h.) */
/* ms895284 MSMQQueue.PeekNext (Header: Mqoai.h.) */
/* ms895286 MSMQQueue.QueueInfo (Header: Mqoai.h.) */
/* ms895287 MSMQQueue.Receive (Header: Mqoai.h.) */
/* ms895289 MSMQQueue.ReceiveCurrent (Header: Mqoai.h.) */
/* ms895614 MSMQQueue.Reset (Header: Mqoai.h.) */
/* ms895653 MSMQQueue.ShareMode (Header: Mqoai.h.) */
/* ms895234 MSMQQueueInfo.Authenticate (Header: Mqoai.h.) */
/* ms895236 MSMQQueueInfo.BasePriority (Header: Mqoai.h.) */
/* ms895238 MSMQQueueInfo.Create (Header: Mqoai.h.) */
/* ms895240 MSMQQueueInfo.CreateTime (Header: Mqoai.h.) */
/* ms895241 MSMQQueueInfo.Delete (Header: Mqoai.h.) */
/* ms895244 MSMQQueueInfo.FormatName (Header: Mqoai.h.) */
/* ms895245 MSMQQueueInfo.IsTransactional (Header: Mqoai.h.) */
/* ms895248 MSMQQueueInfo.IsWorldReadable (Header: Mqoai.h.) */
/* ms895249 MSMQQueueInfo.Journal (Header: Mqoai.h.) */
/* ms895252 MSMQQueueInfo.JournalQuota (Header: Mqoai.h.) */
/* ms895253 MSMQQueueInfo.Label (Header: Mqoai.h.) */
/* ms895256 MSMQQueueInfo.ModifyTime (Header: Mqoai.h.) */
/* ms895257 MSMQQueueInfo.Open (Header: Mqoai.h.) */
/* ms895260 MSMQQueueInfo.PathName (Header: Mqoai.h.) */
/* ms895261 MSMQQueueInfo.PrivLevel (Header: Mqoai.h.) */
/* ms895264 MSMQQueueInfo.QueueGuid (Header: Mqoai.h.) */
/* ms895266 MSMQQueueInfo.Quota (Header: Mqoai.h.) */
/* ms895268 MSMQQueueInfo.Refresh (Header: Mqoai.h.) */
/* ms895272 MSMQQueueInfo.ServiceTypeGuid (Header: Mqoai.h.) */
/* ms895275 MSMQQueueInfo.Update (Header: Mqoai.h.) */
/* ------------------------------------------------------------------
 * Book surface: servers (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms895153 MSMQEvent.Arrived (Header: Mqoai.h.) */
/* ms895154 MSMQEvent.ArrivedError (Header: Mqoai.h.) */
/* ms895158 MSMQMessage.Ack (Header: Mqoai.h.) */
/* ms895160 MSMQMessage.AdminQueueInfo (Header: Mqoai.h.) */
/* ms895163 MSMQMessage.AppSpecific (Header: Mqoai.h.) */
/* ms895164 MSMQMessage.ArrivedTime (Header: Mqoai.h.) */
/* ms895166 MSMQMessage.AuthLevel (Header: Mqoai.h.) */
/* ms895169 MSMQMessage.Body (Header: Mqoai.h.) */
/* ms895170 MSMQMessage.BodyLength (Header: Mqoai.h.) */
/* ms895173 MSMQMessage.Class (Header: Mqoai.h.) */
/* ms895174 MSMQMessage.CorrelationId (Header: Mqoai.h.) */
/* ms895176 MSMQMessage.Delivery (Header: Mqoai.h.) */
/* ms895178 MSMQMessage.DestinationQueueInfo (Header: Mqoai.h.) */
/* ms895181 MSMQMessage.EncryptAlgorithm (Header: Mqoai.h.) */
/* ms895182 MSMQMessage.Extension (Header: Mqoai.h.) */
/* ms895185 MSMQMessage.HashAlgorithm (Header: Mqoai.h.) */
/* ms895186 MSMQMessage.Id (Header: Mqoai.h.) */
/* ms895189 MSMQMessage.IsAuthenticated (Header: Mqoai.h.) */
/* ms895190 MSMQMessage.Journal (Header: Mqoai.h.) */
/* ms895193 MSMQMessage.Label (Header: Mqoai.h.) */
/* ms895194 MSMQMessage.MaxTimeToReachQueue (Header: Mqoai.h.) */
/* ms895196 MSMQMessage.MaxTimeToReceive (Header: Mqoai.h.) */
/* ms895199 MSMQMessage.Priority (Header: Mqoai.h.) */
/* ms895200 MSMQMessage.PrivLevel (Header: Mqoai.h.) */
/* ms895203 MSMQMessage.ResponseQueueInfo (Header: Mqoai.h.) */
/* ms895204 MSMQMessage.Send (Header: Mqoai.h.) */
/* ms895207 MSMQMessage.SenderCertificate (Header: Mqoai.h.) */
/* ms895208 MSMQMessage.SenderId (Header: Mqoai.h.) */
/* ms895211 MSMQMessage.SenderIdType (Header: Mqoai.h.) */
/* ms895212 MSMQMessage.SentTime (Header: Mqoai.h.) */
/* ms895215 MSMQMessage.SourceMachineGuid (Header: Mqoai.h.) */
/* ms895217 MSMQMessage.Trace (Header: Mqoai.h.) */
/* ms895224 MSMQQueue.Access (Header: Mqoai.h.) */
/* ms895225 MSMQQueue.Close (Header: Mqoai.h.) */
/* ms895228 MSMQQueue.EnableNotification (Header: Mqoai.h.) */
/* ms895231 MSMQQueue.Handle (Header: Mqoai.h.) */
/* ms895276 MSMQQueue.IsOpen (Header: Mqoai.h.) */
/* ms895279 MSMQQueue.Peek (Header: Mqoai.h.) */
/* ms895281 MSMQQueue.PeekCurrent (Header: Mqoai.h.) */
/* ms895284 MSMQQueue.PeekNext (Header: Mqoai.h.) */
/* ms895286 MSMQQueue.QueueInfo (Header: Mqoai.h.) */
/* ms895287 MSMQQueue.Receive (Header: Mqoai.h.) */
/* ms895289 MSMQQueue.ReceiveCurrent (Header: Mqoai.h.) */
/* ms895614 MSMQQueue.Reset (Header: Mqoai.h.) */
/* ms895653 MSMQQueue.ShareMode (Header: Mqoai.h.) */
/* ms895234 MSMQQueueInfo.Authenticate (Header: Mqoai.h.) */
/* ms895236 MSMQQueueInfo.BasePriority (Header: Mqoai.h.) */
/* ms895238 MSMQQueueInfo.Create (Header: Mqoai.h.) */
/* ms895240 MSMQQueueInfo.CreateTime (Header: Mqoai.h.) */
/* ms895241 MSMQQueueInfo.Delete (Header: Mqoai.h.) */
/* ms895244 MSMQQueueInfo.FormatName (Header: Mqoai.h.) */
/* ms895245 MSMQQueueInfo.IsTransactional (Header: Mqoai.h.) */
/* ms895248 MSMQQueueInfo.IsWorldReadable (Header: Mqoai.h.) */
/* ms895249 MSMQQueueInfo.Journal (Header: Mqoai.h.) */
/* ms895252 MSMQQueueInfo.JournalQuota (Header: Mqoai.h.) */
/* ms895253 MSMQQueueInfo.Label (Header: Mqoai.h.) */
/* ms895256 MSMQQueueInfo.ModifyTime (Header: Mqoai.h.) */
/* ms895257 MSMQQueueInfo.Open (Header: Mqoai.h.) */
/* ms895260 MSMQQueueInfo.PathName (Header: Mqoai.h.) */
/* ms895261 MSMQQueueInfo.PrivLevel (Header: Mqoai.h.) */
/* ms895264 MSMQQueueInfo.QueueGuid (Header: Mqoai.h.) */
/* ms895266 MSMQQueueInfo.Quota (Header: Mqoai.h.) */
/* ms895268 MSMQQueueInfo.Refresh (Header: Mqoai.h.) */
/* ms895272 MSMQQueueInfo.ServiceTypeGuid (Header: Mqoai.h.) */
/* ms895275 MSMQQueueInfo.Update (Header: Mqoai.h.) */

