/*
 * Msacmdrv.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-audio.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_MSACMDRV_H
#define AKARI_MSACMDRV_H

#include "Mmsystem.h"   /* WAVEFORMATEX carrier */

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896091 ACMDRVFORMATSUGGEST (page print, compiled) */
typedef struct  {
    DWORD cbStruct;
    DWORD fdwSuggest;
    LPWAVEFORMATEX pwfxSrc;
    DWORD cbwfxSrc;
    LPWAVEFORMATEX pwfxDst;
    DWORD cbwfxDst;
} ACMDRVFORMATSUGGEST;
/* ms896096 ACMDRVSTREAMSIZE (page print, compiled) */
typedef struct  {
    DWORD cbStruct;
    DWORD fdwSize;
    DWORD cbSrcLength;
    DWORD cbDstLength;
} ACMDRVSTREAMSIZE;
/* ms896093 ACMDRVOPENDESC -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } ACMDRVOPENDESC; */
/* ms896094 ACMDRVSTREAMHEADER -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } ACMDRVSTREAMHEADER; */
/* ms896095 ACMDRVSTREAMINSTANCE -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } ACMDRVSTREAMINSTANCE; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_MSACMDRV_H */
