/*
 * Msacmdrv.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-audio.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_MSACMDRV_H
#define AKARI_MSACMDRV_H

#include "Mmsystem.h"   /* WAVEFORMATEX carrier */

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896091 ACMDRVFORMATSUGGEST (page print, compiled) */
typedef struct  {
    DWORD cbStruct;
    DWORD fdwSuggest;
    LPWAVEFORMATEX pwfxSrc;
    DWORD cbwfxSrc;
    LPWAVEFORMATEX pwfxDst;
    DWORD cbwfxDst;
} ACMDRVFORMATSUGGEST;
/* ms896096 ACMDRVSTREAMSIZE (page print, compiled) */
typedef struct  {
    DWORD cbStruct;
    DWORD fdwSize;
    DWORD cbSrcLength;
    DWORD cbDstLength;
} ACMDRVSTREAMSIZE;
/* ms896093 ACMDRVOPENDESC -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } ACMDRVOPENDESC; */
/* ms896094 ACMDRVSTREAMHEADER -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } ACMDRVSTREAMHEADER; */
/* ms896095 ACMDRVSTREAMINSTANCE -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } ACMDRVSTREAMINSTANCE; */

#ifdef __cplusplus
}
#endif

/* ================================================================== */
/* M96 value adoption -- values adopted from the CeGCC-lineage w32api
 * reference (R1, public domain; docs/clean-room.md par.4
 * revision 2026-09-10).  Every name below is documented by
 * the official CE pages WITHOUT a value (see the record
 * comments and the held ledger in this header); the value
 * is a CE-era ABI fact carried by the CE lineage itself.
 * Desktop mingw-w64 was considered and EXCLUDED as a source
 * (desktop-era values; policy note in clean-room.md).  R1's
 * license-exception files (winsock*, gl*) are unused.
 * ================================================================== */

/* ---- ACM_ family (2 names; R1) ---- */
#define ACM_STREAMSIZEF_DESTINATION                  0x0001
#define ACM_FORMATSUGGESTF_WFORMATTAG                0x10000

/* ---- DRV_ family (2 names; R1) ---- */
#define DRV_OPEN                                     0x0003
#define DRV_CLOSE                                    0x0004

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms895512 ACMDM_DRIVER_ABOUT: documented name-only (no value published; held) */
/* ms895966 ACMDM_DRIVER_DETAILS: documented name-only (no value published; held) */
/* ms895983 ACMDM_DRIVER_NOTIFY: documented name-only (no value published; held) */
/* ms896075 ACMDM_FILTER_DETAILS: documented name-only (no value published; held) */
/* ms896077 ACMDM_FILTERTAG_DETAILS: documented name-only (no value published; held) */
/* ms896078 ACMDM_FORMAT_DETAILS: documented name-only (no value published; held) */
/* ms896079 ACMDM_FORMAT_SUGGEST: documented name-only (no value published; held) */
/* ms896080 ACMDM_FORMATTAG_DETAILS: documented name-only (no value published; held) */
/* ms896081 ACMDM_HARDWARE_WAVE_CAPS_INPUT: documented name-only (no value published; held) */
/* ms896082 ACMDM_HARDWARE_WAVE_CAPS_OUTPUT: documented name-only (no value published; held) */
/* ms896083 ACMDM_STREAM_CLOSE: documented name-only (no value published; held) */
/* ms896084 ACMDM_STREAM_CONVERT: documented name-only (no value published; held) */
/* ms896085 ACMDM_STREAM_OPEN: documented name-only (no value published; held) */
/* ms896086 ACMDM_STREAM_PREPARE: documented name-only (no value published; held) */
/* ms896087 ACMDM_STREAM_RESET: documented name-only (no value published; held) */
/* ms896088 ACMDM_STREAM_SIZE: documented name-only (no value published; held) */
/* ms896089 ACMDM_STREAM_UNPREPARE: documented name-only (no value published; held) */
#endif /* AKARI_MSACMDRV_H */
