/*
 * Nled.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-nled.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_NLED_H
#define AKARI_NLED_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-nled (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-nled (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-nled (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms905297 NLED_COUNT_INFO: prototype printed by the page; derived at the M99 sweep. */
typedef struct NLED_COUNT_INFO {
    UINT cLeds;
} NLED_COUNT_INFO;

/* ms905326 NLED_SETTINGS_INFO: prototype printed by the page; derived at the M99 sweep. */
typedef struct NLED_SETTINGS_INFO {
    UINT LedNum;
    INT OffOnBlink;
    LONG TotalCycleTime;
    LONG OnTime;
    LONG OffTime;
    INT MetaCycleOn;
    INT MetaCycleOff;
} NLED_SETTINGS_INFO;

/* ms905332 NLED_SUPPORTS_INFO: prototype printed by the page; derived at the M99 sweep. */
typedef struct NLED_SUPPORTS_INFO {
    UINT LedNum;
    LONG lCycleAdjust;
    BOOL fAdjustTotalCycleTime;
    BOOL fAdjustOnTime;
    BOOL fAdjustOffTime;
    BOOL fMetaCycleOn;
    BOOL fMetaCycleOff;
} NLED_SUPPORTS_INFO;

#ifdef __cplusplus
}
#endif

#endif /* AKARI_NLED_H */
