/*
 * Not applicable.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): core-system-management-reference.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_NOT APPLICABLE_H
#define AKARI_NOT APPLICABLE_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: core-system-management-reference (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa450984 VS_VERSIONINFO (page print, compiled) */
typedef struct  {
    WORD wLength;
    WORD wValueLength;
    WORD wType;
    WCHAR szKey[];
    WORD Padding1[];
    VS_FIXEDFILEINFO Value;
    WORD Padding2[];
    WORD Children[];
} VS_VERSIONINFO;
/* aa450909 StringFileInfo -- HELD (page print; member types unpublished):
 *   typedef struct StringFileInfo { ... } StringFileInfo; */
/* aa450911 StringTable -- HELD (page print; member types unpublished):
 *   typedef struct StringTable { ... } StringTable; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_NOT APPLICABLE_H */
