/*
 * PCIbus.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-pci.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PCIBUS_H
#define AKARI_PCIBUS_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-pci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919386 PCI_DEV_INFO -- HELD (page print; member types unpublished):
 *   typedef struct _PCI_DEV_INFO { ... } PCI_DEV_INFO, *PPCI_DEV_INFO; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PCIBUS_H */
