/*
 * PCIReg.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-pci.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PCIREG_H
#define AKARI_PCIREG_H

#include "CEDDK.h"     /* BUS_DATA_TYPE (PCIReg structure members) */

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-pci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896150 BUSDATA_PARMS (page print, compiled) */
typedef struct BUSDATA_PARMS {
    DWORD Function;
    ULONG ReturnCode;
    BUS_DATA_TYPE BusDataType;
    ULONG BusNumber;
    ULONG SlotNumber;
    PVOID Buffer;
    ULONG Offset;
    ULONG Length;
} BUSDATA_PARMS, *PBUSDATA_PARMS;
/* ms919389 PCI_REG_INFO -- HELD (page print; member types unpublished):
 *   typedef struct _PCI_REG_INFO { ... } PCI_REG_INFO, *PPCI_REG_INFO; */
/* ms919390 PCI_REG_LIST -- HELD (page print; member types unpublished):
 *   typedef struct _PCI_REG_LIST { ... } PCI_REG_LIST, *PPCI_REG_LIST; */
/* ms919387 PCIInitInfo: print `void PCIInitInfo(LPCWSTR RegPath,DWORD Bus,DWORD Device,DWORD Function,DWORD SysIntr,PPCI_COMMON_CONFIG pCfg,PPCI_REG_INFO pInfo);` */
/* (record-only: parameter or return type unpublished) */
/* ms919388 PCIReg: print `BOOL PCIReg(PPCI_REG_INFO pInfo);` */
/* (record-only: parameter or return type unpublished) */

/* ------------------------------------------------------------------
 * Book surface: drivers-pci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447684 ConfigInit: print `static BOOL ConfigInit(PPCI_DEV_INFO pInfo);` */
/* (record-only: parameter or return type unpublished) */
/* aa447685 ConfigRsrc: print `static BOOL ConfigRsrc(PPCI_DEV_INFO pInfo,PPCI_RSRC pMemHead,PPCI_RSRC pIoHead,DWORD* pMemSize,DWORD* pIoSize);` */
/* (record-only: parameter or return type unpublished) */
/* aa447686 ConfigSet: print `static BOOL ConfigSet(PPCI_RSRC pRsrc);` */
/* (record-only: parameter or return type unpublished) */
/* aa447687 ConfigSize: print `static BOOL ConfigSize(PPCI_DEV_INFO pInfo);` */
/* (record-only: parameter or return type unpublished) */
/* ms923768 Enabling the PCI Bus Driver */
/* aa447537 PCI Bus Configuration and Enumeration */
/* aa447541 PCI Bus Driver Registry Settings */
/* aa447542 PCI Bus Driver Samples */
/* ms894036 Step 1: Loading the PCI Bus Driver */
/* ms894037 Step 2: Enumerating Devices on the PCI Bus */
/* ms894038 Step 3: Enumerating a PCI Serial Driver */
/* ms894039 Step 4: Enumerating a PCI Ethernet Controller Driver */
/* ms894040 Step 5: Loading Drivers on the PCI Bus */

/* ------------------------------------------------------------------
 * Book surface: drivers-pci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923768 Enabling the PCI Bus Driver */
/* aa447537 PCI Bus Configuration and Enumeration */
/* aa447541 PCI Bus Driver Registry Settings */
/* aa447542 PCI Bus Driver Samples */
/* ms894036 Step 1: Loading the PCI Bus Driver */
/* ms894037 Step 2: Enumerating Devices on the PCI Bus */
/* ms894038 Step 3: Enumerating a PCI Serial Driver */
/* ms894039 Step 4: Enumerating a PCI Ethernet Controller Driver */
/* ms894040 Step 5: Loading Drivers on the PCI Bus */

/* ------------------------------------------------------------------
 * Book surface: drivers-pci (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923768 Enabling the PCI Bus Driver */
/* aa447537 PCI Bus Configuration and Enumeration */
/* aa447541 PCI Bus Driver Registry Settings */
/* aa447542 PCI Bus Driver Samples */
/* ms894036 Step 1: Loading the PCI Bus Driver */
/* ms894037 Step 2: Enumerating Devices on the PCI Bus */
/* ms894038 Step 3: Enumerating a PCI Serial Driver */
/* ms894039 Step 4: Enumerating a PCI Ethernet Controller Driver */
/* ms894040 Step 5: Loading Drivers on the PCI Bus */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PCIREG_H */
