/*
 * Pegdser.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-serial.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PEGDSER_H
#define AKARI_PEGDSER_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-serial (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms920512 SERIAL_DEV_STATUS (page print, compiled) */
typedef struct _SERIAL_DEV_STATUS {
    DWORD Errors;
    COMSTAT ComStat;
} SERIAL_DEV_STATUS, *PSERIAL_DEV_STATUS;
/* ms920520 SERIAL_QUEUE_SIZES (page print, compiled) */
typedef struct _SERIAL_QUEUE_SIZES {
    DWORD cbInQueue;
    DWORD cbOutQueue;
} SERIAL_QUEUE_SIZES, *PSERIAL_QUEUE_SIZES;

/* ------------------------------------------------------------------
 * Book surface: drivers-serial (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-serial (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms901420 IOCTL_SERIAL_CLR_DTR: documented name-only (no value published; held) */
/* ms901421 IOCTL_SERIAL_CLR_RTS: documented name-only (no value published; held) */
/* ms901422 IOCTL_SERIAL_DISABLE_IR: documented name-only (no value published; held) */
/* ms901423 IOCTL_SERIAL_ENABLE_IR: documented name-only (no value published; held) */
/* ms901424 IOCTL_SERIAL_GET_COMMSTATUS: documented name-only (no value published; held) */
/* ms901425 IOCTL_SERIAL_GET_DCB: documented name-only (no value published; held) */
/* ms901426 IOCTL_SERIAL_GET_MODEMSTATUS: documented name-only (no value published; held) */
/* ms901427 IOCTL_SERIAL_GET_PROPERTIES: documented name-only (no value published; held) */
/* ms901428 IOCTL_SERIAL_GET_TIMEOUTS: documented name-only (no value published; held) */
/* ms901429 IOCTL_SERIAL_GET_WAIT_MASK: documented name-only (no value published; held) */
/* ms901430 IOCTL_SERIAL_IMMEDIATE_CHAR: documented name-only (no value published; held) */
/* ms901431 IOCTL_SERIAL_PURGE: documented name-only (no value published; held) */
/* ms901432 IOCTL_SERIAL_SET_BREAK_OFF: documented name-only (no value published; held) */
/* ms901433 IOCTL_SERIAL_SET_BREAK_ON: documented name-only (no value published; held) */
/* ms901434 IOCTL_SERIAL_SET_DCB: documented name-only (no value published; held) */
/* ms901435 IOCTL_SERIAL_SET_DTR: documented name-only (no value published; held) */
/* ms901436 IOCTL_SERIAL_SET_QUEUE_SIZE: documented name-only (no value published; held) */
/* ms901437 IOCTL_SERIAL_SET_RTS: documented name-only (no value published; held) */
/* ms901438 IOCTL_SERIAL_SET_TIMEOUTS: documented name-only (no value published; held) */
/* ms901439 IOCTL_SERIAL_SET_WAIT_MASK: documented name-only (no value published; held) */
/* ms901440 IOCTL_SERIAL_SET_XOFF: documented name-only (no value published; held) */
/* ms901441 IOCTL_SERIAL_SET_XON: documented name-only (no value published; held) */
/* ms901442 IOCTL_SERIAL_WAIT_ON_MASK: documented name-only (no value published; held) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PEGDSER_H */
