/*
 * Pegdser.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-serial.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PEGDSER_H
#define AKARI_PEGDSER_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-serial (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms920512 SERIAL_DEV_STATUS (page print, compiled) */
typedef struct _SERIAL_DEV_STATUS {
    DWORD Errors;
    COMSTAT ComStat;
} SERIAL_DEV_STATUS, *PSERIAL_DEV_STATUS;
/* ms920520 SERIAL_QUEUE_SIZES (page print, compiled) */
typedef struct _SERIAL_QUEUE_SIZES {
    DWORD cbInQueue;
    DWORD cbOutQueue;
} SERIAL_QUEUE_SIZES, *PSERIAL_QUEUE_SIZES;

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PEGDSER_H */
