/*
 * Pmimpl.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): powerman.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PMIMPL_H
#define AKARI_PMIMPL_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: powerman (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919405 PlatformDeviceListInit: print `BOOL WINAPI PlatformDeviceListInit(PDEVICE_LIST pdl);` */
/* (record-only: parameter or return type unpublished) */
/* ms919406 PlatformManageSystemPower: print `VOID WINAPI PlatformManageSystemPower(HANDLE hevReady);` */
AKARI_CE_IMPORT VOID WINAPI PlatformManageSystemPower(HANDLE hevReady)
    AKARI_CE_NAME(PlatformManageSystemPower);
/* ms919407 PlatformMapPowerStateHint: print `DWORD WINAPI PlatformMapPowerStateHint(DWORD dwHint, LPSTR pszBuf, DWORD dwBufChars);` */
AKARI_CE_IMPORT DWORD WINAPI PlatformMapPowerStateHint(DWORD dwHint, LPSTR pszBuf, DWORD dwBufChars)
    AKARI_CE_NAME(PlatformMapPowerStateHint);
/* ms919408 PlatformResumeSystem: print `VOID WINAPI PlatformResumeSystem(void);` */
AKARI_CE_IMPORT VOID WINAPI PlatformResumeSystem(void)
    AKARI_CE_NAME(PlatformResumeSystem);
/* ms919409 PlatformSendInitialNotifications: print `VOID PlatformSendInitialNotifications(PPOWER_NOTIFICATION ppn, DWORD dwFlags);` */
/* (record-only: parameter or return type unpublished) */
/* ms919410 PlatformSetSystemPowerState: print `DWORD WINAPI PlatformSetSystemPowerState(LPCSTSTR pszName, BOOL fForce, BOOL fInternal);` */
/* (record-only: parameter or return type unpublished) */
/* ms919660 PlatformValidatePMRegistry: print `DWORD WINAPI PlatformValidatePMRegistry(void);` */
AKARI_CE_IMPORT DWORD WINAPI PlatformValidatePMRegistry(void)
    AKARI_CE_NAME(PlatformValidatePMRegistry);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PMIMPL_H */
