/* pnrpdef.h -- PNRP definitions (Windows CE 5.0+; p2p.lib rows).
 * Pages: tools/manifests/servers.manifest (Peer-to-Peer node).
 * See docs/inventory.md M75d. */

#ifndef AKARI_PNRPDEF_H
#define AKARI_PNRPDEF_H

/* ms896278 "PNRP_CLOUD_FLAGS": print `typedef enum {
 * PNRP_CLOUD_NO_FLAGS, PNRP_CLOUD_NAME_LOCAL} PNRP_CLOUD_FLAGS;` */
typedef enum {
    PNRP_CLOUD_NO_FLAGS,
    PNRP_CLOUD_NAME_LOCAL
} PNRP_CLOUD_FLAGS;

/* ms896280 "PNRP_CLOUD_STATE": print `typedef enum {
 * PNRP_CLOUD_STATE_VIRTUAL, PNRP_CLOUD_STATE_SYNCHRONISING,
 * PNRP_CLOUD_STATE_ACTIVE, PNRP_CLOUD_STATE_DEAD,
 * PNRP_CLOUD_STATE_DISABLED, PNRP_CLOUD_STATE_NO_NET,
 * PNRP_CLOUD_STATE_ALONE} PNRP_CLOUD_STATE;` */
typedef enum {
    PNRP_CLOUD_STATE_VIRTUAL,
    PNRP_CLOUD_STATE_SYNCHRONISING,
    PNRP_CLOUD_STATE_ACTIVE,
    PNRP_CLOUD_STATE_DEAD,
    PNRP_CLOUD_STATE_DISABLED,
    PNRP_CLOUD_STATE_NO_NET,
    PNRP_CLOUD_STATE_ALONE
} PNRP_CLOUD_STATE;

/* ms896281 "PNRP_RESOLVE_CRITERIA": print `typedef enum {
 * PNRP_RESOLVE_CRITERIA_DEFAULT, PNRP_RESOLVE_CRITERIA_ANY_PEER_NAME,
 * PNRP_RESOLVE_CRITERIA_NEAREST_NON_CURRENT_PROCESS_PEER_NAME,
 * PNRP_RESOLVE_CRITERIA_NEAREST_PEER_NAME,
 * PNRP_RESOLVE_CRITERIA_NEAREST_REMOTE_PEER_NAME,
 * PNRP_RESOLVE_CRITERIA_NON_CURRENT_PROCESS_PEER_NAME,
 * PNRP_RESOLVE_CRITERIA_REMOTE_PEER_NAME} PNRP_RESOLVE_CRITERIA;` */
typedef enum {
    PNRP_RESOLVE_CRITERIA_DEFAULT,
    PNRP_RESOLVE_CRITERIA_ANY_PEER_NAME,
    PNRP_RESOLVE_CRITERIA_NEAREST_NON_CURRENT_PROCESS_PEER_NAME,
    PNRP_RESOLVE_CRITERIA_NEAREST_PEER_NAME,
    PNRP_RESOLVE_CRITERIA_NEAREST_REMOTE_PEER_NAME,
    PNRP_RESOLVE_CRITERIA_NON_CURRENT_PROCESS_PEER_NAME,
    PNRP_RESOLVE_CRITERIA_REMOTE_PEER_NAME
} PNRP_RESOLVE_CRITERIA;

#endif /* AKARI_PNRPDEF_H */
