/*
 * Prnport.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-printer.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PRNPORT_H
#define AKARI_PRNPORT_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-printer (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899310 GetPrinterInfo: print `DWORD WINAPI GetPrinterInfo(HANDLE hPrint,DWORDdwOption,PVOID pBuff,PDWORD pBuffLen);` */
DWORD WINAPI GetPrinterInfo(HANDLE hPrint, DWORD dwOption, PVOID pBuff, PDWORD pBuffLen);
/* ms919683 PrinterClose: print `VOID WINAPI PrinterClose(HANDLE hPrint);` */
VOID WINAPI PrinterClose(HANDLE hPrint);
/* ms919686 PrinterOpen: print `HANDLE WINAPI PrinterOpen(PWSTR sPort);` */
HANDLE WINAPI PrinterOpen(PWSTR sPort);
/* ms919688 PrinterSend: print `BOOL WINAPI PrinterSend(HANDLE hPrint,LPCVOID lpBuffer,DWORDdwBytes);` */
BOOL WINAPI PrinterSend(HANDLE hPrint, LPCVOID lpBuffer, DWORD dwBytes);
/* ms919830 ReportPrinterStatus: print `` */
/* (record-only: parameter or return type unpublished) */

/* ------------------------------------------------------------------
 * Book surface: drivers-printer (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447573 Print Spooling */
/* aa447568 Printer Driver Architecture */
/* aa447569 Printer Driver Migration */
/* aa447570 Printer Driver Registry Settings */
/* aa447572 Printer Driver Samples */

/* ------------------------------------------------------------------
 * Book surface: drivers-printer (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447573 Print Spooling */
/* aa447568 Printer Driver Architecture */
/* aa447569 Printer Driver Migration */
/* aa447570 Printer Driver Registry Settings */
/* aa447572 Printer Driver Samples */

/* ------------------------------------------------------------------
 * Book surface: drivers-printer (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447573 Print Spooling */
/* aa447568 Printer Driver Architecture */
/* aa447569 Printer Driver Migration */
/* aa447570 Printer Driver Registry Settings */
/* aa447572 Printer Driver Samples */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PRNPORT_H */
