/*
 * Proxy.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-usbfn.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PROXY_H
#define AKARI_PROXY_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-usbfn (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448150 STORE_ExecuteCommand: print `DWORD STORE_ExecuteCommand( PTRANSPORT_COMMAND ptcCommand, PTRANSPORT_DATA ptdData);` */
/* (record-only: parameter or return type unpublished) */
/* aa448151 STORE_IsCommandSupported: print `BOOL STORE_IsCommandSupported( PTRANSPORT_COMMAND ptcCommand, PBOOL pfDataStageRequired, PDWORD pdwDirection, PDWORD pdwDataSize);` */
/* (record-only: parameter or return type unpublished) */

/* ------------------------------------------------------------------
 * Book surface: drivers-usbfn (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448275 Optimizing a USB Function Driver Stack */
/* aa448278 Porting a USB Function Controller Driver */
/* aa448298 USB Function Client Driver Functions */
/* ms895481 USB Function Client Driver Registry Settings */
/* ms894091 USB Function Controller Driver Bus Interface */
/* ms894094 USB Function Controller Driver MDD */
/* ms894095 USB Function Controller Driver MDD and DDI Interface */
/* ms894096 USB Function Controller Driver PDD */
/* ms894097 USB Function Controller Driver PDD and DDSI Interface */
/* ms894093 USB Function Controller Driver Samples */
/* ms894098 USB Function Controller Driver Transfers */
/* ms923251 USB Function Controller MDD Functions */
/* ms895475 USB Function Controller MDD IOCTLs */
/* ms923252 USB Function Controller PDD Functions */
/* ms894319 USB Function Mass Storage Client Driver Configuration and Implementation */
/* ms894325 USB Function Mass Storage Client Driver Execution Sequence */
/* ms894323 USB Function Mass Storage Client Driver Samples */
/* ms894330 USB Function Mass Storage Client Driver SCSI-2 Command Support */
/* ms894345 USB Function Mass Storage Client Driver SCSI-2 Direct-Access Device Emulator */
/* ms894347 USB Function Mass Storage Client Driver Transport */
/* aa448290 USB Function Serial Client Driver Samples */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PROXY_H */
