/*
 * Pwingdi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-display.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_PWINGDI_H
#define AKARI_PWINGDI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923267 VIDEO_POWER_MANAGEMENT -- HELD (page print; member types unpublished):
 *   typedef struct VIDEOPOWER_MANAGEMENT { ... } VIDEO_POWER_MANAGEMENT, * PVIDEO_POWER_MANAGEMENT; */

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447689 ContrastCmdInputParm: documented name-only (no value published; held) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_PWINGDI_H */
