/*
 * Rapitypes.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): activesync.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_RAPITYPES_H
#define AKARI_RAPITYPES_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms879804 RAPI_CONNECTIONTYPE (RAPI) (page print, compiled) */
typedef enum  {
    RAPI_CONNECTION_USB = 0,
    RAPI_CONNECTION_IR = 1,
    RAPI_CONNECTION_SERIAL = 2,
    RAPI_CONNECTION_NETWORK = 3
} RAPI_CONNECTIONTYPE;
/* ms879807 RAPI_DEVICE_PLATFORM (RAPI) (page print, compiled) */
typedef struct  {
    BSTR bstrName;
    DWORD dwMajor;
    DWORD dwMinor;
} RAPI_DEVICE_PLATFORM;
/* ms879806 RAPI_DEVICESTATUS (RAPI) (page print, compiled) */
typedef enum  {
    RAPI_DEVICE_DISCONNECTED = 0,
    RAPI_DEVICE_CONNECTED = 1
} RAPI_DEVICESTATUS;
/* ms879802 RAPISTREAMFLAG (RAPI) (page print, compiled) */
typedef enum tagRAPISTREAMFLAG {
    STREAM_TIMEOUT_READ
} RAPISTREAMFLAG;
/* ms879803 RAPI_CONNECTIONINFO (RAPI) -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } RAPI_CONNECTIONINFO; */
/* ms879805 RAPI_DEVICEINFO (RAPI) -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } RAPI_DEVICEINFO; */
/* ms879808 RAPI_GETDEVICEOPCODE (RAPI) -- HELD (page print; member types unpublished):
 *   typedef enum  { ... } RAPI_GETDEVICEOPCODE; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_RAPITYPES_H */
