/*
 * Rapi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): activesync.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_RAPI_H
#define AKARI_RAPI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct IRAPIStream IRAPIStream;   /* opaque carrier (layout unpublished) */
/* aa513350 CE_FIND_DATA (page print, compiled) */
typedef struct _CE_FIND_DATA {
    DWORD dwFileAttributes;
    FILETIME ftCreationTime;
    FILETIME ftLastAccessTime;
    FILETIME ftLastWriteTime;
    DWORD nFileSizeHigh;
    DWORD nFileSizeLow;
    DWORD dwOID;
    WCHAR cFileName[MAX_PATH];
} CE_FIND_DATA;
/* aa513381 CEOSVERSIONINFO (page print, compiled) */
typedef struct _CEOSVERSIONINFO {
    DWORD dwOSVersionInfoSize;
    DWORD dwMajorVersion;
    DWORD dwMinorVersion;
    DWORD dwBuildNumber;
    DWORD dwPlatformId;
    WCHAR szCSDVersion[128];
} CEOSVERSIONINFO, *LPCEOSVERSIONINFO;
/* aa514430 RAPIINIT (page print, compiled) */
typedef struct _RAPIINIT {
    DWORD cbSize;
    HANDLE heRapiInit;
    HRESULT hrRapiInit;
} RAPIINIT;
/* aa513323 CeCheckPassword (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeCheckPassword(LPWSTR lpszPassword)
    AKARI_CE_NAME(CeCheckPassword);
/* aa513324 CeCloseHandle (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeCloseHandle(HANDLE hObject)
    AKARI_CE_NAME(CeCloseHandle);
/* aa513325 CeCopyFile (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeCopyFile(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName, BOOL bFailIfExists)
    AKARI_CE_NAME(CeCopyFile);
/* aa513328 CeCreateDirectory (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeCreateDirectory(LPCWSTR lpPathName, LPSECURITY_ATTRIBUTES lpSecurityAttributes)
    AKARI_CE_NAME(CeCreateDirectory);
/* aa513329 CeCreateFile (RAPI): print `` */
/* (record-only: parameter or return type unpublished) */
/* aa513340 CeCreateProcess (RAPI): print `` */
/* (record-only: parameter or return type unpublished) */
/* aa513344 CeDeleteFile (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeDeleteFile(LPCWSTR lpFileName)
    AKARI_CE_NAME(CeDeleteFile);
/* aa513347 CeFindAllDatabases (RAPI): print `` -- recorded verbatim (no compiled prototype) */
/* aa513348 CeFindAllFiles (RAPI): print `` -- recorded verbatim (no compiled prototype) */
/* aa513349 CeFindClose (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeFindClose(HANDLE hFindFile)
    AKARI_CE_NAME(CeFindClose);
/* aa513353 CeFindFirstFile (RAPI): print `` -- recorded verbatim (no compiled prototype) */
/* aa513356 CeFindNextFile (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeFindNextFile(HANDLE hFindFile, LPWIN32_FIND_DATA lpFindFileData)
    AKARI_CE_NAME(CeFindNextFile);
/* aa513357 CeGetClassName (RAPI): print `` */
AKARI_CE_IMPORT int CeGetClassName(HWND hWnd, LPTSTR lpClassName, int nMaxCount)
    AKARI_CE_NAME(CeGetClassName);
/* aa513358 CeGetDesktopDeviceCaps (RAPI): print `` */
AKARI_CE_IMPORT INT CeGetDesktopDeviceCaps(INT nIndex)
    AKARI_CE_NAME(CeGetDesktopDeviceCaps);
/* aa513359 CeGetFileAttributes (RAPI): print `` */
AKARI_CE_IMPORT DWORD CeGetFileAttributes(LPCWSTR lpFileName)
    AKARI_CE_NAME(CeGetFileAttributes);
/* aa513360 CeGetFileSize (RAPI): print `` */
AKARI_CE_IMPORT DWORD CeGetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh)
    AKARI_CE_NAME(CeGetFileSize);
/* aa513361 CeGetFileTime (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeGetFileTime(HANDLE hFile, LPFILETIME lpCreationTime, LPFILETIME lpLastAccessTime, LPFILETIME lpLastWriteTime)
    AKARI_CE_NAME(CeGetFileTime);
/* aa513362 CeGetLastError (RAPI): print `` */
AKARI_CE_IMPORT DWORD CeGetLastError(void)
    AKARI_CE_NAME(CeGetLastError);
/* aa513364 CeGetSpecialFolderPath (RAPI): print `` */
AKARI_CE_IMPORT DWORD CeGetSpecialFolderPath(int nFolder, DWORD nBufferLength, LPWSTR lpBuffer)
    AKARI_CE_NAME(CeGetSpecialFolderPath);
/* aa513365 CeGetStoreInformation (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeGetStoreInformation(LPSTORE_INFORMATION lpsi)
    AKARI_CE_NAME(CeGetStoreInformation);
/* aa513367 CeGetSystemMetrics (RAPI): print `` */
AKARI_CE_IMPORT int CeGetSystemMetrics(int nIndex)
    AKARI_CE_NAME(CeGetSystemMetrics);
/* aa513368 CeGetSystemPowerStatusEx (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeGetSystemPowerStatusEx(PSYSTEM_POWER_STATUS_EX pstatus, BOOL fUpdate)
    AKARI_CE_NAME(CeGetSystemPowerStatusEx);
/* aa513369 CeGetTempPath (RAPI): print `` */
AKARI_CE_IMPORT DWORD CeGetTempPath(DWORD nBufferLength, LPWSTR lpBuffer)
    AKARI_CE_NAME(CeGetTempPath);
/* aa513370 CeGetVersionEx (RAPI): print `` -- recorded verbatim (no compiled prototype) */
/* aa513372 CeGetWindow (RAPI): print `` */
AKARI_CE_IMPORT HWND CeGetWindow(HWND hWnd, UINT uCmd)
    AKARI_CE_NAME(CeGetWindow);
/* aa513371 CeGetWindowLong (RAPI): print `` */
AKARI_CE_IMPORT LONG CeGetWindowLong(HWND hWnd, int nIndex)
    AKARI_CE_NAME(CeGetWindowLong);
/* aa513373 CeGetWindowText (RAPI): print `` */
AKARI_CE_IMPORT int CeGetWindowText(HWND hWnd, LPWSTR lpString, int nMaxCount)
    AKARI_CE_NAME(CeGetWindowText);
/* aa513374 CeGlobalMemoryStatus (RAPI): print `` */
AKARI_CE_IMPORT void CeGlobalMemoryStatus(LPMEMORYSTATUS lpmst)
    AKARI_CE_NAME(CeGlobalMemoryStatus);
/* aa513376 CeMoveFile (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeMoveFile(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName)
    AKARI_CE_NAME(CeMoveFile);
/* ms879800 CeQueryInstructionSet (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeQueryInstructionSet(DWORD dwInstructionSet, LPDWORD lpdwCurrentInstructionSet)
    AKARI_CE_NAME(CeQueryInstructionSet);
/* aa513382 CeRapiFreeBuffer: print `` -- recorded verbatim (no compiled prototype) */
/* aa513383 CeRapiGetError: print `HRESULT CeRapiGetError(void);` */
AKARI_CE_IMPORT HRESULT CeRapiGetError(void)
    AKARI_CE_NAME(CeRapiGetError);
/* aa513384 CeRapiInit: print `` */
AKARI_CE_IMPORT HRESULT CeRapiInit(void)
    AKARI_CE_NAME(CeRapiInit);
/* aa513385 CeRapiInitEx: print `` */
AKARI_CE_IMPORT HRESULT CeRapiInitEx(RAPIINIT* pRapiInit)
    AKARI_CE_NAME(CeRapiInitEx);
/* aa513386 CeRapiInvoke: print `HRESULT CeRapiInvoke( LPCWSTRpDllPath,LPCWSTRpFunctionName,DWORDcbInput, BYTE* pInput,DWORD* pcbOutput,BYTE** ppOutput,IRAPIStream** ppIRAPIStream,DWORD dwReserved);` */
AKARI_CE_IMPORT HRESULT CeRapiInvoke(LPCWSTR pDllPath, LPCWSTR pFunctionName, DWORD cbInput, BYTE* pInput, DWORD* pcbOutput, BYTE* ppOutput, IRAPIStream* ppIRAPIStream, DWORD dwReserved)
    AKARI_CE_NAME(CeRapiInvoke);
/* aa513387 CeRapiUninit: print `` */
AKARI_CE_IMPORT HRESULT CeRapiUninit(void)
    AKARI_CE_NAME(CeRapiUninit);
/* aa513388 CeReadFile (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped)
    AKARI_CE_NAME(CeReadFile);
/* aa513391 CeRegCloseKey (RAPI): print `` */
AKARI_CE_IMPORT LONG CeRegCloseKey(HKEY hKey)
    AKARI_CE_NAME(CeRegCloseKey);
/* aa513392 CeRegCreateKeyEx (RAPI): print `` -- recorded verbatim (no compiled prototype) */
/* aa513393 CeRegDeleteKey (RAPI): print `` */
AKARI_CE_IMPORT LONG CeRegDeleteKey(HKEY hKey, LPCWSTR lpszSubKey)
    AKARI_CE_NAME(CeRegDeleteKey);
/* aa513394 CeRegDeleteValue (RAPI): print `` */
AKARI_CE_IMPORT LONG CeRegDeleteValue(HKEY hKey, LPCWSTR lpszValueName)
    AKARI_CE_NAME(CeRegDeleteValue);
/* aa513395 CeRegEnumKeyEx (RAPI): print `` */
AKARI_CE_IMPORT LONG CeRegEnumKeyEx(HKEY hKey, DWORD dwIndex, LPWSTR lpName, LPDWORD lpcbName, LPDWORD lpReserved, LPWSTR lpClass, LPDWORD lpcbClass, PFILETIME lpftLastWriteTime)
    AKARI_CE_NAME(CeRegEnumKeyEx);
/* aa513396 CeRegEnumValue (RAPI): print `` */
AKARI_CE_IMPORT LONG CeRegEnumValue(HKEY hKey, DWORD dwIndex, LPWSTR lpszValueName, LPDWORD lpcbValueName, LPDWORD lpReserved, LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData)
    AKARI_CE_NAME(CeRegEnumValue);
/* aa513397 CeRegOpenKeyEx (RAPI): print `` */
AKARI_CE_IMPORT LONG CeRegOpenKeyEx(HKEY hKey, LPCWSTR lpszSubKey, DWORD ulOptions, REGSAM samDesired, PHKEY phkResult)
    AKARI_CE_NAME(CeRegOpenKeyEx);
/* aa513398 CeRegQueryInfoKey (RAPI): print `` */
AKARI_CE_IMPORT LONG CeRegQueryInfoKey(HKEY hKey, LPWSTR lpClass, LPDWORD lpcbClass, LPDWORD lpReserved, LPDWORD lpcSubKeys, LPDWORD lpcbMaxSubKeyLen, LPDWORD lpcbMaxClassLen, LPDWORD lpcValues, LPDWORD lpcbMaxValueNameLen, LPDWORD lpcbMaxValueLen, LPDWORD lpcbSecurityDescriptor, PFILETIME lpftLastWriteTime)
    AKARI_CE_NAME(CeRegQueryInfoKey);
/* aa513399 CeRegQueryValueEx (RAPI): print `` */
AKARI_CE_IMPORT LONG CeRegQueryValueEx(HKEY hKey, LPCWSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData)
    AKARI_CE_NAME(CeRegQueryValueEx);
/* aa513400 CeRegSetValueEx (RAPI): print `` -- recorded verbatim (no compiled prototype) */
/* aa513401 CeRemoveDirectory (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeRemoveDirectory(LPCWSTR lpPathName)
    AKARI_CE_NAME(CeRemoveDirectory);
/* aa513405 CeSetEndOfFile (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeSetEndOfFile(HANDLE hFile)
    AKARI_CE_NAME(CeSetEndOfFile);
/* aa513406 CeSetFileAttributes (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeSetFileAttributes(LPCWSTR lpFileName, DWORD dwFileAttributes)
    AKARI_CE_NAME(CeSetFileAttributes);
/* aa513810 CeSetFilePointer (RAPI): print `` */
AKARI_CE_IMPORT DWORD CeSetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod)
    AKARI_CE_NAME(CeSetFilePointer);
/* aa513813 CeSetFileTime (RAPI): print `` */
/* (record-only: parameter or return type unpublished) */
/* aa513814 CeSHCreateShortcut (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeSHCreateShortcut(LPWSTR lpszShortcut, LPWSTR lpszTarget)
    AKARI_CE_NAME(CeSHCreateShortcut);
/* aa513816 CeSHGetShortcutTarget (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeSHGetShortcutTarget(LPWSTR lpszShortcut, LPWSTR lpszTarget, int cbMax)
    AKARI_CE_NAME(CeSHGetShortcutTarget);
/* aa513847 CeWriteFile (RAPI): print `` */
AKARI_CE_IMPORT BOOL CeWriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped)
    AKARI_CE_NAME(CeWriteFile);
/* aa514340 IRAPIStream::GetRapiStat (Header: Rapi.h.) */
/* aa514342 IRAPIStream::SetRapiStat (Header: Rapi.h.) */

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa513308 Accessing Folders */
/* ms861126 Accessing Objects */
/* aa513311 ActiveSync Migration */
/* ms879784 ActiveSync Overview */
/* ms861144 ActiveSync Programming FAQ */
/* ms861160 ActiveSync Samples */
/* ms861176 ActiveSync Security */
/* aa514589 Adding Custom Menus to Windows CE Explorer */
/* ms861215 COM-Based Notification */
/* ms861226 Comparing Store Identifiers */
/* ms861235 Configuring the ActiveSync COM Components */
/* ms861269 Defining ActiveSync Objects */
/* ms861287 Desktop Computer Registry Settings */
/* ms861294 Desktop Registry Structure */
/* ms861304 Detecting Changes to Desktop Objects */
/* ms861313 Detecting Device Object Changes */
/* ms861416 Device Registry Settings */
/* ms861429 Enabling or Disabling a Service Provider in a New Partnership */
/* ms861466 Enumerating Device Objects */
/* ms861472 Enumerating Objects */
/* ms861476 Enumerating Objects with the FindObjects Function */
/* ms861484 Establishing an ActiveSync Desktop-Device Partnership */
/* ms861491 Examples of CEUTIL Functions */
/* ms861541 Generating a Class Identifier for the Filter */
/* ms861549 Handling and Displaying Service-Provider Errors */
/* ms861565 Handling Errors that Halt Synchronization */
/* ms861575 Handling Initialization Errors */
/* ms861590 Handling Synchronization Errors */
/* ms861598 Implementing a Dummy File Filter */
/* ms861622 Implementing the Device Functions */
/* aa514725 Important End-user Notification for ActiveSync */
/* ms861652 Initializing the Device Store */
/* ms861657 Initializing the Store */
/* ms861670 Managing the Summary and Details Panes */
/* ms861690 Prompting Users for Information During Synchronization */
/* ms861695 Prompting Users for Settings During Setup */
/* ms861741 Registering a File Extension Type */
/* ms861749 Registering a File Filter */
/* ms861753 Registering File Types and File Filters */
/* ms861756 Registering the Service Provider */
/* ms861759 Registry-Based Notification */
/* ms861772 Resolving Conflicts */
/* ms861781 Sending and Receiving Data with the SyncData Function */
/* ms861790 Setting Synchronization Options */
/* ms861786 Settings Dialog Box Specifications */
/* ms861795 Steps in Developing ActiveSync Providers */
/* ms861821 Understanding Partnerships */
/* ms861825 Understanding Service Providers */
/* ms861830 Understanding the ActiveSync Manager's Role */
/* ms861834 User-Interface Elements */
/* aa513061 Using RAPI Calls in a File Filter */
/* aa513303 Windows CE-based Device Notification */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_RAPI_H */
