/*
 * Replfilt.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): activesync.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_REPLFILT_H
#define AKARI_REPLFILT_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: activesync (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa513853 CFF_CONVERTOPTIONS (page print, compiled) */
typedef struct tagCFF_CONVERTOPTIONS {
    ULONG cbSize;
    BOOL bNoModalUI;
} CFF_CONVERTOPTIONS;
/* aa513851 CFF_CONVERTINFO -- HELD (page print; member types unpublished):
 *   typedef struct tagCFF_CONVERTINFO { ... } CFF_CONVERTINFO; */
/* aa513854 CFF_DESTINATIONFILE -- HELD (page print; member types unpublished):
 *   typedef struct tagCFF_DESTINATIONFILE { ... } CFF_DESTINATIONFILE; */
/* aa513855 CFF_SOURCEFILE -- HELD (page print; member types unpublished):
 *   typedef struct tagCFF_SOURCEFILE { ... } CFF_SOURCEFILE; */
/* aa514424 PFF_CONVERTINFO -- HELD (page print; member types unpublished):
 *   typedef struct tagPFF_CONVERTINFO { ... } PFF_CONVERTINFO; */
/* aa514427 PFF_DESTINATIONFILE -- HELD (page print; member types unpublished):
 *   typedef struct tagPFF_DESTINATIONFILE { ... } PFF_DESTINATIONFILE; */
/* aa514428 PFF_SOURCEFILE -- HELD (page print; member types unpublished):
 *   typedef struct tagPFF_SOURCEFILE { ... } PFF_SOURCEFILE; */
/* aa513873 ICeFileFilter::FilterOptions (Header: Replfilt.h.) */
/* aa513875 ICeFileFilter::FormatMessage (Header: Replfilt.h.) */
/* aa513877 ICeFileFilter::NextConvertFile (Header: Replfilt.h.) */
/* aa513881 ICeFileFilterOptions::SetFilterOptions (Header: Replfilt.h.) */
/* aa513882 ICeFileFilterSite::CloseDestinationFile (Header: Replfilt.h.) */
/* aa513883 ICeFileFilterSite::CloseSourceFile (Header: Replfilt.h.) */
/* aa513886 ICeFileFilterSite::OpenDestinationFile (Header: Replfilt.h.) */
/* aa513890 ICeFileFilterSite::OpenSourceFile (Header: Replfilt.h.) */
/* aa513891 ICeFileFilterSite::ReportLoss (Header: Replfilt.h.) */
/* aa513893 ICeFileFilterSite::ReportProgress (Header: Replfilt.h.) */
/* aa514316 IPegasusFileFilter::FilterOptions (Header: Replfilt.h.) */
/* aa514319 IPegasusFileFilter::FormatMessage (Header: Replfilt.h.) */
/* aa514323 IPegasusFileFilter::NextConvertFile (Header: Replfilt.h.) */
/* aa514325 IPegasusFileFilterSite::CloseDestinationFile (Header: Replfilt.h.) */
/* aa514327 IPegasusFileFilterSite::CloseSourceFile (Header: Replfilt.h.) */
/* aa514331 IPegasusFileFilterSite::OpenDestinationFile (Header: Replfilt.h.) */
/* aa514332 IPegasusFileFilterSite::OpenSourceFile (Header: Replfilt.h.) */
/* aa514335 IPegasusFileFilterSite::ReportLoss (Header: Replfilt.h.) */
/* aa514336 IPegasusFileFilterSite::ReportProgress (Header: Replfilt.h.) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_REPLFILT_H */
