/*
 * Sapiddk.h -- documented include-name alias for sapi.h.
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * The CE-era Requirements rows print "Header: Sapiddk.h" (120 pages);
 * SAPI engine-side DDI interface records are carried in sapi.h (M68).  This project carries the declarations in sapi.h; on a
 * case-sensitive filesystem (the LLVM-WinCE cross toolchain) this
 * alias keeps #include <Sapiddk.h> compiling.  NOTE: a case-insensitive
 * checkout (Windows) would collide Sapiddk.h with sapi.h -- see
 * docs/inventory.md (header-name compatibility unit).
 */

#include "Sapi.h"/* ------------------------------------------------------------------
 * Book surface: sapi (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms897368 _ISpPrivateEngineCall (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms897369 _ISpPrivateEngineCall::CallEngine (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms897370 _ISpPrivateEngineCall::CallEngineEx (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886319 ISpCFGInterpreter::InitGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886330 ISpCFGInterpreter::Interpret (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886356 ISpCFGInterpreterSite::AddProperty (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886366 ISpCFGInterpreterSite::AddTextReplacement (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886462 ISpCFGInterpreterSite::GetResourceValue (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886840 ISpErrorLog::AddError (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886849 ISpGramCompBackend::InitFromBinaryGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886850 ISpGramCompBackend::SetSaveObjects (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886861 ISpGrammarCompiler::CompileStream (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886863 ISpITNProcessor::ITNPhrase (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886864 ISpITNProcessor::LoadITNGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886911 ISpObjectTokenEnumBuilder::AddTokens (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886912 ISpObjectTokenEnumBuilder::AddTokensFromDataKey (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886913 ISpObjectTokenEnumBuilder::AddTokensFromTokenEnum (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886914 ISpObjectTokenEnumBuilder::SetAttribs (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886915 ISpObjectTokenEnumBuilder::Sort (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517314 ISpSRAlternates::Commit (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517315 ISpSRAlternates::GetAlternates (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517319 ISpSREngine::GetInputAudioFormat (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517320 ISpSREngine::GetPropertyNum (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517322 ISpSREngine::GetPropertyString (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517323 ISpSREngine::IsPronounceable (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517324 ISpSREngine::LoadProprietaryGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517325 ISpSREngine::LoadSLM (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517326 ISpSREngine::OnCreateGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517327 ISpSREngine::OnCreateRecoContext (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517328 ISpSREngine::OnDeleteGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517329 ISpSREngine::OnDeleteRecoContext (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517330 ISpSREngine::PrivateCall (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887490 ISpSREngine::PrivateCallEx (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887546 ISpSREngine::RecognizeStream (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887553 ISpSREngine::RuleNotify (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887556 ISpSREngine::SetAdaptationData (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887564 ISpSREngine::SetContextState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887567 ISpSREngine::SetGrammarState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887573 ISpSREngine::SetPropertyNum (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887576 ISpSREngine::SetPropertyString (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887580 ISpSREngine::SetProprietaryRuleIdState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887584 ISpSREngine::SetProprietaryRuleState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887589 ISpSREngine::SetRecoProfile (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887595 ISpSREngine::SetSite (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887603 ISpSREngine::SetSLMState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887608 ISpSREngine::SetTextSelection (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887616 ISpSREngine::SetWordSequenceData (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889616 ISpSREngine::UnloadProprietaryGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889623 ISpSREngine::UnloadSLM (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889630 ISpSREngine::WordNotify (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887828 ISpSREngineSite::AddEvent (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887927 ISpSREngineSite::DataAvailable (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887940 ISpSREngineSite::GetContextMaxAlternates (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887951 ISpSREngineSite::GetMaxAlternates (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887966 ISpSREngineSite::GetResource (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887975 ISpSREngineSite::GetRuleInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887988 ISpSREngineSite::GetStateInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887998 ISpSREngineSite::GetTransitionProperty (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889010 ISpSREngineSite::GetWordInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889018 ISpSREngineSite::IsAlternate (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889025 ISpSREngineSite::ParseFromTransitions (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889032 ISpSREngineSite::Read (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889126 ISpSREngineSite::Recognition (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889208 ISpSREngineSite::SetBufferNotifySize (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889303 ISpSREngineSite::SetRuleClientContext (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889491 ISpSREngineSite::SetWordClientContext (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889601 ISpSREngineSite::Synchronize (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889609 ISpSREngineSite::UpdateRecoPos (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890241 ISpTask::Execute (Header: sapiddk.h, sapiddk.idl.) */
/* ms890243 ISpTaskManager::CreateReoccurringTask (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890244 ISpTaskManager::CreateThreadControl (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890245 ISpTaskManager::GetThreadPoolInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890246 ISpTaskManager::QueueTask (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890248 ISpTaskManager::SetThreadPoolInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890249 ISpTaskManager::TerminateTask (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890250 ISpTaskManager::TerminateTaskGroup (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890252 ISpThreadControl::ExitThreadEvent (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890255 ISpThreadControl::NotifyEvent (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890256 ISpThreadControl::StartThread (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890257 ISpThreadControl::TerminateThread (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890258 ISpThreadControl::ThreadCompleteEvent (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890259 ISpThreadControl::ThreadHandle (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890260 ISpThreadControl::ThreadId (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890261 ISpThreadControl::WaitForThreadDone (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890262 ISpThreadControl::WindowHandle (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890264 ISpThreadTask::InitThread (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890265 ISpThreadTask::ThreadProc (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890266 ISpThreadTask::WindowMessage (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890268 ISpTokenUI::DisplayUI (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890269 ISpTokenUI::IsUISupported (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890274 ISpTTSEngine::GetOutputFormat (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890282 ISpTTSEngine::Speak (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890276 ISpTTSEngineSite::CompleteSkip (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890277 ISpTTSEngineSite::GetActions (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890278 ISpTTSEngineSite::GetRate (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890279 ISpTTSEngineSite::GetSkipInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890280 ISpTTSEngineSite::GetVolume (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890281 ISpTTSEngineSite::Write (Header: Sapiddk.h, Sapiddk.idl.) */
/* ------------------------------------------------------------------
 * Book surface: sapi (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms897368 _ISpPrivateEngineCall (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms897369 _ISpPrivateEngineCall::CallEngine (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms897370 _ISpPrivateEngineCall::CallEngineEx (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886319 ISpCFGInterpreter::InitGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886330 ISpCFGInterpreter::Interpret (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886356 ISpCFGInterpreterSite::AddProperty (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886366 ISpCFGInterpreterSite::AddTextReplacement (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886462 ISpCFGInterpreterSite::GetResourceValue (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886840 ISpErrorLog::AddError (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886849 ISpGramCompBackend::InitFromBinaryGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886850 ISpGramCompBackend::SetSaveObjects (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886861 ISpGrammarCompiler::CompileStream (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886863 ISpITNProcessor::ITNPhrase (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886864 ISpITNProcessor::LoadITNGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886911 ISpObjectTokenEnumBuilder::AddTokens (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886912 ISpObjectTokenEnumBuilder::AddTokensFromDataKey (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886913 ISpObjectTokenEnumBuilder::AddTokensFromTokenEnum (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886914 ISpObjectTokenEnumBuilder::SetAttribs (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms886915 ISpObjectTokenEnumBuilder::Sort (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517314 ISpSRAlternates::Commit (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517315 ISpSRAlternates::GetAlternates (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517319 ISpSREngine::GetInputAudioFormat (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517320 ISpSREngine::GetPropertyNum (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517322 ISpSREngine::GetPropertyString (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517323 ISpSREngine::IsPronounceable (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517324 ISpSREngine::LoadProprietaryGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517325 ISpSREngine::LoadSLM (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517326 ISpSREngine::OnCreateGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517327 ISpSREngine::OnCreateRecoContext (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517328 ISpSREngine::OnDeleteGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517329 ISpSREngine::OnDeleteRecoContext (Header: Sapiddk.h, Sapiddk.idl.) */
/* aa517330 ISpSREngine::PrivateCall (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887490 ISpSREngine::PrivateCallEx (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887546 ISpSREngine::RecognizeStream (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887553 ISpSREngine::RuleNotify (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887556 ISpSREngine::SetAdaptationData (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887564 ISpSREngine::SetContextState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887567 ISpSREngine::SetGrammarState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887573 ISpSREngine::SetPropertyNum (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887576 ISpSREngine::SetPropertyString (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887580 ISpSREngine::SetProprietaryRuleIdState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887584 ISpSREngine::SetProprietaryRuleState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887589 ISpSREngine::SetRecoProfile (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887595 ISpSREngine::SetSite (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887603 ISpSREngine::SetSLMState (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887608 ISpSREngine::SetTextSelection (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887616 ISpSREngine::SetWordSequenceData (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889616 ISpSREngine::UnloadProprietaryGrammar (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889623 ISpSREngine::UnloadSLM (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889630 ISpSREngine::WordNotify (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887828 ISpSREngineSite::AddEvent (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887927 ISpSREngineSite::DataAvailable (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887940 ISpSREngineSite::GetContextMaxAlternates (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887951 ISpSREngineSite::GetMaxAlternates (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887966 ISpSREngineSite::GetResource (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887975 ISpSREngineSite::GetRuleInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887988 ISpSREngineSite::GetStateInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms887998 ISpSREngineSite::GetTransitionProperty (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889010 ISpSREngineSite::GetWordInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889018 ISpSREngineSite::IsAlternate (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889025 ISpSREngineSite::ParseFromTransitions (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889032 ISpSREngineSite::Read (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889126 ISpSREngineSite::Recognition (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889208 ISpSREngineSite::SetBufferNotifySize (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889303 ISpSREngineSite::SetRuleClientContext (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889491 ISpSREngineSite::SetWordClientContext (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889601 ISpSREngineSite::Synchronize (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms889609 ISpSREngineSite::UpdateRecoPos (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890241 ISpTask::Execute (Header: sapiddk.h, sapiddk.idl.) */
/* ms890243 ISpTaskManager::CreateReoccurringTask (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890244 ISpTaskManager::CreateThreadControl (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890245 ISpTaskManager::GetThreadPoolInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890246 ISpTaskManager::QueueTask (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890248 ISpTaskManager::SetThreadPoolInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890249 ISpTaskManager::TerminateTask (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890250 ISpTaskManager::TerminateTaskGroup (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890252 ISpThreadControl::ExitThreadEvent (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890255 ISpThreadControl::NotifyEvent (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890256 ISpThreadControl::StartThread (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890257 ISpThreadControl::TerminateThread (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890258 ISpThreadControl::ThreadCompleteEvent (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890259 ISpThreadControl::ThreadHandle (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890260 ISpThreadControl::ThreadId (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890261 ISpThreadControl::WaitForThreadDone (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890262 ISpThreadControl::WindowHandle (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890264 ISpThreadTask::InitThread (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890265 ISpThreadTask::ThreadProc (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890266 ISpThreadTask::WindowMessage (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890268 ISpTokenUI::DisplayUI (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890269 ISpTokenUI::IsUISupported (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890274 ISpTTSEngine::GetOutputFormat (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890282 ISpTTSEngine::Speak (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890276 ISpTTSEngineSite::CompleteSkip (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890277 ISpTTSEngineSite::GetActions (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890278 ISpTTSEngineSite::GetRate (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890279 ISpTTSEngineSite::GetSkipInfo (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890280 ISpTTSEngineSite::GetVolume (Header: Sapiddk.h, Sapiddk.idl.) */
/* ms890281 ISpTTSEngineSite::Write (Header: Sapiddk.h, Sapiddk.idl.) */

