/*
 * Sdcardddk.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-sd.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_SDCARDDDK_H
#define AKARI_SDCARDDDK_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-sd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms920432 SD_FS_TYPE (page print, compiled) */
typedef enum  {
    SD_FS_FAT_PARTITION_TABLE,
    SD_FS_FAT_NO_PARTITION_TABLE,
    SD_FS_UNIVERSAL,
    SD_FS_OTHER
} SD_FS_TYPE, *PSD_FS_TYPE;
/* ms920436 SD_INTERFACE_MODE (page print, compiled) */
typedef enum  {
    SD_INTERFACE_SD_MMC_1BIT,
    SD_INTERFACE_SD_4BIT
} SD_INTERFACE_MODE;
/* ms920454 SD_RESPONSE_TYPE (page print, compiled) */
typedef enum _SD_RESPONSE_TYPE {
    NoResponse,
    ResponseR1,
    ResponseR1b,
    ResponseR2,
    ResponseR3,
    ResponseR4,
    ResponseR5,
    ResponseR6
} SD_RESPONSE_TYPE, *PSD_RESPONSE_TYPE;
/* ms920459 SD_TRANSFER_CLASS (page print, compiled) */
typedef enum  {
    SD_READ,
    SD_WRITE,
    SD_COMMAND
} SD_TRANSFER_CLASS;
/* ms920321 SDCARD_DEVICE_TYPE (page print, compiled) */
typedef enum _SDCARD_DEVICE_TYPE {
    Device_Unknown,
    Device_MMC,
    Device_SD_Memory,
    Device_SD_IO,
    Device_SD_Combo
} SDCARD_DEVICE_TYPE, *PSDCARD_DEVICE_TYPE;
/* ms920414 SD_BUS_REQUEST -- HELD (page print; member types unpublished):
 *   typedef struct _SD_BUS_REQUEST { ... } SD_BUS_REQUEST, *PSD_BUS_REQUEST; */
/* ms920424 SD_CARD_INTERFACE -- HELD (page print; member types unpublished):
 *   typedef struct _SD_CARD_INTERFACE { ... } SD_CARD_INTERFACE, *PSD_CARD_INTERFACE; */
/* ms920426 SD_COMMAND_RESPONSE -- HELD (page print; member types unpublished):
 *   typedef struct _SD_COMMAND_RESPONSE { ... } SD_COMMAND_RESPONSE, *PSD_COMMAND_RESPONSE; */
/* ms920428 SD_DATA_TRANSFER_CLOCKS -- HELD (page print; member types unpublished):
 *   typedef struct _SD_DATA_TRANSFER_CLOCKS { ... } SD_DATA_TRANSFER_TRANSFER_CLOCKS, *PSD_DATA_TRANSFER_CLOCKS; */
/* ms920434 SD_HOST_BLOCK_CAPABILITY -- HELD (page print; member types unpublished):
 *   typedef struct _SD_HOST_BLOCK_CAPABILITY { ... } SD_HOST_BLOCK_CAPABILITY, *PSD_HOST_BLOCK_CAPABILITY; */
/* ms920445 SD_PARSED_REGISTER_CID -- HELD (page print; member types unpublished):
 *   typedef struct _SD_PARSED_REGISTER_CID { ... } SD_PARSED_REGISTER_CID, *PSD_PARSED_REGISTER_CID; */
/* ms920448 SD_PARSED_REGISTER_CSD -- HELD (page print; member types unpublished):
 *   typedef struct _SD_PARSED_REGISTER_CSD { ... } DataAccessTime; */
/* ms920314 SDCARD_CLIENT_REGISTRATION_INFO -- HELD (page print; member types unpublished):
 *   typedef struct _SDCARD_CLIENT_REGISTRATION_INFO { ... } SDCARD_CLIENT_REGISTRATION_INFO, *PSDCARD_CLIENT_REGISTRATION_INFO; */
/* ms920387 SDIO_CARD_INFO -- HELD (page print; member types unpublished):
 *   typedef struct _SDIO_CARD_INFO { ... } SDIO_CARD_INFO, *PSDIO_CARD_INFO; */
/* ms919899 SDAllocateFromMemList: print `PVOID SDAllocateFromMemList(SD_MEMORY_LIST_HANDLEhList);` -- recorded verbatim (no compiled prototype) */
/* ms920293 SDBusRequest: print `SD_API_STATUS SDBusRequest(SD_DEVICE_HANDLEhHandle, UCHARCommand, ULONGArgument, SD_TRANSFER_CLASSTransferClass, SD_RESPONSE_TYPEResponseType, ULONGNumBlocks, ULONGBlockSize, PUCHARpBuffer, PSD_BUS_REQUEST_CALLBACKpCallback, DWORDRequestParam, PSD_BUS_REQUEST*ppRequest, DWORDFlags);` -- recorded verbatim (no compiled prototype) */
/* ms920297 SDCancelBusRequest: print `BOOLEAN SDCancelBusRequest(PSD_BUS_REQUESTpRequest);` -- recorded verbatim (no compiled prototype) */
/* ms920304 SDCardInfoQuery: print `SD_API_STATUS SDCardInfoQuery( SD_DEVICE_HANDLEhHandle, SD_INFO_TYPEInfoType, PVOIDpCardInfo, ULONGStructureSize);` -- recorded verbatim (no compiled prototype) */
/* ms920330 SDCreateMemoryList: print `SD_MEMORY_LIST_HANDLE SDCreateMemoryList(ULONGTag, ULONGDepth, ULONGEntrySize);` -- recorded verbatim (no compiled prototype) */
/* ms920345 SDDeleteMemList: print `VOID SDDeleteMemList( SD_MEMORY_LIST_HANDLEhList);` -- recorded verbatim (no compiled prototype) */
/* ms920353 SDFreeBusRequest: print `VOID SDFreeBusRequest( PSD_BUS_REQUESTpRequest);` -- recorded verbatim (no compiled prototype) */
/* ms920357 SDFreeToMemList: print `VOID SDFreeToMemList(SD_MEMORY_LIST_HANDLEhList, PVOIDpMemory);` -- recorded verbatim (no compiled prototype) */
/* ms920364 SDGetDeviceHandle: print `SD_DEVICE_HANDLE SDGetDeviceHandle(DWORDInitContext, PWCHAR* ppRegPath);` -- recorded verbatim (no compiled prototype) */
/* ms920371 SDGetTuple: print `SD_API_STATUS SDGetTuple(SD_DEVICE_HANDLEhDevice, UCHARTupleCode, PUCHARpBuffer, PULONGpBufferSize, BOOLCommonCIS);` -- recorded verbatim (no compiled prototype) */
/* ms920379 SDIOConnectInterrupt: print `SD_API_STATUS SDIOConnectInterrupt( SD_DEVICE_HANDLEhDevice, PSD_INTERRUPT_CALLBACKpIsrFunction);` -- recorded verbatim (no compiled prototype) */
/* ms920383 SDIODisconnectInterrupt: print `VOID SDIODisconnectInterrupt( SD_DEVICE_HANDLEhDevice);` -- recorded verbatim (no compiled prototype) */
/* ms920391 SDOutputBuffer: print `VOID SDOutputBuffer(PVOIDpBuffer, ULONGBufferSize);` -- recorded verbatim (no compiled prototype) */
/* ms920396 SDPerformSafeCopy: print `BOOLEAN SDPerformSafeCopy(PVOIDpDestination, PVOIDpSource, ULONGLength);` -- recorded verbatim (no compiled prototype) */
/* ms920399 SDReadWriteRegistersDirect: print `SD_API_STATUS SDReadWriteRegistersDirect(SD_DEVICE_HANDLEhDevice, SD_IO_TRANSFER_TYPEReadWrite, UCHARFunction, DWORDAddress, BOOLEANReadAfterWrite, PUCHARpBuffer, ULONGBufferLength);` -- recorded verbatim (no compiled prototype) */
/* ms920402 SDRegisterClient: print `SD_API_STATUS SDRegisterClient(SD_DEVICE_HANDLEhDevice, PVOIDpDeviceContext, PSDCARD_CLIENT_REGISTRATION_INFOpInfo);` -- recorded verbatim (no compiled prototype) */
/* ms920406 SDSetCardFeature: print `SD_API_STATUS SDSetCardFeature(SD_DEVICE_HANDLEhDevice, SD_SET_FEATURE_TYPECardFeature, PVOIDpCardInfo, ULONGStructureSize);` -- recorded verbatim (no compiled prototype) */
/* ms920410 SDSynchronousBusRequest: print `SD_API_STATUS SDSynchronousBusRequest(SD_DEVICE_HANDLEhHandle, UCHARCommand, DWORDArgument, SD_TRANSFER_CLASSTransferClass,SD_RESPONSE_TYPEResponseType, PSD_COMMAND_RESPONSEpResponse, ULONGNumBlocks, ULONGBlockSize, PUCHARpBuffer,DWORDFlags);` -- recorded verbatim (no compiled prototype) */

/* ------------------------------------------------------------------
 * Book surface: drivers-sd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890608 Asynchronous Bus Requests */
/* ms891038 Card Information Structures */
/* ms891100 Client Driver Entry Points */
/* ms891109 Client Driver Registration */
/* ms891161 Combo Cards */
/* ms892501 Multi-Function Cards */
/* aa447564 Power On and Off Notifications for Secure Digital Card Drivers */
/* ms893994 Secure Digital Card Bus Driver */
/* ms894008 Secure Digital Card Driver Registry Settings */
/* ms920486 Secure Digital Card Driver Status Codes */
/* ms894010 Secure Digital Card Multimedia Card Compatibility */
/* ms894025 Single Function Cards */
/* ms894026 Slot Event Callback */
/* ms894055 Synchronous Bus Requests */

/* ------------------------------------------------------------------
 * Book surface: drivers-sd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-sd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890608 Asynchronous Bus Requests */
/* ms891038 Card Information Structures */
/* ms891100 Client Driver Entry Points */
/* ms891109 Client Driver Registration */
/* ms891161 Combo Cards */
/* ms892501 Multi-Function Cards */
/* aa447564 Power On and Off Notifications for Secure Digital Card Drivers */
/* ms893994 Secure Digital Card Bus Driver */
/* ms894008 Secure Digital Card Driver Registry Settings */
/* ms920486 Secure Digital Card Driver Status Codes */
/* ms894010 Secure Digital Card Multimedia Card Compatibility */
/* ms894025 Single Function Cards */
/* ms894026 Slot Event Callback */
/* ms894055 Synchronous Bus Requests */

/* ------------------------------------------------------------------
 * Book surface: drivers-sd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms920438 SD_IO_FUNCTION_ENABLE_INFO: documented name-only (no value published; held) */
/* ms920440 SD_IO_TRANSFER_TYPE: documented name-only (no value published; held) */

/* ------------------------------------------------------------------
 * Book surface: drivers-sd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890608 Asynchronous Bus Requests */
/* ms891038 Card Information Structures */
/* ms891100 Client Driver Entry Points */
/* ms891109 Client Driver Registration */
/* ms891161 Combo Cards */
/* ms892501 Multi-Function Cards */
/* aa447564 Power On and Off Notifications for Secure Digital Card Drivers */
/* ms893994 Secure Digital Card Bus Driver */
/* ms894008 Secure Digital Card Driver Registry Settings */
/* ms920486 Secure Digital Card Driver Status Codes */
/* ms894010 Secure Digital Card Multimedia Card Compatibility */
/* ms894025 Single Function Cards */
/* ms894026 Slot Event Callback */
/* ms894055 Synchronous Bus Requests */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_SDCARDDDK_H */
