/*
 * Sdcard.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-sd.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_SDCARD_H
#define AKARI_SDCARD_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-sd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896148 BUILD_IO_RW_DIRECT_ARG: print `DWORD BUILD_IO_RW_DIRECT_ARG(RWFlag, RAW, Function, Address, Data);` -- recorded verbatim (no compiled prototype) */
/* ms896149 BUILD_IO_RW_EXTENDED_ARG: print `DWORD BUILD_IO_RW_EXTENDED_ARG(Read_Write, BlockMode, Function, Address, IncrementAddress, Count);` */
/* (record-only: parameter or return type unpublished) */
/* ms920417 SD_BUS_REQUEST_RESPONSE: print `PSD_COMMAND_RESPONSE SD_BUS_REQUEST_RESPONSE(PSD_BUS_REQUESTpRequest );` -- recorded verbatim (no compiled prototype) */
/* ms920420 SD_BUS_REQUEST_STATUS: print `SD_API_STATUS SD_BUS_REQUEST_STATUS(PSD_BUS_REQUESTpRequest );` -- recorded verbatim (no compiled prototype) */
/* ms920430 SD_DEBUG_INSTANTIATE_ZONES: print `#define SD_DEBUG_INSTANTIATE_ZONES(TCHARModuleName, DWORDInitialValue, TCHARSlot0, TCHARSlot1, TCHARSlot2, TCHARSlot3, TCHARSlot4, TCHARSlot5, TCHARSlot6, TCHARSlot7, TCHARSlot8, TCHARSlot9, TCHARSlot10);` -- recorded verbatim (no compiled prototype) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_SDCARD_H */
