/*
 * Sdmem.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-sd.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_SDMEM_H
#define AKARI_SDMEM_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-sd (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms920339 SDDeinitializeCardLib: print `BOOL SDDeinitializeCardLib();` */
AKARI_CE_IMPORT BOOL SDDeinitializeCardLib(void)
    AKARI_CE_NAME(SDDeinitializeCardLib);
/* ms920376 SDInitializeCardLib: print `BOOL SDInitializeCardLib();` */
AKARI_CE_IMPORT BOOL SDInitializeCardLib(void)
    AKARI_CE_NAME(SDInitializeCardLib);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_SDMEM_H */
