/*
 * Serhw.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-serial.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_SERHW_H
#define AKARI_SERHW_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-serial (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms898289 DEVICE_LIST -- HELD (page print; member types unpublished):
 *   typedef struct __DEVICE_LIST { ... } DEVICE_LIST, *PDEVICE_LIST; */
/* ms900163 HW_VTBL -- HELD (page print; member types unpublished):
 *   typedef struct __HW_VTBL { ... } HW_VTBL, *PHW_VTBL; */
/* ms900147 HWOBJ -- HELD (page print; member types unpublished):
 *   typedef struct __HWOBJ { ... } HWOBJ, *PHWOBJ; */
/* ms899312 GetSerialObject: print `PHWOBJ GetSerialObject(DWORDDeviceArrayIndex);` -- recorded verbatim (no compiled prototype) */
/* ms899897 HWClearBreak: print `VOID HWClearBreak(PVOIDpContext);` */
VOID HWClearBreak(PVOID pContext);
/* ms900102 HWClearDTR: print `VOID HWClearDTR(PVOIDpContext);` */
VOID HWClearDTR(PVOID pContext);
/* ms900109 HWClearRTS: print `VOID HWClearRTS(PVOIDpContext);` */
VOID HWClearRTS(PVOID pContext);
/* ms900113 HWClose: print `ULONG HWClose(PVOIDpContext);` */
ULONG HWClose(PVOID pContext);
/* ms900119 HWDeinit: print `BOOL HWDeinit(PVOIDpContext);` */
BOOL HWDeinit(PVOID pContext);
/* ms900121 HWDisableIR: print `BOOL HWDisableIR( PVOID pContext);` */
BOOL HWDisableIR(PVOID pContext);
/* ms900126 HWEnableIR: print `BOOL HWEnableIR(PVOIDpContext,ULONGBaudRate);` -- recorded verbatim (no compiled prototype) */
/* ms900133 HWGetCommProperties: print `VOID HWGetCommProperties(PVOIDpContext,LPCOMMPROPpCommProp);` */
VOID HWGetCommProperties(PVOID pContext, LPCOMMPROP pCommProp);
/* ms900137 HWGetIntrType: print `INTERRUPT_TYPE HWGetIntrType(PVOIDpContext);` */
/* (record-only: parameter or return type unpublished) */
/* ms900139 HWGetModemStatus: print `VOID HWGetModemStatus(PVOIDpContext,PULONGpModemStatus);` */
VOID HWGetModemStatus(PVOID pContext, PULONG pModemStatus);
/* ms900140 HWGetRxBufferSize: print `ULONG HWGetRxBufferSize(PVOIDpContext);` */
ULONG HWGetRxBufferSize(PVOID pContext);
/* ms900141 HWGetRxStart: print `PVOID HWGetRxStart(PVOID pContext);` */
PVOID HWGetRxStart(PVOID pContext);
/* ms900142 HWGetStatus: print `ULONG HWGetStatus(PVOIDpContext,LPCOMSTATlpStat);` */
ULONG HWGetStatus(PVOID pContext, LPCOMSTAT lpStat);
/* ms900143 HWInit: print `PVOID HWInit(ULONG Identifier,PVOID pMDDContext,PHWOBJ pHWObj);` */
/* (record-only: parameter or return type unpublished) */
/* ms900144 HWIoctl: print `BOOL HWIoctl(DWORD dwOpenData,DWORD dwCode,PBYTEpBufIn,DWORD dwLenIn,PBYTEpBufOut,DWORD dwLenOut,PDWORD pdwActualOut);` */
BOOL HWIoctl(DWORD dwOpenData, DWORD dwCode, PBYTE pBufIn, DWORD dwLenIn, PBYTE pBufOut, DWORD dwLenOut, PDWORD pdwActualOut);
/* ms900145 HWLineIntrHandler: print `VOID HWLineIntrHandler(PVOID pContext);` */
VOID HWLineIntrHandler(PVOID pContext);
/* ms900146 HWModemIntrHandler: print `VOID HWModemIntrHandler(PVOID pContext);` */
VOID HWModemIntrHandler(PVOID pContext);
/* ms900148 HWOpen: print `BOOL HWOpen(PVOID pContext);` */
BOOL HWOpen(PVOID pContext);
/* ms900150 HWPostInit: print `BOOL HWPostInit(PVOID pContext );` */
BOOL HWPostInit(PVOID pContext);
/* ms900151 HWPowerOff: print `BOOL HWPowerOff(PVOIDpContext);` */
BOOL HWPowerOff(PVOID pContext);
/* ms900152 HWPowerOn: print `BOOL HWPowerOn(PVOID pContext);` */
BOOL HWPowerOn(PVOID pContext);
/* ms900153 HWPurgeComm: print `VOID HWPurgeComm(PVOIDpContext,DWORD fdwAction);` */
VOID HWPurgeComm(PVOID pContext, DWORD fdwAction);
/* ms900154 HWPutBytes: print `ULONG HWPutBytes(PVOID pContext,PUCHAR pSrc,ULONG NumberOfBytes,PULONG pBytesSent);` */
ULONG HWPutBytes(PVOID pContext, PUCHAR pSrc, ULONG NumberOfBytes, PULONG pBytesSent);
/* ms900155 HWReset: print `void HWReset(PVOID pContext);` */
void HWReset(PVOID pContext);
/* ms900156 HWRxIntrHandler: print `ULONG HWRxIntrHandler(PVOIDpContext,PUCHARpTargetBuffer,PULONGpByteNumber);` */
ULONG HWRxIntrHandler(PVOID pContext, PUCHAR pTargetBuffer, PULONG pByteNumber);
/* ms900157 HWSetBreak: print `VOID HWSetBreak(PVOID pContext);` */
VOID HWSetBreak(PVOID pContext);
/* ms900158 HWSetCommTimeouts: print `BOOL HWSetCommTimeouts(PVOIDpContext,LPCOMMTIMEOUTSlpCommTO);` */
BOOL HWSetCommTimeouts(PVOID pContext, LPCOMMTIMEOUTS lpCommTO);
/* ms900159 HWSetDCB: print `BOOL HWSetDCB(PVOIDpContext,LPDCBpDCB);` */
BOOL HWSetDCB(PVOID pContext, LPDCB pDCB);
/* ms900160 HWSetDTR: print `VOID HWSetDTR(PVOID pContext);` */
VOID HWSetDTR(PVOID pContext);
/* ms900161 HWSetRTS: print `VOID HWSetRTS(PVOID pContext);` */
VOID HWSetRTS(PVOID pContext);
/* ms900162 HWTxIntrHandler: print `VOID HWTxIntrHandler(PVOID pContext, PUCHAR pSourceBuffer, PULONG pByteNumber );` */
VOID HWTxIntrHandler(PVOID pContext, PUCHAR pSourceBuffer, PULONG pByteNumber);
/* ms900164 HWXmitComChar: print `BOOL HWXmitComChar(PVOID pContext,UCHAR ComChar);` */
BOOL HWXmitComChar(PVOID pContext, UCHAR ComChar);

/* ------------------------------------------------------------------
 * Book surface: drivers-serial (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447675 COM_Close: print `BOOL COM_Close(DWORD pContext);` */
AKARI_CE_IMPORT BOOL COM_Close(DWORD pContext)
    AKARI_CE_NAME(COM_Close);
/* aa447676 COM_Deinit: print `BOOL COM_Deinit(void);` */
AKARI_CE_IMPORT BOOL COM_Deinit(void)
    AKARI_CE_NAME(COM_Deinit);
/* aa447677 COM_Init: print `HANDLE COM_Init(ULONG Identifier);` */
AKARI_CE_IMPORT HANDLE COM_Init(ULONG Identifier)
    AKARI_CE_NAME(COM_Init);
/* aa447678 COM_IOControl: print `BOOL COM_IOControl(DWORD dwOpenData,DWORD dwCode,PBYTE pBufIn,DWORD dwLenIn,PBYTE pBufOut,DWORD dwLenOut,PDWORD pdwActualOut);` */
AKARI_CE_IMPORT BOOL COM_IOControl(DWORD dwOpenData, DWORD dwCode, PBYTE pBufIn, DWORD dwLenIn, PBYTE pBufOut, DWORD dwLenOut, PDWORD pdwActualOut)
    AKARI_CE_NAME(COM_IOControl);
/* aa447679 COM_Open: print `HANDLE COM_Open(HANDLE pContext,DWORD AccessCode,DWORD ShareMode);` */
AKARI_CE_IMPORT HANDLE COM_Open(HANDLE pContext, DWORD AccessCode, DWORD ShareMode)
    AKARI_CE_NAME(COM_Open);
/* aa447680 COM_PowerDown: print `BOOL COM_PowerDown(HANDLE pContext);` */
AKARI_CE_IMPORT BOOL COM_PowerDown(HANDLE pContext)
    AKARI_CE_NAME(COM_PowerDown);
/* aa447681 COM_PowerUp: print `BOOL COM_PowerUp(HANDLE pContext);` */
AKARI_CE_IMPORT BOOL COM_PowerUp(HANDLE pContext)
    AKARI_CE_NAME(COM_PowerUp);
/* aa447682 COM_Read: print `ULONG COM_Read(HANDLE pContext,PUCHAR pTargetBuffer,ULONG BufferLength,PULONGpBytesRead);` */
AKARI_CE_IMPORT ULONG COM_Read(HANDLE pContext, PUCHAR pTargetBuffer, ULONG BufferLength, PULONG pBytesRead)
    AKARI_CE_NAME(COM_Read);
/* aa447683 COM_Write: print `ULONG COM_Write(HANDLE COM_Write,PUCHAR pSourceBytes,ULONG NumberOfBytes);` */
AKARI_CE_IMPORT ULONG COM_Write(HANDLE COM_Write, PUCHAR pSourceBytes, ULONG NumberOfBytes)
    AKARI_CE_NAME(COM_Write);
/* ms890705 Automatic Detection of Docking for Serial Ports */
/* ms892179 High Speed Serial Port Driver */
/* ms895498 Migrating a Serial Port Driver */
/* aa447559 Power Management in Serial Port Drivers */
/* ms894015 Serial Port Driver Architecture */
/* ms894017 Serial Port Driver Registry Settings */
/* ms894019 Serial Port Driver Samples */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_SERHW_H */
