/*
 * Smcce.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-scm.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_SMCCE_H
#define AKARI_SMCCE_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-scm (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919326 OS_DEP_DATA -- HELD (page print; member types unpublished):
 *   typedef struct _OS_DEP_DATA { ... } OS_DEP_DATA, *POS_DEP_DATA; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_SMCCE_H */
