/*
 * Smclib.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-scm.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_SMCLIB_H
#define AKARI_SMCLIB_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-scm (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448186 T1_DATA (page print, compiled) */
typedef struct _T1_DATA {
    UCHAR InfSize;
    ULONG BytesReceived;
    ULONG BytesSent;
    ULONG BytesToSend;
    UCHAR LastError;
    UCHAR NAD;
    ULONG PrevState;
    UCHAR Resend;
    UCHAR Resynch;
    UCHAR SSN;
    ULONG State;
    UCHAR Wtx;
} T1_DATA, *PT1_DATA;
/* ms919892 SCARD_CARD_CAPABILITIES -- HELD (page print; member types unpublished):
 *   typedef struct _SCARD_CARD_CAPABILITIES { ... } ATR; */
/* ms919894 SCARD_READER_CAPABILITIES -- HELD (page print; member types unpublished):
 *   typedef struct _SCARD_READER_CAPABILITIES { ... } SupportedProtocols; */
/* ms919896 SCARD_VENDOR_ATTR -- HELD (page print; member types unpublished):
 *   typedef struct _VENDOR_ATTR { ... } VendorName; */
/* ms921035 SMARTCARD_EXTENSION -- HELD (page print; member types unpublished):
 *   typedef struct _SMARTCARD_EXTENSION { ... } IoRequest; */
/* ms902177 MapNtStatusToWinError: print `ULONG MapNtStatusToWinError(NTSTATUS Status);` */
ULONG MapNtStatusToWinError(NTSTATUS Status);
/* ms920847 SmartcardCreateLink: print `NTSTATUS SmartcardCreateLink(LPCWSTR pszFriendlyName,LPCWSTR pszDeviceName);` */
NTSTATUS SmartcardCreateLink(LPCWSTR pszFriendlyName, LPCWSTR pszDeviceName);
/* ms920918 SmartcardDeleteLink: print `NTSTATUS SmartcardDeleteLink(LPCWSTR pszFriendlyName);` */
NTSTATUS SmartcardDeleteLink(LPCWSTR pszFriendlyName);
/* ms920926 SmartcardDeviceControl: print `NTSTATUS SmartcardDeviceControl(PSMARTCARD_EXTENSION SmartcardExtension,PBYTE pInBuf,DWORD nInBufSize,PBYTE pOutBuf,DWORD nOutBufSize,PDWORD pBytesReturned);` */
/* (record-only: parameter or return type unpublished) */
/* ms920933 SmartcardExit: print `VOID SmartcardExit(PSMARTCARD_EXTENSIONSmartcardExtension);` -- recorded verbatim (no compiled prototype) */
/* ms921144 SmartcardInitialize: print `NTSTATUS SmartcardInitialize(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921243 SmartcardLockDevice: print `NTSTATUS SmartcardLockDevice(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921272 SmartcardRawReply: print `NTSTATUS SmartcardRawReply(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921385 SmartcardRawRequest: print `NTSTATUS SmartcardRawRequest(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921419 SmartcardT0Reply: print `NTSTATUS SmartcardT0Reply(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921526 SmartcardT0Request: print `NTSTATUS SmartcardT0Request(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921641 SmartcardT1Reply: print `NTSTATUS SmartcardT1Reply(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921760 SmartcardT1Request: print `NTSTATUS SmartcardT1Request(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921781 SmartcardUnlockDevice: print `NTSTATUS SmartcardUnlockDevice(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */
/* ms921790 SmartcardUpdateCardCapabilities: print `NTSTATUS SmartcardUpdateCardCapabilities(PSMARTCARD_EXTENSION SmartcardExtension);` */
/* (record-only: parameter or return type unpublished) */

/* ------------------------------------------------------------------
 * Book surface: drivers-scm (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms894027 Smart Card Driver Architecture */
/* ms894028 Smart Card Driver Debugging */
/* ms894029 Smart Card Driver Registry Settings */
/* ms894031 Smart Card Driver Samples */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_SMCLIB_H */
