/*
 * Socksv2.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-pccard.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_SOCKSV2_H
#define AKARI_SOCKSV2_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms921890 SS_POWER_ENTRY -- HELD (page print; member types unpublished):
 *   typedef struct SS_POWER_ENTRY { ... } SS_POWER_ENTRY, *PSS_POWER_ENTRY; */
/* ms921925 SS_SOCKET_INFO -- HELD (page print; member types unpublished):
 *   typedef struct SS_SOCKET_INFO { ... } SS_SOCKET_INFO, *PSS_SOCKET_INFO; */
/* ms921935 SS_SOCKET_SERVICE -- HELD (page print; member types unpublished):
 *   typedef struct SS_SOCKET_SERVICE { ... } SS_SOCKET_SERVICE, *PSS_SOCKET_SERVICE; */
/* ms921944 SS_SOCKET_STATE -- HELD (page print; member types unpublished):
 *   typedef struct SS_SOCKETSTATE { ... } SS_SOCKET_STATE, *PSS_SOCKET_STATE; */
/* aa448145 SS_WINDOW_INFO -- HELD (page print; member types unpublished):
 *   typedef struct SS_WINDOW_INFO { ... } SS_WINDOW_INFO, *PSS_WINDOW_INFO; */
/* aa448146 SS_WINDOW_STATE -- HELD (page print; member types unpublished):
 *   typedef struct SS_WINDOW_STATE { ... } SS_WINDOW_STATE, *PSS_WINDOW_STATE; */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447694 CS_SocketCallback: documented name-only (no value published; held) */
/* ms921840 SS_GetPowerEntry: documented name-only (no value published; held) */
/* ms921851 SS_GetSocket: documented name-only (no value published; held) */
/* ms921864 SS_GetWindow: documented name-only (no value published; held) */
/* ms921870 SS_InquireSocket: documented name-only (no value published; held) */
/* ms921879 SS_InquireWindow: documented name-only (no value published; held) */
/* ms921896 SS_ResetSocket: documented name-only (no value published; held) */
/* ms921903 SS_SetSocket: documented name-only (no value published; held) */
/* ms921913 SS_SetWindow: documented name-only (no value published; held) */
/* ms921955 SS_TranslateBusAddr: documented name-only (no value published; held) */
/* aa448144 SS_TranslateSystemAddr: documented name-only (no value published; held) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_SOCKSV2_H */
