/*
 * Tchddsi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-touch.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_TCHDDSI_H
#define AKARI_TCHDDSI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-touch (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms898269 DdsiTouchPanelAttach: print `LONG DdsiTouchPanelAttach(void);` */
AKARI_CE_IMPORT LONG DdsiTouchPanelAttach(void)
    AKARI_CE_NAME(DdsiTouchPanelAttach);
/* ms898270 DdsiTouchPanelDetach: print `LONG DdsiTouchPanelDetach(void);` */
AKARI_CE_IMPORT LONG DdsiTouchPanelDetach(void)
    AKARI_CE_NAME(DdsiTouchPanelDetach);
/* ms898271 DdsiTouchPanelDisable: print `VOID DdsiTouchPanelDisable(void);` */
AKARI_CE_IMPORT VOID DdsiTouchPanelDisable(void)
    AKARI_CE_NAME(DdsiTouchPanelDisable);
/* ms898272 DdsiTouchPanelEnable: print `BOOL DdsiTouchPanelEnable(void);` */
AKARI_CE_IMPORT BOOL DdsiTouchPanelEnable(void)
    AKARI_CE_NAME(DdsiTouchPanelEnable);
/* ms898273 DdsiTouchPanelGetDeviceCaps: print `BOOL DdsiTouchPanelGetDeviceCaps(ULONGiIndex,LPVOIDlpOutput);` */
AKARI_CE_IMPORT BOOL DdsiTouchPanelGetDeviceCaps(ULONG iIndex, LPVOID lpOutput)
    AKARI_CE_NAME(DdsiTouchPanelGetDeviceCaps);
/* ms898274 DdsiTouchPanelGetPoint: print `void DdsiTouchPanelGetPoint(TOUCH_PANEL_SAMPLE_FLAGSpTipState,PLONGpUnCalX,PLONGpUnCalY);` -- recorded verbatim (no compiled prototype) */
/* ms898276 DdsiTouchPanelPowerHandler: print `VOID DdsiTouchPanelPowerHandler(BOOLbOff);` */
AKARI_CE_IMPORT VOID DdsiTouchPanelPowerHandler(BOOL bOff)
    AKARI_CE_NAME(DdsiTouchPanelPowerHandler);
/* ms898277 DdsiTouchPanelSetMode: print `BOOL DdsiTouchPanelSetMode(ULONGiIndex,LPVOIDlpInput);` */
AKARI_CE_IMPORT BOOL DdsiTouchPanelSetMode(ULONG iIndex, LPVOID lpInput)
    AKARI_CE_NAME(DdsiTouchPanelSetMode);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_TCHDDSI_H */
