/*
 * Tchddi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-touch.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_TCHDDI_H
#define AKARI_TCHDDI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-touch (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct INT32 INT32;   /* opaque carrier (layout unpublished) */
/* aa448197 TouchPanelCalibrateAPoint: print `VOID TouchPanelCalibrateAPoint(INT32 UncalX,INT32 UncalY,INT32* pCalX,INT32* pCalY);` */
AKARI_CE_IMPORT VOID TouchPanelCalibrateAPoint(INT32 UncalX, INT32 UncalY, INT32* pCalX, INT32* pCalY)
    AKARI_CE_NAME(TouchPanelCalibrateAPoint);
/* aa448198 TouchPanelDisable: print `VOID TouchPanelDisable(void);` */
AKARI_CE_IMPORT VOID TouchPanelDisable(void)
    AKARI_CE_NAME(TouchPanelDisable);
/* aa448199 TouchPanelEnable: print `BOOL TouchPanelEnable(PFN_TOUCH_PANEL_CALLBACK pfnCallback);` */
/* (record-only: parameter or return type unpublished) */
/* aa448200 TouchPanelGetDeviceCaps: print `BOOL TouchPanelGetDeviceCaps(INT iIndex,LPVOID lpOutput);` */
AKARI_CE_IMPORT BOOL TouchPanelGetDeviceCaps(INT iIndex, LPVOID lpOutput)
    AKARI_CE_NAME(TouchPanelGetDeviceCaps);
/* aa448201 TouchPanelInitializeCursor: print `BOOL TouchPanelInitializeCursor( PFN_DISP_DRIVER_MOVE_CURSOR);` -- recorded verbatim (no compiled prototype) */
/* aa448202 TouchPanelPowerHandler: print `VOID TouchPanelPowerHandler(BOOL bOff);` */
AKARI_CE_IMPORT VOID TouchPanelPowerHandler(BOOL bOff)
    AKARI_CE_NAME(TouchPanelPowerHandler);
/* aa448203 TouchPanelReadCalibrationAbort: print `VOID TouchPanelReadCalibrationAbort(void);` */
AKARI_CE_IMPORT VOID TouchPanelReadCalibrationAbort(void)
    AKARI_CE_NAME(TouchPanelReadCalibrationAbort);
/* aa448204 TouchPanelReadCalibrationPoint: print `BOOL TouchPanelReadCalibrationPoint(INT* pRawX,INT* pRawY);` */
AKARI_CE_IMPORT BOOL TouchPanelReadCalibrationPoint(INT* pRawX, INT* pRawY)
    AKARI_CE_NAME(TouchPanelReadCalibrationPoint);
/* aa448206 TouchPanelSetCalibration: print `VOID TouchPanelSetCalibration(INT32 cCalibrationPoints,INT32* pScreenXBuffer,INT32* pScreenYBuffer,INT32* pUncalXBuffer,INT32* pUncalYBuffer);` */
AKARI_CE_IMPORT VOID TouchPanelSetCalibration(INT32 cCalibrationPoints, INT32* pScreenXBuffer, INT32* pScreenYBuffer, INT32* pUncalXBuffer, INT32* pUncalYBuffer)
    AKARI_CE_NAME(TouchPanelSetCalibration);
/* aa448207 TouchPanelSetMode: print `BOOL TouchPanelSetMode(INTiIndex,LPVOID lpInput);` */
AKARI_CE_IMPORT BOOL TouchPanelSetMode(INT iIndex, LPVOID lpInput)
    AKARI_CE_NAME(TouchPanelSetMode);
/* aa447794 enumTouchPanelSampleFlags (Header: Tchddi.h.) */

/* ------------------------------------------------------------------
 * Book surface: drivers-touch (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447795 ErrorAnalysis: print `BOOL ErrorAnalysis(INT32 cCalibrationPoints,INT32* pScreenXBuffer,INT32* pScreenYBuffer,INT32* pUncalXBuffer,INT32* pUncalYBuffer);` */
AKARI_CE_IMPORT BOOL ErrorAnalysis(INT32 cCalibrationPoints, INT32* pScreenXBuffer, INT32* pScreenYBuffer, INT32* pUncalXBuffer, INT32* pUncalYBuffer)
    AKARI_CE_NAME(ErrorAnalysis);
/* ms894068 Touch Screen Driver Development Concepts */
/* ms894067 Touch Screen Driver Registry Settings */
/* ms894069 Touch Screen Driver Samples */

/* ------------------------------------------------------------------
 * Book surface: drivers-touch (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447794 enumTouchPanelSampleFlags (Header: Tchddi.h.) */

/* ------------------------------------------------------------------
 * Book surface: drivers-touch (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms894068 Touch Screen Driver Development Concepts */
/* ms894067 Touch Screen Driver Registry Settings */
/* ms894069 Touch Screen Driver Samples */

/* ------------------------------------------------------------------
 * Book surface: drivers-touch (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448205 TOUCH_PANEL_SAMPLE_FLAGS: documented name-only (no value published; held) */
/* aa448208 TPDC_CALIBRATION_POINT: documented name-only (no value published; held) */
/* aa448209 TPDC_CALIBRATION_POINT_COUNT: documented name-only (no value published; held) */
/* aa448210 TPDC_SAMPLE_RATE: documented name-only (no value published; held) */
/* aa447794 enumTouchPanelSampleFlags (Header: Tchddi.h.) */

/* ------------------------------------------------------------------
 * Book surface: drivers-touch (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms894068 Touch Screen Driver Development Concepts */
/* ms894067 Touch Screen Driver Registry Settings */
/* ms894069 Touch Screen Driver Samples */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_TCHDDI_H */
