/*
 * Tuple.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-pccard.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_TUPLE_H
#define AKARI_TUPLE_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-pccard (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919354 PARSED_CONFIG (page print, compiled) */
typedef struct  {
    UINT32 ConfigBase;
    UINT8 RegMask;
    UINT8 LastConfigIndex;
} PARSED_CONFIG;
/* ms919675 POWER_DESCR (page print, compiled) */
typedef struct  {
    UINT16 ValidMask;
    UINT16 NominalV;
    UINT16 MinV;
    UINT16 MaxV;
    UINT16 StaticI;
    UINT16 AvgI;
    UINT16 PeakI;
    UINT16 PowerDownI;
} POWER_DESCR;
/* ms919345 PARSED_CFTABLE -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } PARSED_CFTABLE; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_TUPLE_H */
