/*
 * Usb100.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-usbhost.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_USB100_H
#define AKARI_USB100_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-usbhost (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923225 USB_DEVICE_DESCRIPTOR (page print, compiled) */
typedef struct  {
    UCHAR bLength;
    UCHAR bDescriptorType;
    USHORT bcdUSB;
    UCHAR bDeviceClass;
    UCHAR bDeviceSubClass;
    UCHAR bDeviceProtocol;
    UCHAR bMaxPacketSize0;
    USHORT idVendor;
    USHORT idProduct;
    USHORT bcdDevice;
    UCHAR iManufacturer;
    UCHAR iSerialNumber;
    UCHAR bNumConfigurations;
} USB_DEVICE_DESCRIPTOR;
/* ms923248 USB_ENDPOINT_DESCRIPTOR (page print, compiled) */
typedef struct  {
    UCHAR bLength;
    UCHAR bDescriptorType;
    UCHAR bEndpointAddress;
    UCHAR bmAttributes;
    USHORT wMaxPacketSize;
    UCHAR bInterval;
} USB_ENDPOINT;
/* ms923196 USB_CONFIGURATION_DESCRIPTOR -- HELD (page print; member types unpublished):
 *   typedef struct  { ... } USB_CONFIGURATION_DESCRIPTOR; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_USB100_H */
