/*
 * Usbclient.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-usbhost.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_USBCLIENT_H
#define AKARI_USBCLIENT_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-usbhost (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919799 REG_VALUE_DESCR (page print, compiled) */
typedef struct _REG_VALUE_DESCR {
    LPWSTR Name;
    DWORD Type;
    DWORD Size;
    PBYTE Data;
} REG_VALUE_DESCR, *PREG_VALUE_DESCR;
/* ms919828 REMOVE_LOCK (page print, compiled) */
typedef struct _REMOVE_LOCK {
    BOOL Removed;
    LONG IoCount;
    HANDLE RemoveEvent;
} REMOVE_LOCK, *PREMOVE_LOCK;
/* ms895509 AbortTransfer: print `BOOL AbortTransfer( LPCUSB_FUNCS pUsbFuncs,USB_TRANSFERhTransfer,DWORDdwFlags);` */
/* (record-only: parameter or return type unpublished) */
/* ms896105 AcquireRemoveLock: print `DWORD AcquireRemoveLock( IN PREMOVE_LOCK Lock, IN OPTIONAL PVOID Tag);` */
/* (record-only: parameter or return type unpublished) */
/* aa447665 ClearOrSetFeature: print `DWORD ClearOrSetFeature( LPCUSB_FUNCS UsbFuncs, HANDLE hUsbDevice, LPTRANSFER_NOTIFY_ROUTINE NotifyRoutine, PVOID NotifyContext, DWORD dwFlags, WORD wFeature, UCHAR bIndex, DWORD dwTimeout, BOOL bSet);` */
/* (record-only: parameter or return type unpublished) */
/* aa447672 CloseTransferHandle: print `BOOL CloseTransferHandle( LPCUSB_FUNCS UsbFuncs, USB_TRANSFER hTransfer);` */
/* (record-only: parameter or return type unpublished) */
/* ms898279 DefaultTransferComplete: print `DWORD DefaultTransferComplete( PVOID Context);` */
DWORD DefaultTransferComplete(PVOID Context);
/* ms899314 GetSetKeyValues: print `BOOL GetSetKeyValues( LPCTSTR KeyName, PREG_VALUE_DESCR ValDesc, BOOL bSet, BOOL bOverwrite);` */
/* (record-only: parameter or return type unpublished) */
/* ms899321 GetTransferStatus: print `BOOL GetTransferStatus( LPCUSB_FUNCS UsbFuncs, USB_TRANSFER hTransfer, LPDWORD pBytesTransferred, PUSB_ERROR pUsbError);` */
/* (record-only: parameter or return type unpublished) */
/* ms901365 InitializeRemoveLock: print `BOOL InitializeRemoveLock( IN PREMOVE_LOCK Lock);` */
/* (record-only: parameter or return type unpublished) */
/* ms902128 IssueBulkTransfer: print `` -- recorded verbatim (no compiled prototype) */
/* ms902130 IssueInterruptTransfer: print `DWORD IssueInterruptTransfer( LPCUSB_FUNCS UsbFuncs, USB_PIPE hPipe, LPTRANSFER_NOTIFY_ROUTINE NotifyRoutine, PVOID NotifyContext, DWORD Flags, LPVOID pBuffer, ULONG PhysAddr, DWORD BufferLength, LPDWORD pBytesTransferred, DWORD dwTimeout, PUSB_ERROR pUsbRc);` */
/* (record-only: parameter or return type unpublished) */
/* ms902132 IssueVendorTransfer: print `DWORD IssueVendorTransfer( LPCUSB_FUNCS UsbFuncs, HANDLE hUsbDevice, LPTRANSFER_NOTIFY_ROUTINE NotifyRoutine, PVOID NotifyContext, DWORD Flags, PUSB_DEVICE_REQUEST pControlHeader, LPVOID pBuf, ULONG PhysAddr, LPDWORD pBytesTransferred, DWORD dwTimeout, PUSB_ERROR pUsbRc);` */
/* (record-only: parameter or return type unpublished) */
/* ms919805 ReleaseRemoveLock: print `VOID ReleaseRemoveLock( IN PREMOVE_LOCK Lock, IN OPTIONAL PVOID Tag);` */
/* (record-only: parameter or return type unpublished) */
/* ms919806 ReleaseRemoveLockAndWait: print `VOID ReleaseRemoveLockAndWait( IN PREMOVE_LOCK Lock, IN OPTIONAL PVOID Tag);` */
/* (record-only: parameter or return type unpublished) */
/* ms919840 ResetBulkEndpoint: print `DWORD ResetBulkEndpoint( LPCUSB_FUNCS pUsbFuncs, HANDLE hUsbDevice, USB_PIPE hPipe, LPTRANSFER_NOTIFY_ROUTINE NotifyRoutine, PVOID NotifyContext, UCHAR bIndex, DWORD dwTimeout);` */
/* (record-only: parameter or return type unpublished) */
/* ms919843 ResetDefaultEndpoint: print `DWORD ResetDefaultEndpoint( LPCUSB_FUNCS UsbFuncs, HANDLE hUsbDevice);` */
/* (record-only: parameter or return type unpublished) */
/* ms919850 ResetPipe: print `BOOL ResetPipe( LPCUSB_FUNCS pUsbFuncs, USB_PIPE hPipe, DWORD dwFlags);` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_USBCLIENT_H */
