/*
 * Usbdi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-usbhost.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_USBDI_H
#define AKARI_USBDI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-usbhost (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923236 USB_DRIVER_SETTINGS (page print, compiled) */
typedef struct  {
    DWORD dwCount;
    DWORD dwVendorId;
    DWORD dwProductId;
    DWORD dwReleaseNumber;
    DWORD dwDeviceClass;
    DWORD dwDeviceSubClass;
    DWORD dwDeviceProtocol;
    DWORD dwInterfaceClass;
    DWORD dwInterfaceSubClass;
    DWORD dwInterfaceProtocol;
} USB_DRIVER_SETTINGS;
/* ms923216 USBDeviceAttach: print `` -- recorded verbatim (no compiled prototype) */
/* ms923254 USBInstallDriver: print `` */
BOOL USBInstallDriver(LPCWSTR szDriverLibFile);
/* ms923261 USBUnInstallDriver: print `` */
BOOL USBUnInstallDriver(void);

/* ------------------------------------------------------------------
 * Book surface: drivers-usbhost (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms899320 GetTransferError: print `` */
/* (record-only: parameter or return type unpublished) */
/* ms891069 CIsochronousPipe Class and CIsochTransfer Class Relationship */
/* aa447435 CQueuePipe Class and CTransfer Class Relationship */
/* ms892166 Implementing USB Host Controller Drivers */
/* ms892239 Installing the USB Host Mass Storage Client Driver on the Target Device */
/* ms892240 Installing the USB Host Printer Client Driver on the Target Device */
/* ms894079 Installing, Attaching, and Detaching USB Drivers */
/* ms894080 Loading USB Device Drivers */
/* ms894047 Supported USB Features */
/* ms894081 Testing USB Device Drivers */
/* aa448289 Testing USB Host Client Drivers for Compliance with the USB Specification */
/* aa448279 Troubleshooting: Connection Stability Between the USB Host Client Driver and the USB Host Controller Driver */
/* ms894075 USB 2.0 Common Code Implemented by the EHCI Driver */
/* ms894082 USB Devices */
/* ms894083 USB Driver Interface Functions */
/* ms894099 USB Host Client Driver Registry Settings */
/* ms894085 USB Host Controller Driver Registry Settings */
/* aa447627 USB Host Controller Driver Samples */
/* ms892165 USB Host Controller-specific Code */
/* ms893945 USB Host RNDIS Client Driver */
/* ms894721 USB System Software */
/* ms894725 USB Transfer Types */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_USBDI_H */
