/*
 * Usbfntypes.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-usbfn.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_USBFNTYPES_H
#define AKARI_USBFNTYPES_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-usbfn (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448328 UfnGetRegistryInfo: print `DWORD UfnGetRegistryInfo( LPCTSTR pszActiveKey, PUFN_CLIENT_REG_INFO pRegInfo);` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_USBFNTYPES_H */
