/*
 * Usbmsc.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-usbfn.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_USBMSC_H
#define AKARI_USBMSC_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-usbfn (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa448217 TRANSPORT_COMMAND (page print, compiled) */
typedef struct _TRANSPORT_COMMAND {
    DWORD Flags;
    DWORD Timeout;
    DWORD Length;
    DWORD dwLun;
    PVOID CommandBlock;
} TRANSPORT_COMMAND, *PTRANSPORT_COMMAND;
/* aa448218 TRANSPORT_DATA (page print, compiled) */
typedef struct _TRANSPORT_DATA_BUFFER {
    DWORD RequestLength;
    DWORD TransferLength;
    PVOID DataBlock;
} TRANSPORT_DATA, *PTRANSPORT_DATA;

#ifdef __cplusplus
}
#endif

#endif /* AKARI_USBMSC_H */
