/*
 * Usbtypes.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-usbhost.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_USBTYPES_H
#define AKARI_USBTYPES_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-usbhost (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923257 USB_INTERFACE_DESCRIPTOR (page print, compiled) */
typedef struct  {
    UCHAR bLength;
    UCHAR bDescriptorType;
    UCHAR bInterfaceNumber;
    UCHAR bAlternateSetting;
    UCHAR bNumEndpoints;
    UCHAR bInterfaceClass;
    UCHAR bInterfaceSubClass;
    UCHAR bInterfaceProtocol;
    UCHAR iInterface;
} USB_INTERFACE_DESCRIPTOR;
/* ms923188 USB_CONFIGURATION -- HELD (page print; member types unpublished):
 *   typedef struct _USB_CONFIGURATION { ... } USB_CONFIGURATION, * PUSB_CONFIGURATION, * LPUSB_CONFIGURATION; */
/* ms923207 USB_DEVICE -- HELD (page print; member types unpublished):
 *   typedef struct _USB_DEVICE { ... } USB_DEVICE, * PUSB_DEVICE, * LPUSB_DEVICE; */
/* ms923242 USB_ENDPOINT -- HELD (page print; member types unpublished):
 *   typedef struct _USB_ENDPOINT { ... } USB_ENDPOINT, * PUSB_ENDPOINT, * LPUSB_ENDPOINT; */
/* ms923256 USB_INTERFACE -- HELD (page print; member types unpublished):
 *   typedef struct _USB_INTERFACE { ... } USB_INTERFACE, * PUSB_INTERFACE, * LPUSB_INTERFACE; */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_USBTYPES_H */
