/*
 * Wavemdd.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-audio.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_WAVEMDD_H
#define AKARI_WAVEMDD_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms923281 WAV_Close: print `BOOL WAV_Close(DWORDdwOpenData);` */
BOOL WAV_Close(DWORD dwOpenData);
/* ms923282 WAV_Deinit: print `PVOID WAV_Deinit(DWORDdwData);` */
PVOID WAV_Deinit(DWORD dwData);
/* ms923290 WAV_Init: print `PVOID WAV_Init(DWORDdwInfo);` */
PVOID WAV_Init(DWORD dwInfo);
/* ms923292 WAV_Open: print `PVOID WAV_Open(DWORD dwData,DWORDdwAccess,DWORDdwShareMode);` */
PVOID WAV_Open(DWORD dwData, DWORD dwAccess, DWORD dwShareMode);
/* ms923293 WAV_PowerDown: print `void WAV_PowerDown(void);` */
void WAV_PowerDown(void);
/* ms923294 WAV_PowerUp: print `void WAV_PowerUp(void);` */
void WAV_PowerUp(void);
/* ms923295 WAV_Read: print `DWORD WAV_Read(DWORDdwOpenData,LPVOIDpBuf,DWORDlen);` */
DWORD WAV_Read(DWORD dwOpenData, LPVOID pBuf, DWORD len);
/* ms923296 WAV_Seek: print `DWORD WAV_Seek(DWORDdwOpenData,longpos,DWORDtype);` */
DWORD WAV_Seek(DWORD dwOpenData, long pos, DWORD type);
/* ms923297 WAV_Write: print `` */
DWORD WAV_Write(DWORD dwOpenData, LPCVOID pBuf, DWORD len);

#ifdef __cplusplus
}
#endif

#endif /* AKARI_WAVEMDD_H */
