/*
 * Wavedev.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-audio.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_WAVEDEV_H
#define AKARI_WAVEDEV_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms896092 ACMDRV_MESSAGE_PARAMS (page print, compiled) */
typedef struct  {
    DWORD dwDeviceID;
    HANDLE hDriver;
    UINT uMsg;
    LPARAM lParam1;
    LPARAM lParam2;
} ACMDRV_MESSAGE_PARAMS;

#ifdef __cplusplus
}
#endif

#endif /* AKARI_WAVEDEV_H */
