/*
 * Waveddsi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-audio.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_WAVEDDSI_H
#define AKARI_WAVEDDSI_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-audio (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms919392 PDD_AudioDeinitialize: print `VOID PDD_AudioDeinitialize(void);` */
VOID PDD_AudioDeinitialize(void);
/* ms919393 PDD_AudioGetInterruptType: print `AUDIO_STATE PDD_AudioGetInterruptType(void);` */
/* (record-only: parameter or return type unpublished) */
/* ms919394 PDD_AudioInitialize: print `BOOL PDD_AudioInitialize(DWORD dwIndex);` */
BOOL PDD_AudioInitialize(DWORD dwIndex);
/* ms919395 PDD_AudioMessage: print `` */
DWORD PDD_AudioMessage(UINT uMsg, DWORD dwParam1, DWORD dwParam2);
/* ms919396 PDD_AudioPowerHandler: print `VOID PDD_AudioPowerHandler(BOOLpower_down);` */
VOID PDD_AudioPowerHandler(BOOL power_down);
/* aa448324 PDD_IoControl: print `BOOL PDD_IoControl(PDWORDpdwOpenData, DWORDdwCode, PBYTEpBufIn, DWORDdwLenIn, PBYTEpBufOut, DWORDdwLenOut, PDWORDpdwActualOut);` */
BOOL PDD_IoControl(PDWORD pdwOpenData, DWORD dwCode, PBYTE pBufIn, DWORD dwLenIn, PBYTE pBufOut, DWORD dwLenOut, PDWORD pdwActualOut);
/* ms919399 PDD_WaveProc: print `` -- recorded verbatim (no compiled prototype) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_WAVEDDSI_H */
