/*
 * Wdm.h or Ntddk.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-network-rem.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_WDM_H
#define AKARI_WDM_H

#include <Windows.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-network-rem (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* aa447688 CONTAINING_RECORD: print `PCHAR CONTAINING_RECORD(PCHAR Address,TYPE Type,PCHAR Field);` */
/* (record-only: parameter or return type unpublished) */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_WDM_H */
