/*
 * Winddi.h -- Windows CE book-surface header of record (Akari API).
 *
 * Copyright (c) 2026 Akari API contributors
 * SPDX-License-Identifier: MIT
 *
 * Written from scratch from the official Microsoft Windows CE
 * documentation (learn.microsoft.com previous-versions archive;
 * page ids cited per record).  Source book(s): drivers-printer.
 * Generated by tools/gen-book.py.  Signatures are the pages' own
 * prints; glued print artifacts are split for compilation and the
 * verbatim prints are recorded in the per-row comments.
 */

#ifndef AKARI_WINDDI_H
#define AKARI_WINDDI_H

#include <Windows.h>
#include "Wingdi.h"    /* DEVMODEW (the display book compiled it there) */

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------
 * Book surface: drivers-printer (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct SURFOBJ SURFOBJ;   /* opaque carrier (layout unpublished) */
/* aa447744 DrvEndDoc: print `BOOL DrvEndDoc(SURFOBJ* pso,FLONG fl);` */
/* (record-only: parameter or return type unpublished) */
/* aa447758 DrvStartDoc: print `BOOL DrvStartDoc(SURFOBJ* pso,PWSTR pwszDocName,DWORD dwJobId);` */
BOOL DrvStartDoc(SURFOBJ* pso, PWSTR pwszDocName, DWORD dwJobId);
/* aa447759 DrvStartPage: print `BOOL DrvStartPage(SURFOBJ* pso);` */
BOOL DrvStartPage(SURFOBJ* pso);

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
typedef struct BRUSHOBJ BRUSHOBJ;   /* opaque carrier (layout unpublished) */
typedef struct CLIPOBJ CLIPOBJ;   /* opaque carrier (layout unpublished) */
typedef struct HSURF HSURF;   /* opaque carrier (layout unpublished) */
typedef struct LINEATTRS LINEATTRS;   /* opaque carrier (layout unpublished) */
typedef struct PALOBJ PALOBJ;   /* opaque carrier (layout unpublished) */
typedef struct PATHDATA PATHDATA;   /* opaque carrier (layout unpublished) */
typedef struct PATHOBJ PATHOBJ;   /* opaque carrier (layout unpublished) */
typedef struct XFORMOBJ XFORMOBJ;   /* opaque carrier (layout unpublished) */
typedef struct XLATEOBJ XLATEOBJ;   /* opaque carrier (layout unpublished) */
/* aa447784 ENGCALLBACKS -- HELD (page print; member types unpublished):
 *   typedef struct _ENGCALLBACKS { ... } ENGCALLBACKS, * PENGCALLBACKS; */
/* ms923693 XLATEOBJ -- HELD (page print; member types unpublished):
 *   typedef struct _XLATEOBJ { ... } XLATEOBJ; */
/* ms896145 BRUSHOBJ_pvAllocRbrush: print `PVOID BRUSHOBJ_pvAllocRbrush( BRUSHOBJ* pbo, ULONG cj);` */
AKARI_CE_IMPORT PVOID BRUSHOBJ_pvAllocRbrush(BRUSHOBJ* pbo, ULONG cj)
    AKARI_CE_NAME(BRUSHOBJ_pvAllocRbrush);
/* ms896146 BRUSHOBJ_pvGetRbrush: print `PVOID BRUSHOBJ_pvGetRbrush( BRUSHOBJ* pbo,);` */
AKARI_CE_IMPORT PVOID BRUSHOBJ_pvGetRbrush(BRUSHOBJ* pbo)
    AKARI_CE_NAME(BRUSHOBJ_pvGetRbrush);
/* aa447668 CLIPOBJ_bEnum: print `BOOL CLIPOBJ_bEnum( CLIPOBJ* pco, ULONG cj, ULONG* pv);` */
AKARI_CE_IMPORT BOOL CLIPOBJ_bEnum(CLIPOBJ* pco, ULONG cj, ULONG* pv)
    AKARI_CE_NAME(CLIPOBJ_bEnum);
/* aa447669 CLIPOBJ_cEnumStart: print `ULONG CLIPOBJ_cEnumStart( IN CLIPOBJ* pco, BOOL bAll, ULONG iType, ULONG iDirection, ULONG cLimit);` */
AKARI_CE_IMPORT ULONG CLIPOBJ_cEnumStart(CLIPOBJ* pco, BOOL bAll, ULONG iType, ULONG iDirection, ULONG cLimit)
    AKARI_CE_NAME(CLIPOBJ_cEnumStart);
/* ms898301 DisplayInit: print `BOOL APIENTRY DisplayInit(LPCTSTR pszInstance, DWORD dwNumMonitors);` */
/* (record-only: parameter or return type unpublished) */
/* aa447731 DrvAnyBlt: print `BOOL DrvAnyBlt( SURFOBJ* psoDst, SURFOBJ* psoSrc, SURFOBJ* psoMask, CLIPOBJ* pco, XLATEOBJ* pxlo, POINTL* pptlHTOrg, RECTL* prclDst, POINTL* pptlSrc, POINTL* pptlMask, BRUSHOBJ* pbo, POINTL* pptlBrush, ROP4 rop4, ULONG iMode, ULONG bltFlags);` */
/* (record-only: parameter or return type unpublished) */
/* aa447732 DrvBitBlt: print `BOOL DrvBitBlt( SURFOBJ* psoTrg, SURFOBJ* psoSrc, SURFOBJ* psoMask, CLIPOBJ* pco, XLATEOBJ* pxlo, RECTL* prclTrg, POINTL* pptlSrc, POINTL* pptlMask, BRUSHOBJ* pbo, POINTL* pptlBrush, ROP4 rop4);` */
/* (record-only: parameter or return type unpublished) */
/* aa447734 DrvCopyBits: print `BOOL DrvCopyBits(SURFOBJ* psoDst,SURFOBJ* psoSrc,CLIPOBJ* pco,XLATEOBJ* pxlo,RECTL* prclDst,POINTL* pptlSrc);` */
AKARI_CE_IMPORT BOOL DrvCopyBits(SURFOBJ* psoDst, SURFOBJ* psoSrc, CLIPOBJ* pco, XLATEOBJ* pxlo, RECTL* prclDst, POINTL* pptlSrc)
    AKARI_CE_NAME(DrvCopyBits);
/* aa447735 DrvCreateDeviceBitmap: print `HBITMAP DrvCreateDeviceBitmap( DHPDEV dhpdev, SIZEL sizl, ULONG iFormat);` */
/* (record-only: parameter or return type unpublished) */
/* aa447736 DrvDeleteDeviceBitmap: print `VOID DrvDeleteDeviceBitmap( DHSURF dhsurf);` */
/* (record-only: parameter or return type unpublished) */
/* aa447737 DrvDisableDriver: print `VOID DrvDisableDriver(VOID);` */
AKARI_CE_IMPORT VOID DrvDisableDriver(void)
    AKARI_CE_NAME(DrvDisableDriver);
/* aa447738 DrvDisablePDEV: print `VOID DrvDisablePDEV(DHPDEV dhpdev);` */
/* (record-only: parameter or return type unpublished) */
/* aa447739 DrvDisableSurface: print `VOID DrvDisableSurface(DHPDEV dhpdev);` */
/* (record-only: parameter or return type unpublished) */
/* aa447741 DrvEnableDriver: print `BOOL APIENTRY DrvEnableDriver( ULONG iEngineVersion, ULONG cj, DRVENABLEDATA* pded, PENGCALLBACKS pEngCallbacks);` */
/* (record-only: parameter or return type unpublished) */
/* aa447742 DrvEnablePDEV: print `DHPDEV APIENTRY DrvEnablePDEV(DEVMODEW* pdm,LPWSTR pwszLogAddress,ULONG cPat,HSURF* phsurfPatterns,ULONG cjCaps,ULONG* pdevcaps,ULONG cjDevInfo,DEVINFO* pdi,HDEV hdev,LPWSTR pwszDeviceName,HANDLE hDriver);` */
/* (record-only: parameter or return type unpublished) */
/* aa447743 DrvEnableSurface: print `HSURF DrvEnableSurface(DHPDEV dhpdev);` */
/* (record-only: parameter or return type unpublished) */
/* aa447745 DrvEscape: print `ULONG DrvEscape( DHPDEV dhpdev, SURFOBJ* pso, ULONG iEsc, ULONG cjIn, PVOID pvIn, ULONG cjOut, PVOID pvOut);` */
/* (record-only: parameter or return type unpublished) */
/* aa447746 DrvFillPath: print `BOOL DrvFillPath( SURFOBJ* pso, PATHOBJ* ppo, CLIPOBJ* pco, BRUSHOBJ* pbo, POINTL* pptlBrushOrg, MIX mix, FLONG flOptions);` */
/* (record-only: parameter or return type unpublished) */
/* aa447747 DrvGetMasks: print `ULONG * DrvGetMasks ( DHPDEV dhpdev);` */
/* (record-only: parameter or return type unpublished) */
/* aa447748 DrvGetModes: print `ULONG DrvGetModes(HANDLE hDriver,ULONG cjSize,DEVMODEW* pdm);` */
AKARI_CE_IMPORT ULONG DrvGetModes(HANDLE hDriver, ULONG cjSize, DEVMODEW* pdm)
    AKARI_CE_NAME(DrvGetModes);
/* aa447749 DrvGradientFill: print `BOOL DrvGradientFill( SURFOBJ* pso, CLIPOBJ* pco, XLATEOBJ* pxlo, TRIVERTEX* pVertex, ULONG nVertex, PVOID pMesh, ULONG nMesh, RECTL* prclExtents, POINTL* pptlDitherOrg, ULONG ulMode);` */
AKARI_CE_IMPORT BOOL DrvGradientFill(SURFOBJ* pso, CLIPOBJ* pco, XLATEOBJ* pxlo, TRIVERTEX* pVertex, ULONG nVertex, PVOID pMesh, ULONG nMesh, RECTL* prclExtents, POINTL* pptlDitherOrg, ULONG ulMode)
    AKARI_CE_NAME(DrvGradientFill);
/* aa447750 DrvMovePointer: print `VOID DrvMovePointer( SURFOBJ* pso, LONG x, LONG y, RECTL* prcl);` */
AKARI_CE_IMPORT VOID DrvMovePointer(SURFOBJ* pso, LONG x, LONG y, RECTL* prcl)
    AKARI_CE_NAME(DrvMovePointer);
/* aa447752 DrvPaint: print `BOOL DrvPaint( SURFOBJ* pso, CLIPOBJ* pco, BRUSHOBJ* pbo, POINTL* pptlBrushOrg, MIX mix);` */
/* (record-only: parameter or return type unpublished) */
/* aa447753 DrvPowerHandler: print `VOID DrvPowerHandler( DHPDEV dhpdev, BOOL bOff,);` */
/* (record-only: parameter or return type unpublished) */
/* aa447754 DrvRealizeBrush: print `BOOL DrvRealizeBrush( BRUSHOBJ* pbo, SURFOBJ* psoTarget, SURFOBJ* psoPattern, SURFOBJ* psoMask, XLATEOBJ* pxlo, ULONG iHatch);` */
AKARI_CE_IMPORT BOOL DrvRealizeBrush(BRUSHOBJ* pbo, SURFOBJ* psoTarget, SURFOBJ* psoPattern, SURFOBJ* psoMask, XLATEOBJ* pxlo, ULONG iHatch)
    AKARI_CE_NAME(DrvRealizeBrush);
/* aa447755 DrvRealizeColor: print `ULONG DrvRealizeColor( USHORT iDstType, ULONG cEntries, ULONG* pPalette, ULONG rgbColor);` */
AKARI_CE_IMPORT ULONG DrvRealizeColor(USHORT iDstType, ULONG cEntries, ULONG* pPalette, ULONG rgbColor)
    AKARI_CE_NAME(DrvRealizeColor);
/* aa447756 DrvSetPalette: print `BOOL DrvSetPalette( DHPDEV dhpdev, PALOBJ* ppalo, FLONG fl, ULONG iStart, ULONG cColors);` */
/* (record-only: parameter or return type unpublished) */
/* aa447757 DrvSetPointerShape: print `ULONG DrvSetPointerShape( SURFOBJ* pso, SURFOBJ* psoMask, SURFOBJ* psoColor, XLATEOBJ* pxlo, LONG xHot, LONG yHot, LONG x, LONG y, RECTL* prcl, FLONG fl);` */
/* (record-only: parameter or return type unpublished) */
/* aa447760 DrvStrokePath: print `BOOL DrvStrokePath( SURFOBJ* pso, PATHOBJ* ppo, CLIPOBJ* pco, XFORMOBJ* pxo, BRUSHOBJ* pbo, POINTL* pptlBrushOrg, LINEATTRS* plineattrs, MIX mix);` */
/* (record-only: parameter or return type unpublished) */
/* aa447761 DrvTransparentBlt: print `BOOL DrvTransparentBlt( SURFOBJ* psoDst, SURFOBJ* psoSrc, CLIPOBJ* pco, XLATEOBJ* pxlo, RECTL* prclDst, RECTL* prclSrc, ULONG iTransColor);` */
AKARI_CE_IMPORT BOOL DrvTransparentBlt(SURFOBJ* psoDst, SURFOBJ* psoSrc, CLIPOBJ* pco, XLATEOBJ* pxlo, RECTL* prclDst, RECTL* prclSrc, ULONG iTransColor)
    AKARI_CE_NAME(DrvTransparentBlt);
/* aa447762 DrvUnrealizeColor: print `ULONG APIENTRY DrvUnrealizeColor( USHORT iSrcType, ULONG cEntries, ULONG* pPalette, ULONG iRealizedColor);` */
/* (record-only: parameter or return type unpublished) */
/* aa447785 EngCreateDeviceBitmap: print `HBITMAP EngCreateDeviceBitmap( DHSURF dhsurf, SIZEL sizl, ULONG iFormatCompat);` */
/* (record-only: parameter or return type unpublished) */
/* aa447786 EngCreateDeviceSurface: print `HSURF EngCreateDeviceSurface( DHSURF dhsurf, SIZEL sizl, ULONG iFormatCompat);` */
/* (record-only: parameter or return type unpublished) */
/* aa447787 EngCreatePalette: print `HPALETTE EngCreatePalette( ULONG iMode, ULONG cColors, ULONG* pulColors, FLONG flRed, FLONG flGreen, FLONG flBlue);` */
/* (record-only: parameter or return type unpublished) */
/* aa447788 EngDeleteSurface: print `BOOL EngDeleteSurface( HSURF hsurf);` */
AKARI_CE_IMPORT BOOL EngDeleteSurface(HSURF hsurf)
    AKARI_CE_NAME(EngDeleteSurface);
/* ms919337 PALOBJ_cGetColors: print `ULONG PALOBJ_cGetColors( PALOBJ* ppalo, ULONG iStart, ULONG cColors, ULONG* pulColors);` */
AKARI_CE_IMPORT ULONG PALOBJ_cGetColors(PALOBJ* ppalo, ULONG iStart, ULONG cColors, ULONG* pulColors)
    AKARI_CE_NAME(PALOBJ_cGetColors);
/* ms919360 PATHOBJ_bEnum: print `BOOL PATHOBJ_bEnum( PATHOBJ* ppo, PATHDATA* ppd);` */
AKARI_CE_IMPORT BOOL PATHOBJ_bEnum(PATHOBJ* ppo, PATHDATA* ppd)
    AKARI_CE_NAME(PATHOBJ_bEnum);
/* ms919375 PATHOBJ_vEnumStart: print `VOID PATHOBJ_vEnumStart( PATHOBJ* ppo);` */
AKARI_CE_IMPORT VOID PATHOBJ_vEnumStart(PATHOBJ* ppo)
    AKARI_CE_NAME(PATHOBJ_vEnumStart);
/* ms919370 PATHOBJ_vGetBounds: print `VOID PATHOBJ_vGetBounds( PATHOBJ* ppo, PRECTFX prectfx);` */
/* (record-only: parameter or return type unpublished) */
/* ms923694 XLATEOBJ_cGetPalette: print `ULONG XLATEOBJ_cGetPalette( XLATEOBJ* pxlo, ULONG iPal, ULONG cPal, ULONG* pPal);` */
AKARI_CE_IMPORT ULONG XLATEOBJ_cGetPalette(XLATEOBJ* pxlo, ULONG iPal, ULONG cPal, ULONG* pPal)
    AKARI_CE_NAME(XLATEOBJ_cGetPalette);

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890437 Accelerated Line Segment Function */
/* ms890528 Advanced Display Driver Power Management */
/* ms890543 Antialiased Font Support */
/* ms890627 ATI Sample Display Driver Optimization */
/* ms890765 Benefits and Limitations of GPE Display Drivers */
/* ms890816 Bit Block Transfer Acceleration */
/* ms896142 BitBlT Emulation Library Functions */
/* ms923765 Building DispPerf.exe */
/* ms891084 ClearType */
/* ms891144 ColorConverter */
/* aa447433 Contrast Control */
/* aa448245 Creating a Display Driver Based on the GPE Classes */
/* aa448246 Creating a Target Application for Profiling the FLAT Display Driver */
/* aa447456 DDI Functions */
/* aa447494 Display Buffer Formats */
/* aa448251 Display Device Performance Profile Analysis */
/* aa447499 Display Driver Migration */
/* aa447501 Display Driver Performance Profiling */
/* aa447503 Display Driver Recommendations */
/* aa447504 Display Driver Registry Settings */
/* aa447508 Display Driver Security */
/* aa447507 Display Drivers and the Run-Time Image */
/* aa448252 Enabling Monte Carlo Profiling of a Configuration */
/* ms892154 FLAT Sample Display Driver */
/* ms892157 GDI Support Services */
/* ms892160 GPE */
/* ms892162 GPESurf */
/* ms892163 GPEVGA */
/* aa448254 Implementing the GenBltCpuInitialize Function */
/* aa448255 Implementing the Optimization Function */
/* aa448256 Implementing the Translation Function */
/* ms892485 Line Drawing */
/* ms892486 Line Drawing Acceleration */
/* ms892503 Multiple Screen Driver Support */
/* ms892546 Node2D */
/* aa448261 Obtaining a Performance Profile for a Display Driver */
/* ms892556 Optimized GPE Emulation Function Analysis */
/* ms892557 Optimizing a GPE Emulation Function */
/* aa447567 Primary Display Drivers */
/* aa447622 Sample Blit Acceleration */
/* aa447624 Sample DrvEscape Function */
/* ms893969 Screen Rotation */
/* ms893979 Secondary Display Drivers */
/* ms894032 Source Code for ProfApp */
/* aa448295 VGA Support */

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890437 Accelerated Line Segment Function */
/* ms890528 Advanced Display Driver Power Management */
/* ms890543 Antialiased Font Support */
/* ms890627 ATI Sample Display Driver Optimization */
/* ms890765 Benefits and Limitations of GPE Display Drivers */
/* ms890816 Bit Block Transfer Acceleration */
/* ms896142 BitBlT Emulation Library Functions */
/* ms923765 Building DispPerf.exe */
/* ms891084 ClearType */
/* ms891144 ColorConverter */
/* aa447433 Contrast Control */
/* aa448245 Creating a Display Driver Based on the GPE Classes */
/* aa448246 Creating a Target Application for Profiling the FLAT Display Driver */
/* aa447456 DDI Functions */
/* aa447494 Display Buffer Formats */
/* aa448251 Display Device Performance Profile Analysis */
/* aa447499 Display Driver Migration */
/* aa447501 Display Driver Performance Profiling */
/* aa447503 Display Driver Recommendations */
/* aa447504 Display Driver Registry Settings */
/* aa447508 Display Driver Security */
/* aa447507 Display Drivers and the Run-Time Image */
/* aa448252 Enabling Monte Carlo Profiling of a Configuration */
/* ms892154 FLAT Sample Display Driver */
/* ms892157 GDI Support Services */
/* ms892160 GPE */
/* ms892162 GPESurf */
/* ms892163 GPEVGA */
/* aa448254 Implementing the GenBltCpuInitialize Function */
/* aa448255 Implementing the Optimization Function */
/* aa448256 Implementing the Translation Function */
/* ms892485 Line Drawing */
/* ms892486 Line Drawing Acceleration */
/* ms892503 Multiple Screen Driver Support */
/* ms892546 Node2D */
/* aa448261 Obtaining a Performance Profile for a Display Driver */
/* ms892556 Optimized GPE Emulation Function Analysis */
/* ms892557 Optimizing a GPE Emulation Function */
/* aa447567 Primary Display Drivers */
/* aa447622 Sample Blit Acceleration */
/* aa447624 Sample DrvEscape Function */
/* ms893969 Screen Rotation */
/* ms893979 Secondary Display Drivers */
/* ms894032 Source Code for ProfApp */
/* aa448295 VGA Support */

/* ------------------------------------------------------------------
 * Book surface: drivers-display (tools/gen-book.py; page ids per record)
 * ------------------------------------------------------------------ */
/* ms890437 Accelerated Line Segment Function */
/* ms890528 Advanced Display Driver Power Management */
/* ms890543 Antialiased Font Support */
/* ms890627 ATI Sample Display Driver Optimization */
/* ms890765 Benefits and Limitations of GPE Display Drivers */
/* ms890816 Bit Block Transfer Acceleration */
/* ms896142 BitBlT Emulation Library Functions */
/* ms923765 Building DispPerf.exe */
/* ms891084 ClearType */
/* ms891144 ColorConverter */
/* aa447433 Contrast Control */
/* aa448245 Creating a Display Driver Based on the GPE Classes */
/* aa448246 Creating a Target Application for Profiling the FLAT Display Driver */
/* aa447456 DDI Functions */
/* aa447494 Display Buffer Formats */
/* aa448251 Display Device Performance Profile Analysis */
/* aa447499 Display Driver Migration */
/* aa447501 Display Driver Performance Profiling */
/* aa447503 Display Driver Recommendations */
/* aa447504 Display Driver Registry Settings */
/* aa447508 Display Driver Security */
/* aa447507 Display Drivers and the Run-Time Image */
/* aa448252 Enabling Monte Carlo Profiling of a Configuration */
/* ms892154 FLAT Sample Display Driver */
/* ms892157 GDI Support Services */
/* ms892160 GPE */
/* ms892162 GPESurf */
/* ms892163 GPEVGA */
/* aa448254 Implementing the GenBltCpuInitialize Function */
/* aa448255 Implementing the Optimization Function */
/* aa448256 Implementing the Translation Function */
/* ms892485 Line Drawing */
/* ms892486 Line Drawing Acceleration */
/* ms892503 Multiple Screen Driver Support */
/* ms892546 Node2D */
/* aa448261 Obtaining a Performance Profile for a Display Driver */
/* ms892556 Optimized GPE Emulation Function Analysis */
/* ms892557 Optimizing a GPE Emulation Function */
/* aa447567 Primary Display Drivers */
/* aa447622 Sample Blit Acceleration */
/* aa447624 Sample DrvEscape Function */
/* ms893969 Screen Rotation */
/* ms893979 Secondary Display Drivers */
/* ms894032 Source Code for ProfApp */
/* aa448295 VGA Support */

#ifdef __cplusplus
}
#endif

#endif /* AKARI_WINDDI_H */
