/* Windot11.h -- native 802.11 object identifiers (record-only).
 *
 * Source pages: Network Driver Reference rows printing
 * "Header: Windot11.h" (101 pages).  Every page is an OID_DOT11_*
 * object-identifier description; no CE page prints a value or a
 * type layout for this header, so the identifiers are recorded as
 * names only.  See docs/inventory.md M78c.
 */

#ifndef AKARI_WINDOT11_H
#define AKARI_WINDOT11_H

/* --- Recorded OID_DOT11_* names (values not printed). ----------
 * 101 identifiers (grouped alphabetically):
 *   OID_DOT11_AP_JOIN_REQUEST, OID_DOT11_ATIM_WINDOW,
 *   OID_DOT11_BEACON_PERIOD, OID_DOT11_CCA_MODE_SUPPORTED,
 *   OID_DOT11_CCA_WATCHDOG_COUNT_MAX, OID_DOT11_CCA_WATCHDOG_COUNT_MIN,
 *   OID_DOT11_CCA_WATCHDOG_TIMER_MAX, OID_DOT11_CCA_WATCHDOG_TIMER_MIN,
 *   OID_DOT11_CFP_MAX_DURATION, OID_DOT11_CFP_PERIOD,
 *   OID_DOT11_CF_POLLABLE, OID_DOT11_CHANNEL_AGILITY_ENABLED,
 *   OID_DOT11_CHANNEL_AGILITY_PRESENT, OID_DOT11_COUNTERS_ENTRY,
 *   OID_DOT11_COUNTRY_STRING, OID_DOT11_CURRENT_CCA_MODE,
 *   OID_DOT11_CURRENT_CHANNEL, OID_DOT11_CURRENT_CHANNEL_NUMBER,
 *   OID_DOT11_CURRENT_DWELL_TIME, OID_DOT11_CURRENT_FREQUENCY,
 *   OID_DOT11_CURRENT_INDEX, OID_DOT11_CURRENT_OFFLOAD_CAPABILITY,
 *   OID_DOT11_CURRENT_OPERATION_MODE,
 *   OID_DOT11_CURRENT_OPTIONAL_CAPABILITY,
 *   OID_DOT11_CURRENT_PACKET_FILTER, OID_DOT11_CURRENT_PATTERN,
 *   OID_DOT11_CURRENT_PHY_TYPE, OID_DOT11_CURRENT_REG_DOMAIN,
 *   OID_DOT11_CURRENT_RX_ANTENNA, OID_DOT11_CURRENT_SET,
 *   OID_DOT11_CURRENT_TX_ANTENNA, OID_DOT11_CURRENT_TX_POWER_LEVEL,
 *   OID_DOT11_DEFAULT_WEP_OFFLOAD, OID_DOT11_DEFAULT_WEP_UPLOAD,
 *   OID_DOT11_DIVERSITY_SELECTION_RX, OID_DOT11_DIVERSITY_SUPPORT,
 *   OID_DOT11_DSSS_OFDM_OPTION_ENABLED,
 *   OID_DOT11_DSSS_OFDM_OPTION_IMPLEMENTED, OID_DOT11_DTIM_PERIOD,
 *   OID_DOT11_ED_THRESHOLD, OID_DOT11_EHCC_CAPABILITY_ENABLED,
 *   OID_DOT11_EHCC_CAPABILITY_IMPLEMENTED,
 *   OID_DOT11_EHCC_NUMBER_OF_CHANNELS_FAMILY_INDEX,
 *   OID_DOT11_EHCC_PRIME_RADIX, OID_DOT11_ERP_PBCC_OPTION_ENABLED,
 *   OID_DOT11_ERP_PBCC_OPTION_IMPLEMENTED,
 *   OID_DOT11_FRAGMENTATION_THRESHOLD,
 *   OID_DOT11_FREQUENCY_BANDS_SUPPORTED, OID_DOT11_HOPPING_PATTERN,
 *   OID_DOT11_HOP_ALGORITHM_ADOPTED, OID_DOT11_HOP_MODULUS,
 *   OID_DOT11_HOP_OFFSET, OID_DOT11_HOP_TIME,
 *   OID_DOT11_HR_CCA_MODE_SUPPORTED, OID_DOT11_JOIN_REQUEST,
 *   OID_DOT11_LONG_RETRY_LIMIT, OID_DOT11_MAC_ADDRESS,
 *   OID_DOT11_MAX_DWELL_TIME, OID_DOT11_MAX_MAC_ADDRESS_STATES,
 *   OID_DOT11_MAX_RECEIVE_LIFETIME,
 *   OID_DOT11_MAX_TRANSMIT_MSDU_LIFETIME,
 *   OID_DOT11_MEDIUM_OCCUPANCY_LIMIT, OID_DOT11_MPDU_MAX_LENGTH,
 *   OID_DOT11_MULTI_DOMAIN_CAPABILITY,
 *   OID_DOT11_MULTI_DOMAIN_CAPABILITY_ENABLED,
 *   OID_DOT11_MULTI_DOMAIN_CAPABILITY_IMPLEMENTED,
 *   OID_DOT11_NIC_POWER_STATE, OID_DOT11_NIC_SPECIFIC_EXTENSION,
 *   OID_DOT11_NUMBER_OF_HOPPING_SETS, OID_DOT11_OFFLOAD_CAPABILITY,
 *   OID_DOT11_OPERATIONAL_RATE_SET, OID_DOT11_OPERATION_MODE_CAPABILITY,
 *   OID_DOT11_OPTIONAL_CAPABILITY, OID_DOT11_PBCC_OPTION_IMPLEMENTED,
 *   OID_DOT11_POWER_MGMT_MODE, OID_DOT11_RANDOM_TABLE_FLAG,
 *   OID_DOT11_RECV_SENSITIVITY_LIST,
 *   OID_DOT11_REG_DOMAINS_SUPPORT_VALUE, OID_DOT11_RESET_REQUEST,
 *   OID_DOT11_RF_USAGE, OID_DOT11_RSSI_RANGE, OID_DOT11_RTS_THRESHOLD,
 *   OID_DOT11_SCAN_REQUEST, OID_DOT11_SHORT_PREAMBLE_OPTION_IMPLEMENTED,
 *   OID_DOT11_SHORT_RETRY_LIMIT,
 *   OID_DOT11_SHORT_SLOT_TIME_OPTION_ENABLED,
 *   OID_DOT11_SHORT_SLOT_TIME_OPTION_IMPLEMENTED,
 *   OID_DOT11_START_REQUEST, OID_DOT11_STATION_ID,
 *   OID_DOT11_SUPPORTED_DATA_RATES_VALUE, OID_DOT11_SUPPORTED_PHY_TYPES,
 *   OID_DOT11_SUPPORTED_POWER_LEVELS, OID_DOT11_SUPPORTED_RX_ANTENNA,
 *   OID_DOT11_SUPPORTED_TX_ANTENNA, OID_DOT11_TEMP_TYPE,
 *   OID_DOT11_TI_THRESHOLD, OID_DOT11_UPDATE_IE,
 *   OID_DOT11_WEP_ICV_ERROR_COUNT, OID_DOT11_WEP_OFFLOAD,
 *   OID_DOT11_WEP_UPLOAD, OID_DOT11_WPA_TSC
 */

#endif /* AKARI_WINDOT11_H */
